### ISSUE TITLE
showsHorizontal(Vertical)ScrollIndicator property on ASCollectionNode does nothing

### ISSUE THREAD

**Issue by man-in-black382** [TextureGroup/Texture#1009]
I believe this is because somebody simply forgot to apply these properties to collection view from pending state (`_ASCollectionPendingState`) in `ASCollectionNode`'s `- (void)didLoad` method

**Comment by ay8s** [comment]
Seen this also recently. for now you can do...

```
[collectionNode.view setShowsVerticalScrollIndicator:NO];
[collectionNode.view setShowsHorizontalScrollIndicator:NO];
```

**Comment by ay8s** [comment]
Can be closed 👍
