### ISSUE TITLE
ASCollectionNode requests cell but doesn't show it #ASCollectionNode #ASCellNode

### ISSUE THREAD

**Issue by tataevr** [TextureGroup/Texture#1051]
Hello. I'm trying to show ASCollectionNode in ASDisplayNode, but nothing happens. 
I had add some breakpoints, where i can see that cell is requested, but after that - it isn't displayed, which is really strange. 
[InstaClone.zip](https://github.com/TextureGroup/Texture/files/2229053/InstaClone.zip)
Using Texture 2.7

I'll be very glad for help.

**Comment by maicki** [comment]
@tataevr In `ProfileFeedView.init()` set the `delegate` of the `galleryLayout` to `self`: `galleryLayout.propertiesProvider = self`. It looks kind of broken though after so you either should fix the layout with the `ASCollectionGalleryLayoutDelegate` delegate methods or I would suggest using `UICollectionViewFlowLayout`.

**Comment by tataevr** [comment]
@maicki thank you so much. I feel myself kind a stupid. Well, now i'll remember that. So, another thing that is strange, is that ASCollectionNode doesn't pick height based on height of item. What do you think about it? Can i fix it?
Thank you for your response.
