### ISSUE TITLE
[ASImageNode]Incorrect calculation for backing size calculation

### ISSUE THREAD

**Issue by junjielu** [TextureGroup/Texture#1052]
In demo project and screenshot, I create 2 simple `ASImageNode` with `UIViewContentModeScaleAspectFit`.
However, change the height of node will make image "blurred".

I also find that #836 has mentioned this issue too.I read the code about `ASCroppedImageBackingSizeAndDrawRectInBounds`, and I think there is something wrong with image draw rect calculation.

[Sample Project](https://github.com/junjielu/ImageNodeTest)

![preview](https://user-images.githubusercontent.com/5674818/43250190-5c5125b8-90ef-11e8-934b-b54dbab16801.png)
@nguyenhuy @appleguy

**Comment by junjielu** [comment]
#836

**Comment by junjielu** [comment]
Somebody help?

**Comment by TheRealVictor** [comment]
You might be able to use this answer 😄: https://github.com/TextureGroup/Texture/issues/836#issuecomment-380450873

**Comment by junjielu** [comment]
> You might be able to use this answer 😄: [#836 (comment)](https://github.com/TextureGroup/Texture/issues/836#issuecomment-380450873)

Thanks~
Yep, but I don't want to make image upscale, it may affect performance.
I think it's a bug of image draw rect calculation.
