### ISSUE TITLE
ASCollectionNode Crash

### ISSUE THREAD

**Issue by Monkey-Sun** [TextureGroup/Texture#1057]
When i try to  pull down load net data for the page No.1, the net data not complete,  at the same time i pull up load more data , crash. 
 
Crash Info:
*** Assertion failure in -[ASCollectionView collectionView:cellForItemAtIndexPath:], /Users/admin/Documents/Git/NongJiaAPPPingGuo2/FarmProj/Pods/AsyncDisplayKit/AsyncDisplayKit/ASCollectionView.mm:951

ASDisplayNodeAssert(node != nil, @"Cell node should exist. indexPath = %@, collectionDataSource = %@", indexPath, self);

this crash happened sometimes , not every time.

why????

**Comment by ay8s** [comment]
Can you see if you encounter the same using master?

**Comment by Monkey-Sun** [comment]
Thanks, i update pods AsyncDisplayKit 2.2.0 to Texture 2.7, this bug appear probability lower, it hanppen in iPhone 4 sometimes, iPhone 6 never hanpen again. 
Very strange bug.
