### ISSUE TITLE
How to get frame of ASButtonNode inside ASCellNode

### ISSUE THREAD

**Issue by pawansn** [TextureGroup/Texture#1093]
I want to get frame of button on it's click event which is inside the ASCellNode

**Comment by ay8s** [comment]
We use something similar to this...

```
YourCellNode *cell = (YourCellNode *)[self.collectionNode nodeForItemAtIndexPath:[self.collectionNode indexPathForNode:node]];
```

Then use that to then retrieve the frame of the button. 

```
CGRect rectInCell = [cell.view convertRect:cell.yourButton.frame toView:cell.view];
```

**Comment by pawansn** [comment]
Hey @ay8s 

Thanks for your answer

But I'm using ASTableNode and it's only indexPathForRow(at:) method is available

**Comment by pawansn** [comment]
Hey, I got proper rect by implementing below code on click event of button
          `let buttonPosition = sender.view.convert(sender.bounds.origin, to: tblViewHome.view) //got button position
            let indexPath = self.tblViewHome.indexPathForRow(at: buttonPosition) //got indexpath 
            let cell = self.tblViewHome.nodeForRow(at: indexPath!) as! HomeCellNode //got cell
            let rect = cell.view.convert(cell.btnTrophy.frame, to: self.tblViewHome.supernode?.view) //finally got button rect
            print("rect is \(rect)")`
