### ISSUE TITLE
[IGListAdapter setASDKCollectionNode:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by bigship** [TextureGroup/Texture#1097]
Hi, I'm trying to use Texture and IGListKit together.  I use cocoaPod to install Texture and IGListKit.
Texture version: 2.7
IGListKit version: 3.4.0

But my example app crashes every time due to 
`-[IGListAdapter setASDKCollectionNode:]: unrecognized selector sent to instance`

I've already checked, `setASDKCollectionNode` is implemented in `IGListAdapter+AsyncDisplayKit.m`, and I already add that file to the compile sources.

Here's the code I copyed from ASDKgram example project and use that code in my own examples
``` 
- (instancetype)init {
    UICollectionViewFlowLayout *layout = [[UICollectionViewFlowLayout alloc] init]; 
    ASCollectionNode *node = [[ASCollectionNode alloc] initWithCollectionViewLayout:layout];
    if (self = [super initWithNode:node]) {
        IGListAdapterUpdater *updater = [[IGListAdapterUpdater alloc] init];
        _listAdapter = [[IGListAdapter alloc] initWithUpdater:updater viewController:self workingRangeSize:0];
        _listAdapter.dataSource = self;
        [_listAdapter setASDKCollectionNode:self.collectionNode];   // Crash here !
    }
    return self;
}
```

The strange thing is ASDKgram project can compile and run without crash. So I think it maybe has something to do with my own Xcode settings ?  I've stuck here for a day, anyone know how to solve it ?

PS: I can reproduce the crash. Just create a new project, and install Texture and IGListKit via cocoapod, and use the code I pasted above.

**Comment by ay8s** [comment]
Are you able to post the project that reproduces? Happy to take a look 👍

**Comment by bigship** [comment]
@ay8s Hey, thanks for the reply.  OK, I put a demo project on Github, please clone this repository [](https://github.com/bigship/IGListTest.git)

**Comment by maicki** [comment]
@bigship Hey - let's change your `Podfile` to and it should work.:
```
target 'IGListTest' do
    pod 'Texture'
    pod 'Texture/IGListKit'
    pod 'IGListKit'
end
```

 I will close this issue, please reopen if not resolved yet. Thanks!

**Comment by bigship** [comment]
@maicki Hi, thanks, it solves my issue. I don't know it should be `pod  'Texture/IGListKit'` in order to make it work correctly.  Is it on document yet ?

**Comment by 3a4oT** [comment]
Hey, I have the same issue but I using Carthage. Now sure how I can properly handle it?
I have tried 
```import AsyncDisplayKit.IGListAdapter_AsyncDisplayKit```` but it doesn't work for me.
