### ISSUE TITLE
NSAttributedString+ASText.h can't be import to use

### ISSUE THREAD

**Issue by LustySwimmer** [TextureGroup/Texture#1108]
I can't use NSAttributedString+ASText.h in any file in my project，#import <AsyncDisplayKit/NSAttributedString+ASText.h> always remind me that 'AsyncDisplayKit/NSAttributedString+ASText.h' file not found.
Is this category private to use just in Texture ?

**Comment by maicki** [comment]
@LustySwimmer Hey - yes that is a private header for now and not exposed. Thanks!

**Comment by liuaaaddxiaoer** [comment]
I also want to use it NSAttributedString+ASText.h  but  can't   I use 
YYText instead
