### ISSUE TITLE
ASTableView crash on version 2.7

### ISSUE THREAD

**Issue by joylogs** [TextureGroup/Texture#1114]
We are getting this NSInternalInconsistencyException crash on version 2.7 which wasnt happening earlier for previous versions. Below is the Stack trace.

**Fatal Exception: NSInternalInconsistencyException
attempt to delete row 33 from section 0 which only contains 33 rows before the update**

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x2289391b __exceptionPreprocess
1  libobjc.A.dylib                0x2202ee17 objc_exception_throw
2  CoreFoundation                 0x228937f1 +[NSException raise:format:]
3  Foundation                     0x23077529 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x26ffff75 -[UITableView _endCellAnimationsWithContext:]
5  AsyncDisplayKit                0x1b9e8d5 -[ASTableView rangeController:updateWithChangeSet:updates:] (ASTableView.mm:1645)
6  AsyncDisplayKit                0x1b82aab -[ASRangeController dataController:updateWithChangeSet:updates:] (ASRangeController.mm:521)
7  AsyncDisplayKit                0x1b1fda5 __40-[ASDataController updateWithChangeSet:]_block_invoke_2.202 (ASDataController.mm:610)
8  AsyncDisplayKit                0x1b6c1a7 __30-[ASMainSerialQueue runBlocks]_block_invoke (ASThread.h:235)
9  libdispatch.dylib              0x22401823 _dispatch_call_block_and_release
10 libdispatch.dylib              0x2240180f _dispatch_client_callout
11 libdispatch.dylib              0x2240fba9 _dispatch_main_queue_callback_4CF$VARIANT$mp
12 CoreFoundation                 0x22855b6d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0x22854067 __CFRunLoopRun
14 CoreFoundation                 0x227a3229 CFRunLoopRunSpecific
15 CoreFoundation                 0x227a3015 CFRunLoopRunInMode
16 GraphicsServices               0x23d93ac9 GSEventRunModal
17 UIKit                          0x26e77189 UIApplicationMain
18 Flipkart                       0xa5e69 main (main.m:16)
19 (Missing)                      0x2244b873 (Missing)

This crash isnt observed in iOS 11, but only for iOS 9, 10

**Comment by nguyenhuy** [comment]
Unfortunately there isn't enough information to debug this issue. Please feel free to reopen with a reliable way to reproduce it. Thank you.
