### ISSUE TITLE
cocoapods更新不到2.7版本，只能更新到2.6，2.6设置automaticallyManagesSubnodes为true崩溃

### ISSUE THREAD

**Issue by xuhuaping** [TextureGroup/Texture#1133]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack (we'll be updating the name to Texture soon)

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// Texture version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

**Comment by faimin** [comment]
try `pod update`

**Comment by ay8s** [comment]
You may also need to run pod repo update.
