### ISSUE TITLE
Create 2.7.1 tag + podspec

### ISSUE THREAD

**Issue by ejensen** [TextureGroup/Texture#1138]
There are a number of fixes in master that are not available in the latest official release (2.7.0). Notable the fixes made in PR #1025. 
The adding the changes currently in master to an official release tag would resolve blockage of development teams (see the discussions in the #general Slack channel).

**Comment by Kaspik** [comment]
@Adlai-Holler Please!

**Comment by diederikh** [comment]
+1

**Comment by Kaspik** [comment]
Okay, it didn't help really so...

@garrettmoon / @Adlai-Holler / @maicki / @nguyenhuy ?
Latest release has been done in May, it's December, we have XCode 10, iOS 12, but we need to use master of this huge but great project.

Please, guys. :)

**Comment by GeekTree0101** [comment]
+1

**Comment by ajanuar** [comment]
+1

**Comment by stephensilber** [comment]
You can use `releases/pXXX` as the branch in your Podfile if you are looking for a specific set of fixes but don't want to point directly at `master`
