### ISSUE TITLE
Build failed when using 'ASIGListSectionControllerMethods'

### ISSUE THREAD

**Issue by yesidi** [TextureGroup/Texture#1145]
Code:

    //ASDK Replacement
    override func sizeForItem(at index: Int) -> CGSize {
        return ASIGListSectionControllerMethods.sizeForItem(at: index)
    }
    
    override func cellForItem(at index: Int) -> UICollectionViewCell {
        return ASIGListSectionControllerMethods.cellForItem(at: index, sectionController: self)
    }

Build Error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ASIGListSectionControllerMethods", referenced from:
      objc-class-ref in LabelSectionController.o
      objc-class-ref in SearchSectionController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to fix it? Please tell me.

**Comment by hapiii** [comment]
thanks, solved my problem!
