### ISSUE TITLE
How can I access 'asyncdisplaykit_node' in UIView ?

### ISSUE THREAD

**Issue by aimm** [TextureGroup/Texture#1146]
I found that asyncdisplaykit_node is a private property of _ASDisplayView，is there any public method that I can access ?

**Comment by nguyenhuy** [comment]
Hi, you can use `ASLayerToDisplayNode(CALayer *layer)` and `ASViewToDisplayNode(UIView *view)` declared in `ASDisplayNodeExtras.h`.
