### ISSUE TITLE
Error Profiling an app "Thread-local storage is not supported for the current target"

### ISSUE THREAD

**Issue by kArTeL** [TextureGroup/Texture#1215]
Hi, i'm trying to profile my app and i'm getting an error when i build the app:
<img width="1122" alt="error" src="https://user-images.githubusercontent.com/3840467/48042565-ba572100-e147-11e8-8130-1d42a90e999d.png">

I create a simple project just adding **Texture 2.7 via Cocoapods.**
https://github.com/kArTeL/TextureProfileError

I'm using **cocoapods version 1.5.3** 

Some help is appreciated!!

**Comment by ay8s** [comment]
Try adding the following to your pod file config...

`configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'`

**Comment by kArTeL** [comment]
> Try adding the following to your pod file config...
> 
> `configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'`
@ay8s Thank you, this fix it.
