### ISSUE TITLE
Will Texture get new release soon?

### ISSUE THREAD

**Issue by rlam3** [TextureGroup/Texture#1271]
Will Texture get new release soon?

**Comment by GeekTree0101** [comment]
you can consider using p.xx version branch. For example `pod 'Texture', :git =>  'https://github.com/TextureGroup/Texture.git', :branch => 'p6.74'`

**Comment by appleguy** [comment]
Thanks for asking! It looks like our cadence paused here, although not intentionally. I'm asking some of the other project leads if we can release soon, but indeed feel free to use the "p" branches (which are Pinterest app release cut points).

**Comment by sgrgrsn** [comment]
Thanks for the 2.8 release! 👍 

I think this issue can be closed right away.
