### ISSUE TITLE
Change subnode height on scrollViewDidScroll

### ISSUE THREAD

**Issue by igorvoytovich** [TextureGroup/Texture#1304]
Hi all!
Have ASScrollNode with my content, and want some header (just ASDisplayNode with solid backgroundColor). Want this header change its height on scrollViewDidScroll (UIScrollViewDelegate method) (Behavior like it constrained to top -> safeAreaTop and bottom -> contentTop (scroll view content using autolayout). How I can solve it using Texture? Changing frame.height causing setNeedsLayout calling and scrollNode contentOffset becomes zero.

I hope you understand the question. Thank you.

**Comment by SergeyPetrachkov** [comment]
Hi Igor, if I understand you right you should just 

1) make your header view a separate class (if it's not that yet)
2) override the following method in your header subclass:

```swift
override func animateLayoutTransition(_ context: ASContextTransitioning) 
```
and implement resizing logic there (maybe changing style.preferredSize)
3) in your scrollViewDelegate trigger header.setNeedsLayout

it should work

**Comment by SergeyPetrachkov** [comment]
https://gist.github.com/SergeyPetrachkov/024f549d281b0c1b8c22a1d6de01f68b
