### ISSUE TITLE
tableNode.indexPathForRow(at: CGPoint) could not get right indexpath

### ISSUE THREAD

**Issue by CivelXu** [TextureGroup/Texture#1308]
I use 3d touck peek in ASTableNode;` let indexPath = tableNode.indexPathForRow(at: location)` could not get right indexpath, I need help !!

**Comment by made2k** [comment]
This could be dependent on what you've registered as your previewing delegate.

For instance, if you have an `ASViewController<ASDisplayNode>` and your tableNode is a child node of the controllers node, you'd need to get the point in the table with something like

```
let tableLocation = tableNode.convert(location, from: node)
```

The location is going to be based off the touch point in the view that was registered for previewing. If that wasn't your table, you need to convert that point from the view to the table node before grabbing the index path.

**Comment by ay8s** [comment]
@CivelXu We've not seen any issue with fetching the indexPath while using Texture, would you be up for trying @made2k's suggestion?
