### ISSUE TITLE
deleteItems and insertItems instead of moveItems calls on moveRowAtIndexPath

### ISSUE THREAD

**Issue by DmitriyBagrov92** [TextureGroup/Texture#1316]
Hello!
I'm using move function to perform smooth animation update of cells order (at ASTableNode):
```- (void)moveRowAtIndexPath:(NSIndexPath *)indexPath toIndexPath:(NSIndexPath *)newIndexPath;```
But when I'm calling it I get insertion and deletion animation and logs:
```
[Collection] performBatchUpdates <ASTableNode: 0x1096151f0> { deleteItems = { @0 : { 4 } }; insertItems = { @0 : { 0 } } }
```
It's critical for me, Texture version is 2.7
Please Help!

**Comment by DmitriyBagrov92** [comment]
I found in code that, it wasn't implemented:
https://github.com/TextureGroup/Texture/blob/e59eff8aa0ebc4c354645123173e81993a8264d8/Source/Private/_ASHierarchyChangeSet.mm#L423

**Comment by nguyenhuy** [comment]
Hi, yes we don't have a real move implementation as of now. This is not something activate maintainers plan to fix anytime soon, but we do welcome pull requests. Here is [the last PR](https://github.com/TextureGroup/Texture/pull/507) on this feature.

I'm going to close this issue. Please feel free to reopen it if you want to follow up. Thank you.
