### ISSUE TITLE
Pod fail to install in ASDKGram sample

### ISSUE THREAD

**Issue by iDevelopper** [TextureGroup/Texture#1320]
The pod
```
  pod 'Weaver', :git => 'git@github.com:TextureGroup/Weaver.git', :branch => 'master'
```
fail to install.

Pod install
>Analyzing dependencies
Fetching podspec for `Texture` from `../..`
Pre-downloading: `Weaver` from `git@github.com:TextureGroup/Weaver.git`, branch `master`

>[!] Error installing Weaver
[!] Failed to download 'Weaver'.

**Comment by hacky12** [comment]
change   
pod 'Weaver', :git => 'git@github.com:TextureGroup/Weaver.git', :branch => 'master'

to

pod 'Weaver', :git => 'https://github.com/TextureGroup/Weaver.git', :branch => 'master'
