### ISSUE TITLE
ASTextNode don't break line in ASInsetLayoutSpec

### ISSUE THREAD

**Issue by buithuyen** [TextureGroup/Texture#1329]
Hi you guys,

I have got some problem with `ASTextNode`. The line wasn't break when I embed `ASTextNode` into `ASInsetLayoutSpec`

<img width="922" alt="screen shot 2019-01-27 at 4 06 15 pm" src="https://user-images.githubusercontent.com/5087522/51798963-87f02800-224d-11e9-9e6c-c5c4ee98f66d.png">

<img width="644" alt="screen shot 2019-01-27 at 4 17 46 pm" src="https://user-images.githubusercontent.com/5087522/51799069-2335cd00-224f-11e9-9e6b-c1968924e495.png">

```
override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let addressStack = ASStackLayoutSpec.vertical()
        addressStack.style.flexGrow = 1
        addressStack.style.flexShrink = 1
        addressStack.children = [
            addressNode,
            SpaceNode(),
            directionNode,
        ]
        
        let imageStack = ASStackLayoutSpec.vertical()
        imageStack.children = [imageNode, SpaceNode()]
                
        let stack = ASStackLayoutSpec.horizontal()
        stack.style.flexGrow = 1
        stack.style.flexShrink = 1
        stack.spacing = 16
        stack.children = [
            ASInsetLayoutSpec(insets: UIEdgeInsets(top: 16), child: imageStack),
            ASInsetLayoutSpec(insets: UIEdgeInsets(vertical: 16), child: addressStack),
            locationImageNode
        ]
        
        let spec = ASInsetLayoutSpec(insets: UIEdgeInsets(left: 16), child: stack)
        return spec
    }
```
I just replace  `ASInsetLayoutSpec(insets: UIEdgeInsets(vertical: 16), child: addressStack)` by `addressStack` . This is fine but `addressStack` don't have inset.

![screen shot 2019-01-27 at 4 14 57 pm](https://user-images.githubusercontent.com/5087522/51799047-d3570600-224e-11e9-941e-2b39d652a852.png)
<img width="605" alt="screen shot 2019-01-27 at 4 15 44 pm" src="https://user-images.githubusercontent.com/5087522/51799049-d6ea8d00-224e-11e9-9c39-ac50b2284ef3.png">

Can you help me know what did I do wrong?

**Comment by AbhiRathi-iOS** [comment]
@buithuyen Were you able to add inset to addressStack then?
