### ISSUE TITLE
ASNodeController (post-NSLocking) is causing deadlock in 2.8

### ISSUE THREAD

**Issue by stephensilber** [TextureGroup/Texture#1342]
We use `ASNodeController` throughout our app, and after upgrading to `2.8`, I'm seeing a deadlock in one of our node controllers. It seems to have started after this pull request was merged in:
https://github.com/TextureGroup/Texture/pull/1179

It looks like @appleguy may have brought this up as a potential problem in the #1179 PR review.
https://github.com/TextureGroup/Texture/pull/1179/files/83696de05cc03e6ced2a76780b8a03f1442b0b92#diff-201f20cb04a043f825170266014a5b25R42

Here's my node controller:
```

class HoldingsNodeController: ASNodeController<ASCollectionNode> {
    var securitySelected: ((_ securityId: Int, _ holdingId: Int) -> Void)?
    
    lazy var flowLayout = UICollectionViewFlowLayout()

    
    private var holdingsSubscription: StateSubscription<HoldingsViewModelState>?
    private let holdingsViewModel: HoldingsViewModel
    private let collectionController = CollectionController()
    
    init(holdingsViewModel: HoldingsViewModel) {
        self.holdingsViewModel = holdingsViewModel
        super.init()
        holdingsViewModel.fetchHoldings()
    }
    
    override func didExitPreloadState() {
        super.didExitPreloadState()
        holdingsViewModel.unsubscribe(from: self)
    }
    
    override func didEnterPreloadState() {
        super.didEnterPreloadState()
        holdingsViewModel.subscribe(from: self)
    }
    
    override func createNode() -> ASCollectionNode {
        return ASCollectionNode(collectionViewLayout: flowLayout)
    }
    
    override func nodeDidLoad() {
        super.nodeDidLoad()
        node.backgroundColor = .white
        node.alwaysBounceVertical = true
        node.dataSource = collectionController
        node.delegate = collectionController
        node.view.delaysContentTouches = false
    }
    
    // MARK: StatefulView

    typealias State = HoldingsViewModelState
    
    var renderPolicy: RenderPolicy {
        return .possible
    }
    
    func render(state: HoldingsViewModelState) {
        reload()
    }
}
```

Things I have tried:
* Commenting out the `ASLockScopeSelf` in ASNodeController implementation file does fix the issue
* Removing a reference to `flowLayout` and instead just passing `UICollectionViewLayout()` in the collection initialization
* moving some of the node configuration out of `createNode` and into `nodeDidLoad`

**Comment by stephensilber** [comment]
It looks like this was addressed (at least temporarily) here: https://github.com/TextureGroup/Texture/commit/6428077e01cfbc56b4f482fb3149ce1c0e785e39

But maybe @Adlai-Holler can confirm before I close this?

**Comment by maicki** [comment]
@stephensilber Yes this should be addressed with https://github.com/TextureGroup/Texture/commit/6428077e01cfbc56b4f482fb3149ce1c0e785e39. Can you please try out master if this fixes your problem? Thanks!

**Comment by stephensilber** [comment]
@maicki Master seems to be working. Thanks!
