### ISSUE TITLE
snapchat esque swipe ui demo sample

### ISSUE THREAD

**Issue by markmark1** [TextureGroup/Texture#14]
is there a snapchat like swipe based ui to swipe through videos  available thanks

**Comment by markmark1** [comment]
is this asyncdisplaykit?

**Comment by Adlai-Holler** [comment]
Hey @markmark1 yes this is the framework formerly known as AsyncDisplayKit but unfortunately the core team can't field questions like this. Head over to the [Texture slack](http://texturegroup.org/slack.html) and ask in the #general channel, there's a ton of people helping one another.

**Comment by markmark1** [comment]
Tried slack didn't have much luck do you mind pointing me in the right direction Adlai Holler
		

		
	





On Mon, Apr 17, 2017 at 11:55 AM -0700, "Adlai Holler" <notifications@github.com> wrote:












Hey @markmark1 yes this is the framework formerly known as AsyncDisplayKit but unfortunately the core team can't field questions like this. Head over to the Texture slack and ask in the #general channel, there's a ton of people helping one another.

**Comment by Adlai-Holler** [comment]
@markmark1 You should check out ASPagerNode to create a horizontal-swiping list, and then ASVideoPlayerNode to show the videos.

**Comment by markmark1** [comment]
Thanks so much you rock Adlai 
		

		
	





On Mon, Apr 17, 2017 at 4:30 PM -0700, "Adlai Holler" <notifications@github.com> wrote:












@markmark1 You should check out ASPagerNode to create a horizontal-swiping list, and then ASVideoPlayerNode to show the videos.

**Comment by markmark1** [comment]
What about images and overlays are there texture modules for those too?
		

		
	





On Mon, Apr 17, 2017 at 4:30 PM -0700, "Adlai Holler" <notifications@github.com> wrote:












@markmark1 You should check out ASPagerNode to create a horizontal-swiping list, and then ASVideoPlayerNode to show the videos.

**Comment by markmark1** [comment]
What's a node
		

		
	





On Mon, Apr 17, 2017 at 4:30 PM -0700, "Adlai Holler" <notifications@github.com> wrote:












@markmark1 You should check out ASPagerNode to create a horizontal-swiping list, and then ASVideoPlayerNode to show the videos.

**Comment by Adlai-Holler** [comment]
http://texturegroup.org/docs/getting-started.html Godspeed on your project 🙂

**Comment by markmark1** [comment]
What about images and overlays 
		

		
	





On Mon, Apr 17, 2017 at 4:35 PM -0700, "mark M" <write2mark1@gmail.com> wrote:













	
		
		
	
		
		What about images and overlays are there texture modules for those too?
		

		
	





On Mon, Apr 17, 2017 at 4:30 PM -0700, "Adlai Holler" <notifications@github.com> wrote:












@markmark1 You should check out ASPagerNode to create a horizontal-swiping list, and then ASVideoPlayerNode to show the videos.
