### ISSUE TITLE
Insert two cells at the same time duplicate one of the cell

### ISSUE THREAD

**Issue by DrewDe** [TextureGroup/Texture#1403]
I’m having an issue with ASTableNode when inserting two cells at the same time. One of the cell is duplicated.

The following code : 
```
            self.messages.append("TEST 1")
            self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)

            self.messages.insert("TEST 2", at: 0)
            self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)
            
            self.messages.insert("TEST 3", at: 0)
            self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)
```

Produce the following result ( demo project : https://github.com/DrewDe/TextureDuplicate ):
![ASTableNode](https://i.ibb.co/x8RBLx6/IMG-3177.png)

Thanks for your help,

—Jérémie

**Comment by ay8s** [comment]
Your second 

```self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)```

Should be

```self.tableNode.insertRows(at: [IndexPath(row: 1, section: 0)], with: .top)```

**Comment by DrewDe** [comment]
Thanks @ay8s for your answer, sorry I've made a mistake in my demo project ( it's fixed ), this is the actual code to reproduce:

```
            self.messages.append("TEST 1")
            self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)

            self.messages.insert("TEST 2", at: 0)
            self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)
            
            self.messages.insert("TEST 3", at: 0)
            self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)
```

It produce : 
![ASTableNode](:https://imgur.com/267b2531-6a72-46bc-a439-1f37e79267c0)

**Comment by ay8s** [comment]
In which case you would want to do 
```
self.messages.insert("TEST 1", at: 0)
self.tableNode.insertRows(at: [IndexPath(row: 2, section: 0)], with: .top)

self.messages.insert("TEST 2", at: 0)
self.tableNode.insertRows(at: [IndexPath(row: 1, section: 0)], with: .top)

self.messages.insert("TEST 3", at: 0)
self.tableNode.insertRows(at: [IndexPath(row: 0, section: 0)], with: .top)
```
![Simulator Screen Shot - iPhone XS Max - 2019-03-12 at 15 34 18](https://user-images.githubusercontent.com/1058408/54240795-53be8700-44dc-11e9-888b-46b403a8cfc1.png)

**Comment by DrewDe** [comment]
Ok, thanks 👍
