### ISSUE TITLE
Thread should not hold lock NSAttributedString(htmlString:)

### ISSUE THREAD

**Issue by foxware00** [TextureGroup/Texture#1404]
Texture version 2.8

@nguyenhuy Referencing this issue with more details and specific crash report and details #1334 

In layoutSpecFits and didLoad I run a couple of functions on the string before placing it into ASTextNode. I'm using another library for parsing [Markdown](https://github.com/iwasrobbed/Down). This internally requires execution to be on the main thread as Down's implementation of `.toAttributredString()` invokes `NSAttributedString(htmlString:)`. So I've added a check to ensure we're on the `isMainThread` before executing. However in 2.8 this causes the following stack trace. I've got some work to do to change this markdown parser to not require `NSAttributedString(htmlString:)` but instead walk the tree and construct the NSAttributedString manually without needing to be on the UI thread. Regardless I wonder if you could shed some light on what might be the cause and if there is something I can do in 2.8 to prevent this crashing. Downgrading to 2.7 works fine.

If you require any more information or different stack trace please let me know. This is all on the `main` thread.

Linked the code i'm using to ensure we're on the correct thread. Given calling from `didLoad` also faced the same issues.

```
if Thread.isMainThread {
    if let value = originalString.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines).asMarkDownString() { <-- this is the culprit..
        self.attributedLink(originalString: value.string,
                attributes: attributes,
                isEdited: isEdited)
    }
}
```
This code doesn't crash, but obviously doesn't allow me to parse `asMarkDownString()` which I require
```
attributedLink(originalString: originalString.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines),
        attributes: attributes,
        isEdited: isEdited)

```
```
func asMarkDownString() -> NSAttributedString? {
    return try? Down(markdownString: self).toAttributedString()
}
```
This is the code directly from Down that's causing the issue
```
let html = try self.toHTML(options)
let defaultStylesheet = "* {font-family: Helvetica } code, pre { font-family: Menlo }"
return try NSAttributedString(htmlString: "<style>" + (stylesheet ?? defaultStylesheet) + "</style>" + html)
```
NSAttributedString extension which is using the `documentType: .DocumentType.html`
```
extension NSAttributedString {
    convenience init(htmlString: String) throws {
        guard let data = htmlString.data(using: String.Encoding.utf8) else {
            throw DownErrors.htmlDataConversionError
        }

        let options: [NSAttributedString.DocumentReadingOptionKey: Any] = [
            .documentType: NSAttributedString.DocumentType.html,
            .characterEncoding: NSNumber(value: String.Encoding.utf8.rawValue)
        ]
        try self.init(data: data, options: options, documentAttributes: nil)
    }
}
```

	0   CoreFoundation                      0x000000010b3da1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010a0da735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b3d9f42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001049d7940 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   AsyncDisplayKit                     0x000000010325fded _ZN4ASDN5Mutex13AssertNotHeldEv + 589
	5   AsyncDisplayKit                     0x00000001032b1ecb -[ASDisplayNode enumerateInterfaceStateDelegates:] + 75
	6   AsyncDisplayKit                     0x000000010329b64e -[ASDisplayNode _pendingNodeDidDisplay:] + 654
	7   AsyncDisplayKit                     0x000000010329f82c -[ASDisplayNode subnodeDisplayDidFinish:] + 60
	8   AsyncDisplayKit                     0x000000010329f731 -[ASDisplayNode displayDidFinish] + 513
	9   AsyncDisplayKit                     0x000000010329f288 -[ASDisplayNode didDisplayAsyncLayer:] + 56
	10  AsyncDisplayKit                     0x000000010325bff2 __64-[ASDisplayNode(AsyncDisplay) displayAsyncLayer:asynchronously:]_block_invoke_2 + 1378
	11  AsyncDisplayKit                     0x0000000103188f2a -[ASAsyncTransactionOperation callAndReleaseCompletionBlock:] + 506
	12  AsyncDisplayKit                     0x000000010318eebb -[_ASAsyncTransaction completeTransaction] + 923
	13  AsyncDisplayKit                     0x000000010318eaa7 __29-[_ASAsyncTransaction commit]_block_invoke + 39
	14  libdispatch.dylib                   0x000000010d0784e1 _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x000000010d07954b _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010d085380 _dispatch_main_queue_callback_4CF + 1290
	17  CoreFoundation                      0x000000010b33f3e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	18  CoreFoundation                      0x000000010b339a76 __CFRunLoopRun + 2342
	19  CoreFoundation                      0x000000010b338e11 CFRunLoopRunSpecific + 625
	20  UIFoundation                        0x0000000111c62b42 -[NSHTMLReader _loadUsingWebKit] + 1918
	21  UIFoundation                        0x0000000111c63f17 -[NSHTMLReader attributedString] + 22
	22  UIFoundation                        0x0000000111bef3f6 _NSReadAttributedStringFromURLOrData + 5452
	23  UIFoundation                        0x0000000111bede16 -[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 117
	24  Down                                0x000000010493e3fd $SSo18NSAttributedStringC4DownE04htmlB0ABSS_tKcfc + 893
	25  Down                                0x000000010493e021 $SSo18NSAttributedStringC4DownE04htmlB0ABSS_tKcfC + 65
	26  Down                                0x00000001049379db $S4Down0A26AttributedStringRenderablePAAE02tobC0_10stylesheetSo012NSAttributedC0CAA0A7OptionsV_SSSgtKF + 683
	27  AppKit                            0x0000000109061309 $SSS8AppKitE16asMarkDownStringSo012NSAttributedF0CSgyF + 169
	28  App                               0x0000000100f81f87 $S5App18ASTextNodeProtocolPAAE23stripMentionsAndLinkify14originalString10attributes10isMarkdown0L6EditedySS_SDySo012NSAttributedJ3KeyaypGS2btF + 631
	29  App                               0x0000000101514344 $S5App20FeedLabelledTextNodeC18layoutSpecThatFitsySo08ASLayoutG0CSo11ASSizeRangeaF + 1252
	30  App                               0x0000000101515a7f $S5App20FeedLabelledTextNodeC18layoutSpecThatFitsySo08ASLayoutG0CSo11ASSizeRangeaFTo + 95
	31  AsyncDisplayKit                     0x000000010326c7f7 -[ASDisplayNode(ASLayoutSpec) _locked_layoutElementThatFits:] + 679
	32  AsyncDisplayKit                     0x000000010328afc4 __27+[ASDisplayNode initialize]_block_invoke + 244
	33  AsyncDisplayKit                     0x000000010326b605 -[ASDisplayNode(ASLayoutSpec) calculateLayoutLayoutSpec:] + 821
	34  AsyncDisplayKit                     0x00000001032983fe -[ASDisplayNode calculateLayoutThatFits:] + 926
	35  AsyncDisplayKit                     0x0000000103297e60 -[ASDisplayNode calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] + 592
	36  AsyncDisplayKit                     0x000000010325dda9 -[ASDisplayNode(ASLayoutElement) layoutThatFits:parentSize:] + 2665
	37  AsyncDisplayKit                     0x00000001033661ca _ZL16crossChildLayoutRK22ASStackLayoutSpecChildRK22ASStackLayoutSpecStyledddd6CGSize + 442
	38  AsyncDisplayKit                     0x0000000103365fe9 ___ZL43layoutItemsAlongUnconstrainedStackDimensionRNSt3__16vectorI21ASStackLayoutSpecItemNS_9allocatorIS1_EEEERK22ASStackLayoutSpecStylebRK11ASSizeRange6CGSizeb_block_invoke + 553
	39  AsyncDisplayKit                     0x0000000103365ce5 _ZL21dispatchApplyIfNeededmbU13block_pointerFvmE + 181
	40  AsyncDisplayKit                     0x00000001033621c3 _ZL43layoutItemsAlongUnconstrainedStackDimensionRNSt3__16vectorI21ASStackLayoutSpecItemNS_9allocatorIS1_EEEERK22ASStackLayoutSpecStylebRK11ASSizeRange6CGSizeb + 371
	41  AsyncDisplayKit                     0x0000000103361365 _ZN25ASStackUnpositionedLayout7computeERKNSt3__16vectorI22ASStackLayoutSpecChildNS0_9allocatorIS2_EEEERK22ASStackLayoutSpecStyleRK11ASSizeRangeb + 757
	42  AsyncDisplayKit                     0x000000010335a722 -[ASStackLayoutSpec calculateLayoutThatFits:] + 562
	43  AsyncDisplayKit                     0x00000001033004a2 -[ASLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] + 466
	44  AsyncDisplayKit                     0x0000000103300245 -[ASLayoutSpec layoutThatFits:parentSize:] + 357
	45  AsyncDisplayKit                     0x00000001032ddf22 -[ASInsetLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] + 2082
	46  AsyncDisplayKit                     0x0000000103300245 -[ASLayoutSpec layoutThatFits:parentSize:] + 357
	47  AsyncDisplayKit                     0x00000001031d8228 -[ASBackgroundLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] + 216
	48  AsyncDisplayKit                     0x0000000103300245 -[ASLayoutSpec layoutThatFits:parentSize:] + 357
	49  AsyncDisplayKit                     0x00000001031d8228 -[ASBackgroundLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] + 216
	50  AsyncDisplayKit                     0x0000000103300245 -[ASLayoutSpec layoutThatFits:parentSize:] + 357
	51  AsyncDisplayKit                     0x00000001032ddf22 -[ASInsetLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] + 2082
	52  AsyncDisplayKit                     0x0000000103300245 -[ASLayoutSpec layoutThatFits:parentSize:] + 357
	53  AsyncDisplayKit                     0x00000001033000da -[ASLayoutSpec layoutThatFits:] + 138
	54  AsyncDisplayKit                     0x000000010326bd1b -[ASDisplayNode(ASLayoutSpec) calculateLayoutLayoutSpec:] + 2635
	55  AsyncDisplayKit                     0x00000001032983fe -[ASDisplayNode calculateLayoutThatFits:] + 926
	56  AsyncDisplayKit                     0x0000000103297e60 -[ASDisplayNode calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] + 592
	57  AsyncDisplayKit                     0x000000010325dda9 -[ASDisplayNode(ASLayoutElement) layoutThatFits:parentSize:] + 2665
	58  AsyncDisplayKit                     0x000000010325d33a -[ASDisplayNode(ASLayoutElement) layoutThatFits:] + 138
	59  AsyncDisplayKit                     0x0000000103241e92 -[ASDataController _layoutNode:withConstrainedSize:] + 1122
	60  AsyncDisplayKit                     0x000000010324dec6 -[ASDataController relayoutNodes:nodesSizeChanged:] + 2790
	61  AsyncDisplayKit                     0x00000001033865d6 -[ASTableView layoutSubviews] + 726
	62  UIKitCore                           0x000000011467f795 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1441
	63  QuartzCore                          0x0000000105e16b19 -[CALayer layoutSublayers] + 175
	64  AsyncDisplayKit                     0x000000010319f2ca -[_ASDisplayLayer layoutSublayers] + 426
	65  QuartzCore                          0x0000000105e1b9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	66  QuartzCore                          0x0000000105d947ca _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 342
	67  QuartzCore                          0x0000000105dcb97e _ZN2CA11Transaction6commitEv + 576
	68  QuartzCore                          0x0000000105dcc6fa _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
	69  CoreFoundation                      0x000000010b33ec27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	70  CoreFoundation                      0x000000010b3390be __CFRunLoopDoObservers + 430
	71  CoreFoundation                      0x000000010b339751 __CFRunLoopRun + 1537
	72  CoreFoundation                      0x000000010b338e11 CFRunLoopRunSpecific + 625
	73  GraphicsServices                    0x00000001118b91dd GSEventRunModal + 62
	74  UIKitCore                           0x000000011419581d UIApplicationMain + 140
	75  App                               0x0000000101bb9f41 main + 225
	76  libdyld.dylib                       0x000000010d0e9575 start + 1
```

**Comment by nguyenhuy** [comment]
Sorry for this late response. I've just released [2.8.1](https://github.com/TextureGroup/Texture/releases/tag/2.8.1) that disables these asserts. Please upgrade to 2.8.1. Cheers!
