### ISSUE TITLE
Crash with release/p7.11

### ISSUE THREAD

**Issue by businessengine** [TextureGroup/Texture#1423]
We use release/p7.11 and get random crashes (sometime) with the following error `2019-03-25 15:20:08.386809+1100 BusinessEngine[687:62711] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Node should always be marked invisible before deallocating. Node: <ASTextNode: 0x118631800; "Name: Foodizi">'`

This happened with `release/p7.4` and `release/p7.11` while it was not happening with the 2.7 (public cocoapod) branch. Any helps please? We can go back with any release which is not making the app crashed.

**Comment by garrettmoon** [comment]
@businessengine this is an assertion, not a crash. Since this can be caused by client code it's difficult for us to debug. Can you upload a sample project that reproduces this?

**Comment by ernestmama** [comment]
Latest release is p7.41. Please feel free to reopen if applicable.
