### ISSUE TITLE
 Reload tableNode‘s, Whether you insert it or move it, it will animate, How can I eliminate this animation for a better user experience?

### ISSUE THREAD

**Issue by SummerHF** [TextureGroup/Texture#1472]
`animated` **false**,  doesn't work.
```
self.tableNode.performBatch(animated: false, updates: {
                self.tableNode.reloadData()
            }, completion: { (finished) in
               self.removeLoadingView()
 })
```
* ScreenShot
![Cell Animate](https://ws2.sinaimg.cn/large/006tNc79ly1g2jfixou6vg309u0l2azh.gif)

* Can someone give some advice, even the demo app `ASDKgram` also have this situation:
![](https://ws1.sinaimg.cn/large/006tNc79ly1g2jfyro7rcg309u0l2e81.gif).

**I think this is a serious problem!!!!***   @nguyenhuy

**Comment by skg54** [comment]
FYI for anyone who has struggled with this.

A good way to achieve full control over animation is using the following methods on your Node Containers:
insertRows(at:with:)
reloadRows(at:with:)
deleteRows(at:with:)

à la


    tableNode.performBatch(animated: false) {
        tableNode.deleteRows(at: indexPaths, with: .none)
    }
