### ISSUE TITLE
Support for Dark Mode in iSO13

### ISSUE THREAD

**Issue by varyP** [TextureGroup/Texture#1540]
On iOS13, all UI Elements (eg: TabBar, TableView container etc), turn Black in Dark Mode automatically.

While Texture elements remain the same color, having Texture read the setting & changing the default color from White to Black would be awesome, else UI looks weird & out of place with a mix of White & Black throughout.

Using Texture (2.8.1)
XCode11-Beta
iOS13

**Comment by rahul-malik** [comment]
What is the specific task here? In ios13 the color changes already take effect. Are you asking for this to happen on iOS 12 and earlier?
