### ISSUE TITLE
When set NSLineBreakByTruncatingTail the truncationAttributedText will  be invalid

### ISSUE THREAD

**Issue by yunyyyun** [TextureGroup/Texture#1566]
When i set my textNode by this code:
```
_textNode.truncationMode = NSLineBreakByTruncatingTail;
_textNode.truncationAttributedText = truncationAttributedText;
```
the attribute truncationAttributedText will not work，Is there any solution(not use ASTextNode2)？

I have to set  NSLineBreakByTruncatingTail, because the _textNode.attributedText is with lineSpace(4), and with maximumNumberOfLines

**Comment by WIZOooo** [comment]
I am running into this problem too. How did you solve it?

**Comment by WIZOooo** [comment]
> I am running into this problem too. How did you solve it?

I got this problem fixed. Just replace ASTextNode with ASTextNode2. You have to set "additionalTruncationMessage" property instead of "truncationAttributedText" if truncationAttributedText Tapping is required.

**Comment by yunyyyun** [comment]
@WIZOooo  you can try to use ASTextNode2
