### ISSUE TITLE
Layout Spec Visualization

### ISSUE THREAD

**Issue by garrettmoon** [TextureGroup/Texture#157]
_From @hannahmbanana on November 14, 2016 4:27_

Initial half-baked idea was committed in #2554 and removed in #2991 to manage code complexity with the layout refactor. 

Huy has volunteered to drive the feature sometime down the road. Thanks Huy!

_Copied from original issue: facebookarchive/AsyncDisplayKit#2604_

**Comment by nguyenhuy** [comment]
Closing this in favor of Weaver.
