### ISSUE TITLE
What is the best way to display a set of tags but limit to only one line using Texture?

### ISSUE THREAD

**Issue by dickyj** [TextureGroup/Texture#16]
Hi,
I am trying to implement something like the TagListView (https://github.com/ElaWorkshop/TagListView). 
I am thinking of using ASCellNode and adding ASButtonNodes. But how do I limit the tags to only one line? Do I keep looping on each addition of the tag button until I find that the size has extended to the second line? And do I do it in the layoutSpecThatFits() method? Will there be a performance penalty? 

Thanks,
Dicky

**Comment by Adlai-Holler** [comment]
Hey @dickyj the core team can't field questions like this unfortunately. There's a ton of smart people helping one another apply Texture in the `#general` channel of the [Texture slack team](http://texturegroup.org/slack.html).

**Comment by shubham14896** [comment]
Hi @dickyj are you able to achieve the same?
