### ISSUE TITLE
run ASDKgram Error 

### ISSUE THREAD

**Issue by DevaLee** [TextureGroup/Texture#1624]
when I download the demo and go to the ASDKgram ,then set up pod install , it throw a fail,

BeL:ASDKgram ritamashin$ pod install
Analyzing dependencies
Fetching podspec for `Texture` from `../..`
Pre-downloading: `Weaver` from `git@github.com:TextureGroup/Weaver.git`, branch `master`

[!] Error installing Weaver
[!] Failed to download 'Weaver': [!] /usr/bin/git clone git@github.com:TextureGroup/Weaver.git /var/folders/n8/mh13psh924l4vc68ln545gxm0000gn/T/d20190818-43839-lgk8s6 --template= --single-branch --depth 1 --branch master

Cloning into '/var/folders/n8/mh13psh924l4vc68ln545gxm0000gn/T/d20190818-43839-lgk8s6'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

my location is ShangHai

**Comment by nguyenhuy** [comment]
That error usually means you don’t have SSH keys properly set up on your machine. You can either fix that or switch to a HTTP URL for Weaver (like [this](https://github.com/TextureGroup/Texture/pull/1623/files#diff-2b20fb764901e7e269c7478c8c540fe6L8)).
