### ISSUE TITLE
ASTextNode does not render Japanese font correctly. (It misuse serif fonts)

### ISSUE THREAD

**Issue by muukii** [TextureGroup/Texture#1655]
On iOS13, ASTextNode does not render the Japanese font correctly,
Especially, We can see this problem with specified font and linebreak mode.

```swift
    let node = ASTextNode()
    
    let paragraph = NSMutableParagraphStyle()
    
    paragraph.lineBreakMode = .byCharWrapping
        
    node.attributedText = NSAttributedString(
      string: "こんにちは",
      attributes: [
        NSAttributedString.Key.font : UIFont.boldSystemFont(ofSize: 18),
        NSAttributedString.Key.foregroundColor : UIColor.init(white: 0.8, alpha: 1),
        NSAttributedString.Key.paragraphStyle : paragraph,
      ]
    )
```

![image](https://user-images.githubusercontent.com/1888355/64089662-18fa2500-cd82-11e9-8a08-a1953947bac9.png)

The rendered font is wrong.
Followings is correct.

![image](https://user-images.githubusercontent.com/1888355/64089763-b05f7800-cd82-11e9-8e3c-888e3b080570.png)

I think to set lineBreakMode causes this problem.
If I drop setting for lineBreakMode, ASTextNode will render correct font.

Additionally, ASTextNode2 does not have this problem. It works fine.

What's the problem?
Should I use ASTextNode2?

I attach reproduce project file.
[iOS13-Text.zip](https://github.com/TextureGroup/Texture/files/3564430/iOS13-Text.zip)

**Comment by jeffersonsetiawan** [comment]
I got this problem too. If I remove `NSAttributedString.Key.paragraphStyle`, it works as expected. 

I am curious how to solve this too.

**Comment by jeffersonsetiawan** [comment]
When I tried to use a custom font, it shows the correct custom font.

**Comment by jeffersonsetiawan** [comment]
I think https://github.com/TextureGroup/Texture/pull/1579 fixes this issue

**Comment by muukii** [comment]
wow, I'll try to use on master branch

**Comment by muukii** [comment]
It seems to be fixed.
