### ISSUE TITLE
Wrong font when using NSParagraphStyle on ASTextNode in iOS 13

### ISSUE THREAD

**Issue by sgrgrsn** [TextureGroup/Texture#1659]
I have a problem with my ASTextNode when building with the latest beta of Xcode 11 (beta 6) on the latest beta of iOS 13.1 (beta 2), and the one bundled with the Xcode 11 simulator.

I set up my attributed string like this:
```swift
let paragraphStyle = NSMutableParagraphStyle()
paragraphStyle.alignment = .center

textNode.attributedText = NSAttributedString(
    string: "Hello world!\nHow are you doing?",
    attributes: [
        NSAttributedString.Key.font: UIFont.systemFont(ofSize: 32, weight: .bold),
        NSAttributedString.Key.paragraphStyle: paragraphStyle,
    ]
)
```

It shows up as a serif font, and not the San Francisco font. If I choose to remove the paragraphStyle attributes from the string it shows up correctly as the San Francisco font, but then I'm not able to set alignment, line heights etc.

**With the paragraphStyle attributes:**
![Simulator 2019-09-06 at 14 26 21](https://user-images.githubusercontent.com/6108577/64427795-52989c00-d0b2-11e9-9d38-35e1a31ceb8e.png)

**Without the paragraphStyle attributes:**
![Simulator 2019-09-06 at 14 27 07](https://user-images.githubusercontent.com/6108577/64427852-765be200-d0b2-11e9-9316-2fed989de121.png)

I've tried on both my device and on the simulator and it gives the same result. There's no problems when building to an iOS 12 device/simulator.

Hope you can help me out. 

Thanks in advance.

## Info
**Texture version:** 2.8.1 (installed with CocoaPods v1.7.3)
**Xcode version:** 11.0 beta 6
**iOS version (simulator):** 13.0 (bundled with Xcode 11 beta 6)
**iOS version (device):** 13.1 beta 2
**Sample project:** 
[FontXcode11-Sample.zip](https://github.com/TextureGroup/Texture/files/3583900/FontXcode11-Sample.zip)

**Comment by jeffersonsetiawan** [comment]
I think https://github.com/TextureGroup/Texture/pull/1579 fixes this issue

**Comment by sgrgrsn** [comment]
It seems like it's the same problem - thanks 👍

**Comment by nikmun** [comment]
I am facing the same issue. When will you guys release the new version with the fix of this issue?
