### ISSUE TITLE
didDisplayNodeContentWithRenderingContext doesn't get called anymore on 2.8.1 vs 2.8

### ISSUE THREAD

**Issue by christianselig** [TextureGroup/Texture#1680]
Texture version: 2.8.1

I updated from Texture 2.8 to 2.8.1 and `didDisplayNodeContentWithRenderingContext` isn't getting called anymore. I use that block in the `init` of a layerBacked `ASTextNode` to get some custom drawing elements (highlighted elements basically).

I didn't have much time to investigate (iOS 13 time crunch) so I ended up just downgrading back to 2.8 where it works as expected, apologies for not much more information on the issue.

Searching in the Slack for it I see one person had encountered it too:

> Does anyone know why didDisplayNodeContentWithRenderingContext block isn't called on ios 13? It gets called on ios 12 (edited) 

(I don't believe it's an iOS 13 issue though, it works as expected on iOS 13 if you're using the 2.8 release.)

*(Also thanks for all the awesome work the Texture team/contributors have been doing, 2.8.1 packed a ton of awesomeness especially around Dark Mode things, my hats are off to you and I greatly appreciate it!)*

**Comment by choiks14** [comment]
same here

**Comment by christianselig** [comment]
Here's some super simple sample code showing it not working from a new project.

Code from Texture 2.8 where `didDisplayNodeContentWithRenderingContext` **does** get called:

```swift
class RootViewController: ASViewController<ASDisplayNode> {
    let rootNode = ASDisplayNode()
    let bodyNode = ASTextNode()

    init() {
        super.init(node: rootNode)

        bodyNode.attributedText = NSAttributedString(string: "Hello, world!", attributes: [.font: UIFont.systemFont(ofSize: 21.0, weight: .semibold), .foregroundColor: UIColor.black])
        rootNode.addSubnode(bodyNode)

        bodyNode.didDisplayNodeContentWithRenderingContext = { (context, drawParameters) in
            print("Is this ever called?") // Texture 3.0 never calls this. Texture 2.8 does.
        }

        rootNode.layoutSpecBlock = { (node, constrainedSize) in
            return ASCenterLayoutSpec(centeringOptions: .XY, sizingOptions: .minimumXY, child: self.bodyNode)
        }
    }

    required init?(coder aDecoder: NSCoder) { fatalError("\(#file) does not implement coder.") }
}
```

However if you change Cocoapods to point to the most recent commit of Texture (3.0) (and change the code sample to subclass `ASDKViewController` and change `init()` to `override init()`), you'll see `didDisplayNodeContentWithRenderingContext` will no longer get called.

This changes if you change from `ASTextNode` to `ASTextNode2` (`didDisplayNodeContentWithRenderingContext` **will** get called) however `ASTextNode2` is still missing a lot of helpful methods from `ASTextNode` like `rectsForTextRange` which prevent me from migrating over to it fully (in fact in my real project I use `didDisplayNodeContentWithRenderingContext` and `rectsForTextRange` so it's even more important, haha).

**Comment by christianselig** [comment]
Ready for some Rube Goldberg magic? Issue seems to be that at some point between 2.8 and 3.0:

-  `ASTextNode` (not `ASTextNode2`) added the `displayWithParameters:isCancelled:` method (you can see here)
- Which causes `flags.implementsImageDisplay` to be `YES`.
- This in turn causes `shouldCreateGraphicsContext` [in ASDisplayNode+AsyncDisplay](https://github.com/TextureGroup/Texture/blob/master/Source/Private/ASDisplayNode+AsyncDisplay.mm#L167) to be set to `NO`. 
- Which in turns causes the graphics context to never be created, so it's `nil`.
- Slightly further down [in the method that implements the block callback](https://github.com/TextureGroup/Texture/blob/master/Source/Private/ASDisplayNode+AsyncDisplay.mm#L313) it's required that the graphics context be non-nil in order to call the callback. Since it's nil it just skips right past it and the block never gets called.

Note that `ASTextNode2` on the other hand does not implement `displayWithParameters:isCancelled:`, so `flags.implementsImageDisplay` is `NO` which causes everything to be set up properly.

I'm admittedly not sure what the obvious fix is here or why `ASTextNode` implements that method while `ASTextNode2` does not.

**Comment by garrettmoon** [comment]
@christianselig thank you for the thorough investigation!
