### ISSUE TITLE
Takes time execution in pre-main, should be lazily

### ISSUE THREAD

**Issue by ihsanhusnul** [TextureGroup/Texture#1697]
As mention in [WWDC](https://github.com/Blackjacx/WWDC#optimizing-app-launch) to avoiding some concern about using +[Class load]. may this block function be in the initialize?

the line to be a concern
https://github.com/TextureGroup/Texture/blob/2.8.1/Source/ASDisplayNode.mm#L253

this measured process in the pre-main app.

Total pre-main time: 1.9 seconds (100.0%)
         dylib loading time: 1.4 seconds (70.3%)
        rebase/binding time: 141.38 milliseconds (7.0%)
            ObjC setup time:  89.70 milliseconds (4.4%)
           initializer time: 362.51 milliseconds (18.1%)
           slowest intializers :
             libSystem.B.dylib :   4.85 milliseconds (0.2%)
               **AsyncDisplayKit : 200.48 milliseconds (10.0%)**
                     Parchment : 225.83 milliseconds (11.2%)

**Comment by ernestmama** [comment]
This is updated in master: https://github.com/TextureGroup/Texture/blob/master/Source/ASDisplayNode.mm#L258

PR: https://github.com/TextureGroup/Texture/pull/1425/files.
