### ISSUE TITLE
didDisplayNodeContentWithRenderingContext not called on iOS 13

### ISSUE THREAD

**Issue by royj** [TextureGroup/Texture#1729]
Texture version: 2.8.1 (Happens on all later master versions too)

Calling didDisplayNodeContentWithRenderingContext in an ASTextNode no longer calls the block that goes with it (https://i.imgur.com/Ya2hiqv.png). On the image, line 54 is never being executed.

Worked fine on iOS 12. Can anyone point me in the right direction?

**Comment by christianselig** [comment]
I'm seeing the same issue.

**Comment by bolsinga** [comment]
Sounds like #1680

**Comment by jparise** [comment]
Closing this as a duplicate of #1680.
