### ISSUE TITLE
IGListKit 4 update

### ISSUE THREAD

**Issue by ermik** [TextureGroup/Texture#1747]
There are new breaking changes, so what is the path to adopting the latest release of `IGListKit`?
https://github.com/TextureGroup/Texture/blob/d688ce3d2091fadfa85f89c9f915e442eb1f0de0/Texture.podspec#L46-L49

**Comment by ay8s** [comment]
@ermik Curious what breaking changes you've seen? We don't use the IGListKit implementation within Texture but I did try bumping up IGListKit to 4.0 and running ASDKGram and ran into no issues.

**Comment by ermik** [comment]
Sorry, holidays have been busy this year. I was referring to the announced breakage (some renaming), not  anything specific as to impact on ASDK interop. Thank you for bumping up the pod and I'm glad it was this easy.
