### ISSUE TITLE
AsyncDelegate for ASTableNode/ASCollectionNode missing forwarding iOS 13 new api 

### ISSUE THREAD

**Issue by IvanChan** [TextureGroup/Texture#1771]
Some new api in iOS 13 is NOT support for ASTableNode & ASCollectionNode, ASProxyDelegate is NOT forward those

```
func tableView(_ tableView: UITableView, contextMenuConfigurationForRowAt indexPath: IndexPath, point: CGPoint) -> UIContextMenuConfiguration?

    func tableView(_ tableView: UITableView, willPerformPreviewActionForMenuWith configuration: UIContextMenuConfiguration, animator: UIContextMenuInteractionCommitAnimating) 
```

Btw, Texture have NOT release a version to fully support iOS 13 for quit a long time, even just for dark mode

**Comment by uuttff8** [comment]
+1

**Comment by IvanChan** [comment]
@uuttff8 workaround is  hook

But I wonder why NOT use `UITableViewDelegate` instead of `ASCommonTableViewDelegate`, considering **Texture** is NOT update as frequently as before

**Comment by jparise** [comment]
We'd be happy to review a patch that adds these new APIs.

**Comment by uuttff8** [comment]
@jparise review pls https://github.com/TextureGroup/Texture/pull/1795
