### ISSUE TITLE
ASVideoNode memory leak issue

### ISSUE THREAD

**Issue by sagesse-cn** [TextureGroup/Texture#1774]
I have a ASButtonNnode in ASCellNode. when click this button it will call `play()`, in the `play()` will dymanic create a  ASVideoNode.
It works fine, but when call `stop()`, the ASVideNode doesn't release properly.

```swift
func play() {
    let newVideo = ASVideoNode()
    
    newVideo.backgroundColor = .clear
    newVideo.muted = true
    newVideo.isLayerBacked = true
    newVideo.shouldAutoplay = true
    newVideo.shouldAutorepeat = false
    newVideo.shouldAggressivelyRecoverFromStall = false
    
    insertSubnode(newVideo, belowSubnode: footer)
    setNeedsLayout()
    
    video = newVideo
}

func stop() {
    video.map {
        $0.assetURL = nil
        $0.resetToPlaceholder()
        $0.removeFromSupernode()
    }
    video = nil
}

var video: ASVideoNode?
```

# Information
Texture version: master
Xcode Version 11.3.1
iOS 13.3.1
iPhone 8

**Comment by sagesse-cn** [comment]
<img width="518" alt="WX20200213-183033@2x" src="https://user-images.githubusercontent.com/6903353/74425926-6e894080-4e8f-11ea-8f99-ecac3b57499a.png">

**Comment by SergeyPetrachkov** [comment]
Hi! Could you attach a sample project that reproduces this problem?

**Comment by sagesse-cn** [comment]
> Hi! Could you attach a sample project that reproduces this problem?

I'm sorry i fix the problem, because I removed ASVideoNode from supernode in `stop()`.
but I didn't call `setNeedsLayout()`, in `ASLayoutSpec` maybe cached the references of video node
