### ISSUE TITLE
Package Texture to enable a version that does not link to CoreLocation 

### ISSUE THREAD

**Issue by babbage** [TextureGroup/Texture#1783]
Texture links to CoreLocation due to the inclusion of mapping support in ASMapNode, and perhaps for other reasons?

Recently, Apple has started notifying developers the following on submission to AppStoreConnect they they will have to provide a _NSLocationWhenInUseUsageDescription_ and _NSLocationAlwaysUsageDescription_ when Texture is used in the project, even if the app does not use the APIs that link to CoreLocation and so will never trigger the location request to a user. (The full message from AppStoreConnect is below.)

This is undesirable, not least because in the future the limitations on linking to CoreLocation might become more onerous, e.g., if the app was required to demonstrate for App Review a reason why it would be logical for the app's functionality to ever obtain location information.

I propose that Texture consider packaging itself in such a way that components that link to CoreLocation are a separate framework that can be included or not, depending on the needs of the specific project. It would also be worthwhile alongside this looking at how other parts of the project may be able to be separated into separate components—if there is evidence this would lead to smaller binary sizes for projects that use Texture?—as I know I only use a tiny fraction of Texture's features.

Thanks for all your work on this project!

AppStoreConnect email content:
> We identified one or more issues with a recent delivery for your app, _AppName_ _VersionNumber_ (_BuildNumber_). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> **ITMS-90683: Missing Purpose String in Info.plist** - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> **ITMS-90683: Missing Purpose String in Info.plist** - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.

**Comment by nguyenhuy** [comment]
Thank you for your thoughtful report. I do agree with everts you said above. I personally believe the framework needs to be cleaned up and broken down into smaller components that can be put together depending on each project/client needs like Lego pieces, with the foundation to be a lean and “small” “TextureCore” piece.

Having said that, right now we do provide a way to not include map-related code and thus avoid linking CoreLocation. If you use CocoaPods, you can simply stop using the [“MapKit” subspec](https://github.com/TextureGroup/Texture/blob/70f61e9d01eff930f3f8e2bf4146a1841821c79a/Texture.podspec#L91). Would that work for your use case?

**Comment by babbage** [comment]
Oh. That is great. That option had completely escaped my attention, and yep, appears to do exactly what I'm looking for. :)

Scanned back through the install guide, looks like maybe I could make a minor pull request to the docs that adds some guidance on installing using a subspec instead of needing to import all of Texture... 

Thanks for the rapid support.

**Comment by nguyenhuy** [comment]
Glad I could help. Questions, feedback and contributions are all welcome!
