### ISSUE TITLE
-[IGListAdapter setASDKCollectionNode:]: unrecognized selector sent to instance 0x281cfc0d0

### ISSUE THREAD

**Issue by philmartin83** [TextureGroup/Texture#1800]
Hey

I'm trying to use IGList kit with texture and when I set the collection node like this

`thisAdapter.setASDKCollectionNode(collectionView)`

when I run the project the code crashes at the line above and with this 

`-[IGListAdapter setASDKCollectionNode:]: unrecognized selector sent to instance 0x281cfc0d0`

My podfile looks like this and I'm just running 

```Pods for TestProject
	pod "Texture"
	pod 'IGListKit', '~> 4.0.0'

then running pod install

**Comment by ccomsi** [comment]
Try adding `pod 'Texture / IGListKit'`

**Comment by philmartin83** [comment]
granted this works but it reverts my version of texture to almost 3 years ago. So surely I'd be missing out on all the improvements made on texture.

**Comment by philmartin83** [comment]
Awesome thanks this fixed this.
