### ISSUE TITLE
Ship Decision on ASExperimentalDispatchApply

### ISSUE THREAD

**Issue by bolsinga** [TextureGroup/Texture#1850]
ASExperimentalDispatchApply is in the code. Should it be on or off?

Landed with #1345

**Comment by bolsinga** [comment]
@Adlai-Holler Do you know the status of this for other clients? Thanks.

**Comment by Adlai-Holler** [comment]
Shipped in google. cc @wiseoldduck

**Comment by bolsinga** [comment]
Thanks @Adlai-Holler
