### ISSUE TITLE
Ship Decision on ASExperimentalDoNotCacheAccessibilityElements

### ISSUE THREAD

**Issue by bolsinga** [TextureGroup/Texture#1853]
ASExperimentalDoNotCacheAccessibilityElements is in the code. Should it be on or off?

Landed with #1812

**Comment by rcancro** [comment]
For context:

I compared accessibility behavior between UIKit and Texture with a label that could dynamically become hidden (i.e., when a  button was tapped). UIKit would skip the hidden button when navigating, but Texture would not. If I cleared out the cached `_accessibilityElements` and forced Texture to recompute them, then it behaved like UIKit.

The goal of the experiment is to see how much it affects performance if we do not cache the elements. Ideally we would turn off caching so a user wouldn't have to know to invalidate the elements when UI components change their hidden state.

**Comment by rcancro** [comment]
Shipped!
