### ISSUE TITLE
Xcode 12 build error when imported AuthenticationServices

### ISSUE THREAD

**Issue by hovox** [TextureGroup/Texture#1871]
When building with Xcode 12 beta1 we are getting this error `Redefinition of 'ASViewController' as different kind of symbol`
Seems cause is this in `ASFoundation.h`:
```
#if __has_include(<UIKit/UIViewController.h>)
typedef UIViewController ASViewController;
#endif
```
I suppose we need to rename `ASViewController` to something else ? E.g. `AS` => `TK`  as a texture kit ?

**Comment by ay8s** [comment]
Wonder if you have any preference on this one @garrettmoon? Wonder if it might be a good thing to slot into 3.0.

**Comment by hovox** [comment]
I have renamed `ASViewController` into `ASDKViewController` and `AS_EXTERN` into `ASDK_EXTERN` and seems that is enough. 


Not related to this issue but related to Xcode 12, there are some new warnings: 

```
'_Atomic' is a C11 extension
```

**Comment by garrettmoon** [comment]
Of course this would happen after we put out an RC.

**Comment by garrettmoon** [comment]
@hovox can you confirm that this is fixed on master? I want to get it into the 3.0 release.

**Comment by ay8s** [comment]
Working for us @garrettmoon 👍

**Comment by garrettmoon** [comment]
Gonna close this out, please lemme know if I should reopen!

**Comment by mycroftcanner** [comment]
https://github.com/TextureGroup/Texture/issues/2013
