### ISSUE TITLE
Texture won't compile with Xcode 12 beta 4

### ISSUE THREAD

**Issue by mycroftcanner** [TextureGroup/Texture#1894]
Texture won't compile with Xcode 12 beta 4 because of an issue in [PINCache](https://github.com/pinterest/PINCache/issues/275) and PINRemoteIMage

**Comment by k1ngcyk** [comment]
same issue here

**Comment by rahulvyas** [comment]
Same with me

**Comment by noremac** [comment]
There's an issue in the PINRemoteImage repo, and a PR too. https://github.com/pinterest/PINRemoteImage/issues/559

**Comment by zboralski** [comment]
### Temporary Workaround 
```
ENV['COCOAPODS_DISABLE_STATS'] = "true"
use_frameworks!

target 'XX' do
    platform :ios, '13.6'
    pod 'Texture', :git => 'https://github.com/TextureGroup/Texture', :branch => 'master'
    pod 'PINRemoteImage', :git => 'https://github.com/zacwest/PINRemoteImage', :branch => 'fix-xcode-12.0b4'
    pod 'PINCache', :git => 'https://github.com/pinterest/PINCache', :branch => 'master'
end
```

**Comment by jabbarwockeez** [comment]
> ### Temporary Workaround
> ```
> ENV['COCOAPODS_DISABLE_STATS'] = "true"
> use_frameworks!
> 
> target 'XX' do
>     platform :ios, '13.6'
>     pod 'Texture', :git => 'https://github.com/TextureGroup/Texture', :branch => 'master'
>     pod 'PINRemoteImage', :git => 'https://github.com/zacwest/PINRemoteImage', :branch => 'fix-xcode-12.0b4'
>     pod 'PINCache', :git => 'https://github.com/pinterest/PINCache', :branch => 'master'
> end
> ```

I was failed when i tried your solution.

```[!] CocoaPods could not find compatible versions for pod "PINCache":
  In Podfile:
    PINCache (from `https://github.com/pinterest/PINCache`, branch `master`)
    PINRemoteImage (from `https://github.com/zacwest/PINRemoteImage`, branch `fix-xcode-12.0b4`) was resolved to 3.0.0, which depends on
    PINRemoteImage/PINCache (= 3.0.0) was resolved to 3.0.0, which depends on
        PINCache (= 3.0.1-beta.8)
```

**Comment by zboralski** [comment]
@jabbarwockeez everything is out of sync again. 

Use this until PINRemoteImage is released:

```
  pod 'Texture', :git => 'https://github.com/TextureGroup/Texture', :branch => 'master'
  pod 'PINCache', :git => 'https://github.com/pinterest/PINCache', :branch => 'master'
  pod 'PINRemoteImage', :git => 'https://github.com/garrettmoon/PINRemoteImage', :branch => 'updatePINCacheInPodspec'
```

**Comment by zboralski** [comment]
@jabbarwockeez 

PINCache has a new release and it depends on PINRemoteImage that doesn't include the fix.

In the meantime we can pull the right commit:

```
  pod 'Texture', :git => 'https://github.com/TextureGroup/Texture', :branch => 'master'
  pod 'PINCache', :git => 'https://github.com/pinterest/PINCache', :commit => '83ed1a03'
  pod 'PINRemoteImage', :git => 'https://github.com/zacwest/PINRemoteImage', :branch => 'fix-xcode-12.0b4'
```

**Comment by AssyriaGameStudio** [comment]
Experiencing the same issue as highlighted by @jabbarwockeez.

**Comment by faizpathan** [comment]
> @zboralski
> 
> > ### Temporary Workaround
> > ```
> > ENV['COCOAPODS_DISABLE_STATS'] = "true"
> > use_frameworks!
> > 
> > target 'XX' do
> >     platform :ios, '13.6'
> >     pod 'Texture', :git => 'https://github.com/TextureGroup/Texture', :branch => 'master'
> >     pod 'PINRemoteImage', :git => 'https://github.com/zacwest/PINRemoteImage', :branch => 'fix-xcode-12.0b4'
> >     pod 'PINCache', :git => 'https://github.com/pinterest/PINCache', :branch => 'master'
> > end
> > ```
> 
> I was failed when i tried your solution.
> 
> ```
>   In Podfile:
>     PINCache (from `https://github.com/pinterest/PINCache`, branch `master`)
>     PINRemoteImage (from `https://github.com/zacwest/PINRemoteImage`, branch `fix-xcode-12.0b4`) was resolved to 3.0.0, which depends on
>     PINRemoteImage/PINCache (= 3.0.0) was resolved to 3.0.0, which depends on
>         PINCache (= 3.0.1-beta.8)
> ```

do this 
  pod 'Texture', '3.0.0'
  pod 'PINRemoteImage', :git => 'https://github.com/pinterest/PINRemoteImage', :branch => 'master'

this works for me

**Comment by rogerluan** [comment]
> There's an issue in the PINRemoteImage repo, and a PR too. [pinterest/PINRemoteImage#559](https://github.com/pinterest/PINRemoteImage/issues/559)

This one has been fixed already, but OP's issue is still a problem for us 😬

**Comment by mycroftcanner** [comment]
Finally works using Texture, PINRemoteImage, PinCache master branches. Thanks to all involved <3

Maybe we should keep this issue open until the release version works correctly and according to the README.md?

**Comment by rogerluan** [comment]
> Finally works using Texture, PINRemoteImage, PinCache master branches. Thanks to all involved <3
> 
> Maybe we should keep this issue open until the release version works correctly and according to the README.md?

How does your Podfile look like, to make it work? Did you have to specify tag, branch or version for `Texture`, `PINRemoteImage`, or `PinCache`?

**Comment by lazarevzubov** [comment]
Builds successfully in Xcode 12 using the latest Texture (```pod 'Texture'```) and without specifying its components versions/branches (so, currently it's PINCache 3.0.1, PINOperation 1.2, PINRemoteImage 3.0.1, Texture 3.0.0.)

**Comment by MeGaPk** [comment]
for hotfix pincache with version 2.8.1, just use it on cocoapod file:
```
          if target.name == "PINCache" or target.name == "PINRemoteImage"
                puts "Updating #{target.name} OTHER_CFLAGS"
                target.build_configurations.each do |config|
                    config.build_settings['OTHER_CFLAGS'] = '-Xclang -fcompatibility-qualified-id-block-type-checking'
                end
            end
```
