### ISSUE TITLE
ASPagerNode

### ISSUE THREAD

**Issue by VitaliyYarkun** [TextureGroup/Texture#1940]
Hi, 
Can someone point me out why do I have extra space on the left, when I am using ASPagerNode?
Here is a link for a sample project:
[link](https://github.com/VitaliyYarkun/PagerTest)

And gif that displays the result:
![test](https://user-images.githubusercontent.com/16116144/102402195-19591680-3fed-11eb-982e-9b015d0d9c51.gif)

**Comment by phucdth12a** [comment]
You can try
    let layout = ASPagerFlowLayout()
    layout.scrollDirection = .horizontal
    layout.minimumLineSpacing = 0
    layout.minimumInteritemSpacing = 0

    super.init(frame: .zero, collectionViewLayout: layout, layoutFacilitator: nil)

**Comment by VitaliyYarkun** [comment]
```
layout.minimumLineSpacing = 0
layout.minimumInteritemSpacing = 0
```

Solved it, thanks @phucdth12a
