### ISSUE TITLE
Bounds of ASViewController.init(node: ASDisplayNode) is incorrect in iOS 15

### ISSUE THREAD

**Issue by uyloal** [TextureGroup/Texture#2022]
In my project, ASViewController is based on a tab view controller with navigation controller. 
Before iOS 15, it's bounds limited by navigation height and tab height., looks like this
![image](https://user-images.githubusercontent.com/37807381/132817306-b7025100-4431-478d-93b7-2012898f48eb.png)

But when I build it with Xcode 13 beta, the bounds of view controller is as same as screen. 
How can I solve this problem? And is Texture still supported in the future?

**Comment by FlyerYe** [comment]
tablenode的内容会偏移
