### ISSUE TITLE
Failed to compile on Apple Silicon [M1]

### ISSUE THREAD

**Issue by rahulvyas** [TextureGroup/Texture#2057]
I have recently upgraded to M1 Macbook and now I'm having errors when building my project.

Does anyone know how to fix this?

**Comment by lappp9** [comment]
Hey @rahulvyas, I tried building the project as well as installing it into another project locally with cocoa pods on my M1 Mac and everything seemed to work fine. Did you have a sample app you could provide that reproduces this issue?

**Comment by rahulvyas** [comment]
> Hey @rahulvyas, I tried building the project as well as installing it into another project locally with cocoa pods on my M1 Mac and everything seemed to work fine. Did you have a sample app you could provide that reproduces this issue?

Thanks for your reply. I was able to fix the issue on my machine. Closing the issue.

**Comment by foxware00** [comment]
@rahulvyas anything in particular you did to get it to compile. I'm facing similar issues.

**Comment by foxware00** [comment]
Interestingly, I think those gems are related to rosetta and aren't aren't necessary. As least I've got it working without them

What it took for me was converting `ASDimensionMake(CGFloat)` into `ASDimension(unit: .points, value: CGFloat)`

It was complaining about an issue with the optimisations done at release. Debug builds were always fine.

**Comment by rahulvyas** [comment]
> Thanks for the response @rahulvyas Interestingly, I think those gems are related to rosetta and aren't aren't necessary. As least I've got it working without them
> 
> What it took for me was converting `ASDimensionMake(CGFloat)` into `ASDimension(unit: .points, value: CGFloat)`
> 
> It was complaining about an issue with the optimisations done at release. Debug builds were always fine.

Great
