### ISSUE TITLE
App crashes due to assertion "Expected that all old sections were deleted before...sections.."

### ISSUE THREAD

**Issue by garrettmoon** [TextureGroup/Texture#206]
_From @Rokimkar on March 21, 2017 9:15_

I have a ASTableNode and the ASCellNode contains a horizontal ASCollectionNode in it with a default 10 items. Everything works fine when the ViewController containing this ASTableNode is pushed in the Navigation.
But, as soon as I pop the ViewController it crashes with an assertion.

It happens for AsyncDisplayKit pod 2.2 version.
It is working absolutely fine on the previous pod version.

P.S. It got crashed at " **ASDisplayNodeAssert([self editingNodesOfKind:ASDataControllerRowNodeKind].count == 0, @"Expected that all old sections were deleted before %@. Sections: %@", NSStringFromSelector(_cmd), [self editingNodesOfKind:ASDataControllerRowNodeKind]);**" in **ASCollectionDataController.mm**.

_Copied from original issue: facebookarchive/AsyncDisplayKit#3201_

**Comment by garrettmoon** [comment]
_From @naveen7b on March 21, 2017 9:46_

**+1**
Same issue occurred to me with version 2.2

**Comment by garrettmoon** [comment]
_From @hamewang on March 22, 2017 3:5_

Can not use    UICollectionViewFlowLayout ->estimatedItemSize

**Comment by garrettmoon** [comment]
_From @Adlai-Holler on March 22, 2017 18:39_

@Rokimkar Could you provide some sample code with a repro? Are you using `estimatedItemSize` as @hamewang mentioned?

**Comment by garrettmoon** [comment]
_From @hamewang on March 23, 2017 1:7_

@Adlai-Holler create viewController extens ASViewController， overwrite  init Method
- (instancetype)init {
    UICollectionViewFlowLayout *fLayout = [[UICollectionViewFlowLayout alloc] init];
    fLayout.minimumLineSpacing = 10;
    fLayout.minimumInteritemSpacing = 10;
    fLayout.estimatedItemSize = CGSizeMake(100, 50);
    ASCollectionNode *mainNode = [[ASCollectionNode alloc] initWithCollectionViewLayout:fLayout];
    if (self = [super initWithNode:mainNode]) {
        mainNode.dataSource = self;
        mainNode.delegate = self;
    }
    return self;
}

ASCollectionDataSource Method

- (ASCellNodeBlock)collectionNode:(ASCollectionNode *)collectionNode nodeBlockForItemAtIndexPath:(NSIndexPath *)indexPath {
    return ^ASCellNode *() {
        ASTextCellNode *nodel = [[ASTextCellNode alloc] init];
        nodel.text = @"aaaa";
        return nodel;
    };
}

 self.navigationController pushViewController   this method is OK;
but  self.navigationController popViewControllerAnimated this method error

**Comment by garrettmoon** [comment]
_From @Rokimkar on March 23, 2017 6:41_

@Adlai-Holler  [https://github.com/naveen7b/AsyncDisplayKit-Example](link) link for the example project. This project will work fine if the Async display kit version is before 2.2 and it is crashing for version 2.2. Thanks @naveen7b  for the sample code.

**Comment by garrettmoon** [comment]
_From @zjmdp on April 1, 2017 4:20_

I got the same issue rarely, but it did happen.

**Comment by garrettmoon** [comment]
_From @yxztj on April 14, 2017 2:27_

Same here. Guess the app didn't crash in production due to NSAssert being disabled in release build.

**Comment by appleguy** [comment]
@Rokimkar @naveen7b -- I ran asyncdisplaykit-example, and happily the app seems to be working well on the latest version of Texture. Just change out your Podfile definition from AsyncDisplayKit ~> 2.2, to Texture instead and you'll get the latest version.

Please do try this out and update this task if you see any issues. I'd like to make sure they're resolved. Thanks for filing this shortly after 2.2 was launched to report the issue - we acted on this because of getting reports!
