### ISSUE TITLE
Add target on ControlNode not working

### ISSUE THREAD

**Issue by garrettmoon** [TextureGroup/Texture#220]
_From @Ghana93 on April 16, 2017 11:41_

i added this code in LikeNode (in init method) of social app example,but its not working 
 
    [self addTarget:self action:@selector(likeTapped:) forControlEvents:ASControlNodeEventTouchUpInside];

    -(void)likeTapped:(id)sender {
     NSLog(@"Like Button Pressed");
    }
Please help
Thank you,
Gaurav 

_Copied from original issue: facebookarchive/AsyncDisplayKit#3276_

**Comment by garrettmoon** [comment]
@Ghana93 it looks like it's because the PostNode is changing it to be layer backed. In the latest master we've added an assert that prevents this. So now the example asserts on load when the PostNode tries to make it layer backed.

**Comment by Ghana93** [comment]
Yes,By Removing code from line 186 to 188 in PostNode.m,

      for (ASDisplayNode *node in self.subnodes) {
            node.layerBacked = YES;
       }
i was able to perform action task..
Thank You
