### ISSUE TITLE
Ditch the Changelog

### ISSUE THREAD

**Issue by Adlai-Holler** [TextureGroup/Texture#228]
The changelog is currently more trouble than its worth. It's always conflicted, which means another commit and another CI build. And since we squash-and-merge, it's easy enough to translate a commit range into a friendlier set of release notes as needed.

Thoughts @garrettmoon @nguyenhuy @maicki @appleguy ?

Let's resolve this RFC by Friday, May 5th at 10AM pacific.

**Comment by nguyenhuy** [comment]
I always forget updating the file.  And I've solved conflicts in it multiple times.  Although I certainly understand its benefits, I'm in favor of ditching it to streamline the PR process.  As Aldai said, the changelog can be derived from squashed commits.

**Comment by garrettmoon** [comment]
I'm against this because I do the releases :D With the changelog we could have releases set up to be nearly automatic, without it not so much.

If we can figure out a way to not build on a commit that's *just* a change to the changelog, would that alleviate some of this?

Also, weren't we going to use PRs and the plans directory for RFCs?

**Comment by nguyenhuy** [comment]
@garrettmoon Yes, being able to skip the build would be good.  Not sure if it's feasible and worth it, but can we have a script/bot that updates the changelog when a PR is merged, using the PR's title as the log entry, and skips if the title includes #trivial?

**Comment by garrettmoon** [comment]
So I'm going to throw you under the bus here @nguyenhuy, here's the title of a PR vs the wonderful changeling entry you wrote:

Title:
`Introduce ASCollectionGalleryLayoutDelegate`

Changelog:
`Add ASCollectionGalleryLayoutDelegate - an async collection layout that makes same-size collections (e.g photo galleries, pagers, etc) fast and lightweight!`

**Comment by garrettmoon** [comment]
So I'm not opposed to getting rid of the changelog if we can reliably get PR titles that are just as good. The obstacles I see to that:
1. People quickly make titles, the changelog prompts them to spend the time to write something nice.
2. Github PR titles are limited by length.

**Comment by nguyenhuy** [comment]
haha, it's true that people tend to spend more time on the changelog when they're forced to.  I know I'm guilty :P

**Comment by Adlai-Holler** [comment]
Alright time's up. We're keeping the changelog.
