### ISSUE TITLE
Release version with updated Cartfile / Xcode 8.3 support

### ISSUE THREAD

**Issue by dymv** [TextureGroup/Texture#234]
Hey guys,

As we merged #37 we got Xcode 8.3 support in master, but haven't released any version with it.

Could you release a version so we don't have to point to master branch in our project's Cartfile.

Thanks

**Comment by garrettmoon** [comment]
We just pushed out a release at Pinterest which we'll use as a basis once we're sure there aren't any big crashes. Aiming to publish it tomorrow.
