### ISSUE TITLE
Custom layout transition ignores frame animation for ASImageNode (instant)

### ISSUE THREAD

**Issue by fruitcoder** [TextureGroup/Texture#249]
I am using a simple custom layout transition to animate between a truncated and non-truncated text node. Basically, I want all nodes below (y-coordinate-wise) the text node to be animated down while fading in the truncated or non truncated node. Actually this should work with the default layout transition animation, but somehow my image node (1pt. horizontal hairline) is ignored in the default animation AND the custom transition. 
Here is the transition code:
```
override func animateLayoutTransition(_ context: ASContextTransitioning) {
    guard
      let fromNode = context.removedSubnodes().get(index: 0),
      let toNode = context.insertedSubnodes().get(index: 0)
      else { return }

    let heightDifference = abs(context.finalFrame(for: toNode).size.height - context.finalFrame(for: fromNode).size.width)

    guard heightDifference >= 0.0 else { return }

    let nodesBelowText = [lineNode,
                          playButton,
                          bookmarkButton,
                          shareButton]

    toNode.alpha = 0.0 // start hidden

    UIView.animate(withDuration: defaultLayoutTransitionDuration, animations: { [weak self] in
      guard let `self` = self else { return }

      // self size
      if
        let fromSize = context.layout(forKey: ASTransitionContextFromLayoutKey)?.size,
        let toSize = context.layout(forKey: ASTransitionContextToLayoutKey)?.size,
        fromSize != toSize {
        self.frame = CGRect(x: self.frame.origin.x,
                            y: self.frame.origin.y,
                            width: toSize.width, height: toSize.height)
      }

      fromNode.alpha = 0.0
      toNode.alpha = 1.0

      nodesBelowText.forEach({ $0.frame = context.finalFrame(for: $0) })

    }) { context.completeTransition($0) }
  }

```

Is there any reason why a node isn't considered in the animation?
(Using Texture 2.3.1 via Carthage)

**Comment by garrettmoon** [comment]
@fruitcoder can you put up a sample project that demonstrates this? Thanks in advance!

**Comment by fruitcoder** [comment]
I found the issue. My lineNode has `isLayerBacked = true`. Any reason why the layout transition API doesn't support layer backed nodes? If his was obvious from the documentation I'll close the issue right away :)

**Comment by garrettmoon** [comment]
We definitely should be supporting layer backed nodes, I'm not aware of any limitations there. Put up a sample project and we'll take a look :)

**Comment by 9you** [comment]
I have a similarly case when layer backed nodes doesn't work with layout transition API and I think that it work as designed. It would be nice if layout transition API can support layer backed nodes 💯

**Comment by fruitcoder** [comment]
I will provide a simple example project first thing in the morning

**Comment by fruitcoder** [comment]
Okay 5th thing in the morning ^^
[LayoutTransition.zip](https://github.com/TextureGroup/Texture/files/987184/LayoutTransition.zip)

**Comment by garrettmoon** [comment]
@fruitcoder I'll take a look!

**Comment by garrettmoon** [comment]
Ah, I misunderstood what was going on here. I don't think it has anything to do with the transition API and everything to do with using UIView to animate layers?

This is definitely a limitation of the framework; it would be nice if we had a way to animate nodes regardless of if they're view or layer backed.

**Comment by fruitcoder** [comment]
Holy shit, that was stupid -.- Maybe a animation wrapper API that encapsulates UIView and CAAnimations would help. But I don't think that should be started without thinking about interactive animations might work. Maybe on the same level of abstraction with similar API. 
I'll close this issue for now since it was just my mistake and didn't have anything to do with the framework :)
