### ISSUE TITLE
How can I know ASVideoNode occurred an error?

### ISSUE THREAD

**Issue by bawn** [TextureGroup/Texture#252]
Texture version : 2.3.1

For example load .flv video or load timeout. So far I have not found any error callback.

**Comment by Petrachkov** [comment]
Hi @bawn ! I've added to ASVideoNode.h the following:

`- (void)videoNodeDidFailToInitAsset:(ASVideoNode *)videoNode withError:(NSError *)error;`

and then in ASVideoNode.mm  inside - (void)prepareToPlayAsset:(AVAsset *)asset withKeys:(NSArray<NSString *> *)requestedKeys :

 ```
ASDisplayNodeAssertMainThread();
  
  for (NSString *key in requestedKeys) {
    NSError *error = nil;
    AVKeyValueStatus keyStatus = [asset statusOfValueForKey:key error:&error];
    if (keyStatus == AVKeyValueStatusFailed) {
        NSLog(@"Asset loading failed with error: %@", error);
        **[self.delegate videoNodeDidFailToInitAsset:self withError:error];**

    }
  }
  
  if ([asset isPlayable] == NO) {
    NSLog(@"Asset is not playable.");
    return;
  }
``` 

then you can detect errors. I've never submitted that Improvement proposal to the Texture team but i think you might find it helpful.

**Comment by Petrachkov** [comment]
and don't forget to add these files to you git and update CI build host to work around all your pod updates in case you use it.

**Comment by bawn** [comment]
Thanks, This is really useful. I think you can try submit a RP.

**Comment by Petrachkov** [comment]
Just have done that. Waiting for approval :)
