### ISSUE TITLE
Type inference via auto_type

### ISSUE THREAD

**Issue by nguyenhuy** [TextureGroup/Texture#26]
Having type inference would be helpful in many cases. Details can be found in [this great blog post](https://medium.com/@maicki/type-inference-with-auto-type-55a38ef56372). Let me know what you all think!

P/S: If we decide to introduce this, we need to update our coding guidelines.

**Comment by Adlai-Holler** [comment]
For the time being, a couple thoughts:

- Using `let` and `var` macros inconsistently in a public framework is a little unprofessional.
- `__auto_type` can interfere with SourceKit, making development slightly more frustrating.
- `__auto_type` on its own is ugly but useful in cases like `NSMapTable<NSString *, ASDisplayNode *> *mapTable = [self generateMapTable]` 
- Maybe it would be appropriate to use `__auto_type` directly but sparingly, in cases where it makes sense, up to the discretion of the coder. `NSArray<NSString *> *` may not justify it, for example.

**Comment by maicki** [comment]
I'm sharing the opinion of @Adlai-Holler:
* We should not introduce `let` and `var` as it's not common standard
* Using `__auto_type` can be cumbersome
* We should slowly introduce it in places where it makes sense e.g. for blocks etc.

**Comment by nguyenhuy** [comment]
Thanks for the thoughtful feedbacks.  Let's use `__auto_type` on a case by case basic and don't introduce project-wise `let` and `var` macros.  Closing this RFC.
