### ISSUE TITLE
Multiple leaks after updating

### ISSUE THREAD

**Issue by kamvoick** [TextureGroup/Texture#266]
Hello, after updating to latest version found out there are many leaks which weren't there before. I guess I can't do anything about that myself? 
Screenshot:
![zrzut ekranu 2017-05-13 o 15 22 10](https://cloud.githubusercontent.com/assets/19606025/26025882/4c4a1aec-37f1-11e7-820a-e5e36ac7dda2.png)

**Comment by maicki** [comment]
@kamvoick Hey thanks you for reporting. Can you please add an Instruments profile to this issue so we can see the code path what actually caused the leaks? Thanks!

**Comment by appleguy** [comment]
@kamvoick Likewise, this is a valuable report - can you share the test project you used (or if it occurs with any of our example projects), or just put the entire profile in a .zip file and share it on Google Drive / Dropbox?

**Comment by appleguy** [comment]
@kamvoick checking in - please let us know if you're still observing this on the current version, or can provide any other details. We'd love to fix it. I'm hesitant to close this issue, but without a bit of additional detail I don't see a way to investigate it.

**Comment by nguyenhuy** [comment]
I profile the Pinterest app recently and didn't notice any leak related to `ASLayout`. I suppose it's no longer an issue. Please reopen this ticket with more details if you're still hitting it. Thanks!
