### ISSUE TITLE
[ASEditableTextNode] isSecureTextEntry not working

### ISSUE THREAD

**Issue by plm75** [TextureGroup/Texture#273]
Setting the `isSecureTextEntry` property to `true` on an `ASEditableTextNode` has no effect; input text is always visible

**Comment by ay8s** [comment]
@plm75 I don't believe this is supported right now. I've been using UITextField in a few of my projects for this. Also spotted theres a ASTextFieldNode which also does this. https://github.com/pocketlabs/ASTextFieldNode

**Comment by plm75** [comment]
@ay8s ok then. Thanks
