### ISSUE TITLE
ASVideoNode delegate respondsToSelector crash.

### ISSUE THREAD

**Issue by ArmandsB** [TextureGroup/Texture#291]
Hello. I noticed that at line 156 @ ASVideoNode.mm class calls delegate function before checking if it's implemented.

```
- (void)prepareToPlayAsset:(AVAsset *)asset withKeys:(NSArray<NSString *> *)requestedKeys
{
  ASDisplayNodeAssertMainThread();
  
  for (NSString *key in requestedKeys) {
    NSError *error = nil;
    AVKeyValueStatus keyStatus = [asset statusOfValueForKey:key error:&error];
    if (keyStatus == AVKeyValueStatusFailed) {
      NSLog(@"Asset loading failed with error: %@", error);
      [self.delegate videoNode:self didFailToLoadValueForKey:key asset:asset error:error]; // Here is check needed
    }
  }
  
`

**Comment by Petrachkov** [comment]
Hi @ArmandsB ! Quick fix would be to simply implement protocol ASVideoNodeDelegate with didFailToLoadValueForKey method. But right solution will be to add necessary checks to ASVideoNode.mm . I submitted this code in PR last week and obviously forgot to add flags and these checks to .mm file as i'm more Swift developer than ObjC and I cannot just leave something from swift protocol not implemented behind. Sorry for inconvenience
