### ISSUE TITLE
LineSpacing issue in NSMutableParagraphStyle with ASTextNode

### ISSUE THREAD

**Issue by shashank-rps** [TextureGroup/Texture#30]
When an attributed string has different fontSize for words, **lineSpacing** property of **NSMutableParagraphStyle** is not working with **ASTextNode**. This is reproducible in 
ASDKgram also.  

Here is the code snippet which I used to reproduce this issue. I am trying to bring lines closer by giving `lineSpacing = 0` but seems like it is not working. To reproduce it in ASDKgram just change `descriptionAttributedStringWithFontSize` method implementation in `PhotoModel.m`  

```   
- (NSAttributedString *)descriptionAttributedStringWithFontSize:(CGFloat)size {  
  NSArray *fontPerLineArray = @[@{@"Dicover new" : [NSNumber numberWithFloat:70]},
                                @{@"people near" : [NSNumber numberWithFloat:42]}, 
                                @{@"your location" : [NSNumber numberWithFloat:10]}];
  
  __block NSMutableAttributedString *attString = [[NSMutableAttributedString alloc] initWithString:@""];
  
  [fontPerLineArray enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
    [obj enumerateKeysAndObjectsUsingBlock:^(NSString * _Nonnull lineText, id  _Nonnull obj, BOOL * _Nonnull stop) {
      NSMutableAttributedString *newAttributedString = [[NSMutableAttributedString alloc] initWithString:[NSString stringWithFormat:@"%@%@", lineText, idx == [fontPerLineArray count] - 1 ? @"" : @" "]];
      [newAttributedString addAttributes:@{NSForegroundColorAttributeName:[UIColor blackColor], NSFontAttributeName:[UIFont systemFontOfSize:[obj integerValue]]} range:NSMakeRange(0, lineText.length)];
      [attString appendAttributedString:newAttributedString];
    }];
  }];
  
  NSMutableParagraphStyle *paragraphStyle = [NSMutableParagraphStyle new];
  paragraphStyle.alignment = NSTextAlignmentCenter;
  paragraphStyle.lineSpacing = 0;
  [attString addAttribute:NSParagraphStyleAttributeName value:paragraphStyle range:NSMakeRange(0, attString.length)];
  return attString;
}  
```  
  
Attaching the screenshot of ASDKgram feed with ASTextNode having text with different font sizes. 

![img_6470](https://cloud.githubusercontent.com/assets/16534263/25133367/157149f4-246a-11e7-8cf3-5376a9b1942a.PNG)

**Comment by maicki** [comment]
Hey @shashank-rps, `lineSpacing` is 0 by default for paragraph styles, so basically nothing changes if you would not set it at all (see screenshot below), just the default behavior will be applies. Although the documentation says the `lineSpacing` is always `nonnegative` if you set it to negative it actually brings the lines close ... that said this is kind of a hack and I think it could result in undefined behavior. 

I will close this issue for now as on Texture's side it works as expected. Thanks!

<img width="755" alt="screen shot 2017-04-25 at 8 31 15 am" src="https://cloud.githubusercontent.com/assets/25288/25394008/ecf02446-2991-11e7-8795-13bc8dca1819.png">

**Comment by shashank-rps** [comment]
@maicki ok, but is there a way by which I can bring these lines closer?

**Comment by maicki** [comment]
@shashank-rps Set a negative `lineSpacing`, but as said it's kind of an undefined behavior I guess ...
