### ISSUE TITLE
[ASImageNode] wrong image representation while Hero transition.

### ISSUE THREAD

**Issue by denbezrukov** [TextureGroup/Texture#314]
Hi, I want to use Texture with [Hero](https://github.com/lkzhao/Hero)
[Project](https://github.com/Dominionys/Texture-Hero) and [Original Project](https://codeload.github.com/lkzhao/HeroVerticalCityGuideExample/zip/v1.0)
And I have problem with transition. I found [previous issues](https://github.com/facebookarchive/AsyncDisplayKit/issues/2302). But forcedSize doesn't help.
![problem](https://cloud.githubusercontent.com/assets/6227442/26551733/1c6ac640-44ae-11e7-9a4f-63e85280a3ca.gif)

**Comment by rayanmestiri** [comment]
I have the exact same issue, didn't find how to prevent stretching.

**Comment by hashemp206** [comment]
disable `cropEnabled` in `ASImageNode`. will fix the problem
