### ISSUE TITLE
[ASNetworkImageNode] Not loading image from local url

### ISSUE THREAD

**Issue by agusguerra10** [TextureGroup/Texture#319]
Hi guys, I'm having some issues with ASNetworkImageNode. AppLovin SDK is giving me a local url for the ad image, something like: "file:///Users/...."

My ASNetworkImageNode is not loading it, I just see the background color.
I tried using a simple UIImageView and load the file from the url using Kingfisher and it shows up perfectly, so the image does exist in that URL.

![screenshot](https://cloud.githubusercontent.com/assets/1181803/26564513/04940752-44b8-11e7-824f-131dee4c7a59.png)

UIImageView on top left, and the ASNetworkImageNode covering the entire view showing just the background color. The URL I use being the same for both the UIImageView and the ASNetworkImageNode, which is the one printed in the center of the screen

Any idea why this could be happening and how to resolve it?

Thanks!

**Comment by lappp9** [comment]
@agusguerra10 I'm seeing something similar to this with a regular ASImageNode instance. It only happens intermittently though and i'm not sure why

**Comment by maicki** [comment]
Hey @agusguerra10 or @lappp9, could one of you provide a small example we could use to dive deeper. Thanks!

**Comment by agusguerra10** [comment]
Hey @lappp9, my particular issue was related to the location of the image I was assigning to my ASNetworkImageNode. I had a file cached in the disk (you can see the url in the screenshot I attached in the above post but it obviously won't work for you) and it wouldn't load if I used an ASNetworkImageNode. I ended up analyzing the image url and going with a plain ASImageNode if the file url starts with "file://".
I believe you should be able to reproduce this by just saving a file to disk and trying to load it using an ASNetworkImageNode.

Thank you and let me know if that was clear enough :)

**Comment by maicki** [comment]
@agusguerra10 `ASNetworkImageNode` has an interesting handling around this as the moment and I would say it's not really obvious at first.

There exists a property called `shouldCacheImage` on `ASNetworkImageNode`. If set to `YES` it uses the last path of the URL and tries to look up this image via `[UIImageNode imageNamed:]` and not try to load the data from the hard drive. It's set to `YES` by default, so if you set it to `NO` this should resolve your issue. Please reopen in case this is not the case!

Thanks!
