### ISSUE TITLE
[Documentation] Parameter 'elementToLayoutArrtibutesMap' not found in the function declaration

### ISSUE THREAD

**Issue by TanderZA** [TextureGroup/Texture#324]
There's a slight documentation issue in ASCollectionLayoutState.h L: 37 

` * @param elementToLayoutArrtibutesMap Map between elements to their layout attributes. The map may contain all elements, or a subset of them and will be updated later. 
`
Should be: 

` * @param attrsMap Map between elements to their layout attributes. The map may contain all elements, or a subset of them and will be updated later. 
`

**Comment by maicki** [comment]
@TanderZA Hey! Can you please verify that this issue was fixed on master and close if so. Thanks!

**Comment by TanderZA** [comment]
Looks good to me!
