### ISSUE TITLE
ASCollectioNode crash during performBatchUpdates if no preferredSize specified

### ISSUE THREAD

**Issue by ibarisic05** [TextureGroup/Texture#341]
Hi all, thanks for great lib. Found an crash under ASCollectionNode during performBatchUpdates insert statement if there is no preferredSize specified. 
![screen shot 2017-06-08 at 13 14 54](https://user-images.githubusercontent.com/6560022/26949202-4c84b870-4c99-11e7-8ef2-b160d9e9aa3f.png)

Issue I was facing was that I needed to return one empty ASCellNode and I was returning it as
`return ASCellNode()`
this was creating a crash that you can see at screenshot. After moving this code to snippet below, everything seems to work fine.
`let node: ASCellNode = ASCellNode()
node.style.preferredSize = UIScreen.main.bounds.size
return node`

Don't know if this is intended behaviour or not, but this one cost me some time. Hope this helps someone. Maybe putting some info on this one, or something similar.

If you need more info let me know. Credit for fix goes to ypogribnyi on Slack.

**Comment by Adlai-Holler** [comment]
Hi @ibarisic05 thanks for the issue report! This was resolved in #348 by suppressing main-thread assertions during `-debugDescription`. Hope to see you around more!
