### ISSUE TITLE
When i "pod install",it's something wrong，pleasehelp

### ISSUE THREAD

**Issue by FunnyFzl** [TextureGroup/Texture#349]
<img width="593" alt="2017-06-11 5 26 25" src="https://user-images.githubusercontent.com/15104149/27009869-577f3406-4ecb-11e7-83e3-408c2a6744c0.png">

**Comment by nguyenhuy** [comment]
Hi, this has nothing to do with Texture. There are conflicts between your project settings and CocoaPods. Please find more information and possible solutions here: https://stackoverflow.com/questions/18376416/the-target-overrides-the-other-ldflags-build-setting-defined-in-pods-pods
