### ISSUE TITLE
Version of PINRemoteImage wasn't updated in the release of 2.3.3

### ISSUE THREAD

**Issue by xilin** [TextureGroup/Texture#354]
It seems in the commit 4a97c4e53c0c97213231eb266ed328bba3c760f0, we have bump the version of PINRemoteImage to '3.0.0-beta.10', which contain a fix of [crash](https://github.com/pinterest/PINRemoteImage/pull/341).

But this commit didn't show up in the release of 2.3.3.

**Comment by xilin** [comment]
Just find out the code for release seems free on May 23

**Comment by cincas** [comment]
We have same issue here as well.

Seems like podspec in CocoaPods spec repo is not updated to use `3.0.0-beta.10`, it is still `3.0.0-beta.9`

Here is the podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/a/3/e/Texture/2.3.3/Texture.podspec.json

**Comment by xilin** [comment]
@cincas Yeah. I just choose to use the master branch

**Comment by cincas** [comment]
@xilin, kinda risky tbh

We end up choose the commit `00fb3f6cd7dce`
