### ISSUE TITLE
ASNetworkImageNode in swift load gif not animating

### ISSUE THREAD

**Issue by huangboju** [TextureGroup/Texture#36]
This is my code 
```swift
let imageNode = ASNetworkImageNode()

        imageNode.url = URL(string: "https://media.giphy.com/media/l2R0aKwejYr8ycKAg/giphy.gif")
        imageNode.delegate = self
        imageNode.frame = view.bounds
        imageNode.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        imageNode.contentMode = .scaleAspectFit
        view.addSubnode(imageNode)
```

**Comment by maicki** [comment]
Hey @huangboju, the core team can't field questions like this unfortunately. There's a ton of smart people helping one another apply Texture in the `#general` channel of the [Texture slack team](http://texturegroup.org/slack.html) or ask your question on [StackOverflow](http://stackoverflow.com). Thanks!
