### ISSUE TITLE
Support IGListKit 3

### ISSUE THREAD

**Issue by Pacek** [TextureGroup/Texture#364]
Currently only IGListKit 2.1.0 is supported. There's a new 3.0 version with API breaking changes.

**Comment by ay8s** [comment]
@Pacek Just submitted #367 which has most of the changes we included to get Texture working with 3.0.0. Would love to hear if you've spotted any other areas which needed to be updated.

**Comment by ay8s** [comment]
Think this one can be closed now https://github.com/TextureGroup/Texture/pull/367 is merged.

**Comment by maicki** [comment]
@ay8s Yep! Thanks for working on that!
