### ISSUE TITLE
AsTableNode invert, also cellnode edit button invert

### ISSUE THREAD

**Issue by garyoo** [TextureGroup/Texture#373]
Hi. Thank you for ASDK..
I made tablenode inverted for chat.

Tablenode edit (swipe) button also inverted.
How fix it?

**Comment by FengDeng** [comment]
hi @garyoo , try this.

`    override func didEnterVisibleState() {
        super.didEnterVisibleState()
        if let subviews = self.view.superview?.superview?.subviews,let cc = NSClassFromString("UITableViewCellEditControl"){
            for editView in subviews{
                print("layout : \(editView.classForCoder)")
                if editView.isKind(of: cc){
                    editView.transform = __CGAffineTransformMake(1, 0, 0, -1, 0, 0)
                }
            }
        }

    }
    
    override func layout() {
        super.layout()
        if let subviews = self.view.superview?.superview?.subviews,let cc = NSClassFromString("UITableViewCellEditControl"){
            for editView in subviews{
                print("layout : \(editView.classForCoder)")
                if editView.isKind(of: cc){
                    editView.transform = __CGAffineTransformMake(1, 0, 0, -1, 0, 0)
                }
            }
        }
    }`

**Comment by ay8s** [comment]
This is expected right now, the above should resolve it 👍
