### ISSUE TITLE
Can't set an ASCellNode as selected before node.isLoaded

### ISSUE THREAD

**Issue by skensell** [TextureGroup/Texture#374]
I am usually wary of using the default `selected` property and typically use a custom `picked` property because of problems like the following:

In my `ASTableDataSource` method I have something like this:

```Objective-C
- (ASCellNodeBlock)tableNode:(ASTableNode *)tableNode nodeBlockForRowAtIndexPath:(nonnull NSIndexPath *)indexPath {
    BOOL isSelected = YES; // or NO
    return ^ASCellNode*{
        MyCustomCellNode* cell = [[MyCustomCellNode alloc] init];
        cell.selected = isSelected;
        return cell;
    };
}
```

Unfortunately, this does not work because when `isSelected` is `YES`, this value gets overridden when the `_ASTableViewCell` is dequeued and `-setNode:` (in my ASDK 2.1, looks like `-setElement:` in Texture now) is called:

```Objective-C
- (void)setNode:(ASCellNode *)node
{
  _node = node;
  
  self.backgroundColor = node.backgroundColor;
  self.selectionStyle = node.selectionStyle;
  self.accessoryType = node.accessoryType;
  self.separatorInset = node.seperatorInset;
  self.clipsToBounds = node.clipsToBounds;
  
  [node __setSelectedFromUIKit:self.selected];
  [node __setHighlightedFromUIKit:self.highlighted];
}
```

This method seems to correctly transfer the node properties to the cell, but it does the converse for `selected` and `highlighted`, transferring the cell property to the node.  This is where my custom `ASCellNode`'s  `selected` gets set back to `NO` :(  Is this a bug?

**Comment by rewandy** [comment]
I think this has been fixed since 2.2? https://github.com/TextureGroup/Texture/commit/c7888672c8593cad8139851c9f645ca35b59c8a4

Note how the [latest version](https://github.com/TextureGroup/Texture/blob/b14ea8b95d20c5e8f96ee01f9e4cba2e08a3de49/Source/ASTableView.mm#L115) has an `if (node) {` check. There was a problem where if the `node` is `nil`, `selectionStyle` was getting set to `0`, which automatically went and unset the `selected` state as well.

**Comment by nguyenhuy** [comment]
I'm gonna close this issue assuming that it's fixed per @rewandy. Cheers!

**Comment by SandeepAggarwal** [comment]
@nguyenhuy I'm still facing this issue.

**Comment by fumito-ito** [comment]
I have same issue at Texture 2.6
