### ISSUE TITLE
ASTableNode swipe-to-delete cell gesture can leave delete action in a partially visible state

### ISSUE THREAD

**Issue by rewcraig** [TextureGroup/Texture#38]
When using UITableView's native swipe to delete table cell gesture, a partial swipe gesture either fully shows or hides the actions below the cell's content view.
![uikitswipecell](https://cloud.githubusercontent.com/assets/13108906/25187348/982d6aea-24d7-11e7-975d-c12b501a08db.gif)

The same gesture using ASTableNode/ASTableView leaves the cell's content view in a partially open state.

![texturecellswipe](https://cloud.githubusercontent.com/assets/13108906/25187334/8d4c5528-24d7-11e7-90d9-4c95a43f6e9f.gif)

It appears that this functionality is implemented in UITableView's own (private)
implementation of:
`-(void)scrollViewWillEndDragging:(UIScrollView *)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(inout CGPoint *)targetContentOffset;`

ASTableView overrides this method, which breaks the show/hide functionality.  Removing ASTableView's implementation restores the functionality; obviously this is not the solution.

As an ugly solution I have tried creating a category on UITableView to expose the private method and calling [super scrollViewWillEndDragging] at the top of ASTableView's implementation.
This resolves the show/hide problem, but it doesn't seem ideal and I'm not sure of it's impact on other code.  

Sample project:
[ASTableSwipe.zip](https://github.com/TextureGroup/Texture/files/935551/ASTableSwipe.zip)

**Comment by Adlai-Holler** [comment]
Hmm great catch! 

I think the thing to do is:

- At the top of `ASTableView.mm`, add the `@interface UITableView (ScrollViewDelegate)` category you described.
- Inside each of the scroll view delegate methods, add something like:

```
static BOOL superResponds;
static dispatch_once_t onceToken;
dispatch_once(&onceToken, ^{
  superResponds = [UITableView instancesRespondToSelector:_cmd];
});
if (superResponds && scrollView != self) {
  [super scrollViewDid……]; 
  return;
}
```

To keep the code cleaner, you could make a macro that contains the top portion and returns the `BOOL superResponds`.

This way we only message UITableView with UIScrollViewDelegate methods that it implements, and we only ever message it for other scroll views – UITableView doesn't listen for self-events on the public protocol, it uses private methods like `_scrollViewDid…` for that.

Would you be willing to implement it?

**Comment by rewcraig** [comment]
I'll certainly give it a shot! Thanks for the quick response :)

**Comment by Labun** [comment]
Hi, I use version 2.3.2 and this bug still appears. Any suggestions?

**Comment by rewcraig** [comment]
This was not integrated into the release until 2.3.3. Here is the commit:
https://github.com/TextureGroup/Texture/commit/e18d1394e4c3b203191c1a047cf6f5ac018f46f6
Hopefully you are able to upgrade from 2.3.2.
