### ISSUE TITLE
ASTextNode in ASStackLayoutSpec no line break

### ISSUE THREAD

**Issue by ChristianMoler** [TextureGroup/Texture#381]
## Hello Guys ! I’ve got some problem with ASTextNode . Can you help me ?

```
  override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
    _userAvatarImageView.style.width = ASDimensionMakeWithPoints(AvatarImageSize)
    _userAvatarImageView.style.height = ASDimensionMakeWithPoints(AvatarImageSize)
    let infoStack: ASStackLayoutSpec = ASStackLayoutSpec(direction: .vertical, spacing: 4.0, justifyContent: .spaceBetween, alignItems: .start, children: [_userNameLabel,_additionalDataLabel,_catalogNameLabel])
    let bottomStack: ASStackLayoutSpec = ASStackLayoutSpec(direction: .horizontal, spacing: 4.0, justifyContent: .start, alignItems: .start, children: [_userAvatarImageView,infoStack])
    let ratioSpec = ASRatioLayoutSpec(ratio: 0.5656, child: _videoImageView)
    let mainStack: ASStackLayoutSpec = ASStackLayoutSpec(direction: .vertical, spacing: 8.0, justifyContent: .start, alignItems: .start, children: [ratioSpec,bottomStack])
    let insets = UIEdgeInsets(top: 16.0, left: 16.0, bottom: 16.0, right: 16.0)
    let mainSpec = ASInsetLayoutSpec(insets: insets, child: mainStack)
    print(mainSpec.asciiArtString())
    return mainSpec
  }
```
## Screens
![2017-06-23 1 01 19](https://user-images.githubusercontent.com/8842139/27458687-f31a40fa-57b2-11e7-848f-6675eedfe99d.png)
![tbat995pvdu](https://user-images.githubusercontent.com/8842139/27458692-f7b2772c-57b2-11e7-8334-207eafbd9242.jpg)

**Comment by EviluS** [comment]
@ChristianMoler You can try and set `maxWidth` for the vertical `ASStackLayoutSpec` with the three `ASTextNodes` which  should fix your problem.

**Comment by ChristianMoler** [comment]
@EviluS thanks for answer ! How can i calculate maxWidth ?

**Comment by EviluS** [comment]
@ChristianMoler It will be something like:
`CGFloat maxWidth = constrainedSize.max.width - AvatarImageSize - leftPadding - rightPadding - space` - you should fill your correct values.

**Comment by ChristianMoler** [comment]
@EviluS Nice it's work , thanks ! Is this a normal solution? Unless the stack should not automatically calculate the size of the children?

**Comment by EviluS** [comment]
@ChristianMoler No problem. Answering your question - this is probably not the best solution. One better implementation is to set the `flexShrink` property of the `ASStackLayoutSpec` to `true` :) 

> `BOOL .style.flexShrink`	If the sum of childrens' stack dimensions is greater than the maximum size, should this object shrink?

**Comment by appleguy** [comment]
@ChristianMoler @EviluS yes, setting .style.flexShrink = 1.0; is the correct solution.
