### ISSUE TITLE
Couldn't find 'visible' supplementary element of kind UICollectionElementKindSectionHeader  assertion

### ISSUE THREAD

**Issue by mrvincenzo** [TextureGroup/Texture#385]
Getting the `Couldn't find 'visible' supplementary element of kind UICollectionElementKindSectionHeader at index path <> in map <>` assertion when animating section insertion with `performBatchUpdates` in `ASCollectionNode`. Please see https://github.com/facebookarchive/AsyncDisplayKit/pull/3158 for additional details.

Starting from scratch. First section insertion works well. Second section insertion gets the above assertion. Code snippet that reproduces the issue:

    import AsyncDisplayKit

    final class BatchUpdatesAssertion: ASViewController<ASCollectionNode> {
  
        fileprivate var timer: Timer!
        fileprivate var numberOfSections = 0

        init() {
            let layout = UICollectionViewFlowLayout()
            layout.scrollDirection = .vertical

            let node = ASCollectionNode(collectionViewLayout: layout)
            node.registerSupplementaryNode(ofKind: UICollectionElementKindSectionHeader)
      
            super.init(node: node)
      
            node.dataSource = self
            node.delegate = self
      
            timer = Timer.scheduledTimer(withTimeInterval: 2, repeats: true) {  _ in
                self.numberOfSections = self.numberOfSections + 1
                self.animateInsetion()
            }
        }
  
        required init?(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }

    // MARK: - ASCollectionDataSource

    extension BatchUpdatesAssertion: ASCollectionDataSource {
        func animateInsetion() {
            node.performBatchUpdates({ 
                node.insertSections(IndexSet(integer: 0))
                node.insertItems(at: [IndexPath(item: 0, section: 0)])
            }, completion: { _ in
            })
        }
  
        func numberOfSections(in collectionNode: ASCollectionNode) -> Int {
            return numberOfSections
        }
  
        func collectionNode(_ collectionNode: ASCollectionNode, numberOfItemsInSection section: Int) -> Int {
            return 1
        }
  
        func collectionNode(_ collectionNode: ASCollectionNode, nodeForItemAt indexPath: IndexPath) -> ASCellNode {
            let node = ASTextCellNode()
            node.text = "item"
            return node
        }
  
        func collectionNode(_ collectionNode: ASCollectionNode, nodeForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> ASCellNode {
            let node = ASTextCellNode()
            node.text = "section"
            return node
        }
    }

    // MARK: - ASCollectionDelegate

    extension BatchUpdatesAssertion: ASCollectionDelegate {
        func collectionNode(_ collectionNode: ASCollectionNode, constrainedSizeForItemAt indexPath: IndexPath) -> ASSizeRange {
            return ASSizeRangeUnconstrained
        }
  
        func collectionNode(_ collectionNode: ASCollectionNode, sizeRangeForHeaderInSection section: Int) -> ASSizeRange {
            return ASSizeRangeUnconstrained
        }
    }

**Comment by Pacek** [comment]
There's also example project with this crash in #397.

**Comment by Adlai-Holler** [comment]
Fix in #404 thanks for the detailed report @mrvincenzo!
