### ISSUE TITLE
Slack report: CustomCollectionView-Swift sample crashes

### ISSUE THREAD

**Issue by george-gw** [TextureGroup/Texture#39]
The crash report was posted by dviet on slack:
#### Crash:
`2017-04-18 14:39:48.931 Sample[8738:181740] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Range max width must be infinite or a real positive integer.'`

#### Link:
https://asyncdisplaykit.slack.com/conversation/C0V63R86T/p1492501729673862

**Comment by bolsinga** [comment]
It appears this was fixed by #22
