### ISSUE TITLE
"NSNode layoutSpecThatFits"  how to use FBShimmer  or other UIView for child to layout?

### ISSUE THREAD

**Issue by leece** [TextureGroup/Texture#390]
Now I had a ASCellNode and  use layoutSpecThatFits: for child node;
But now i need add FBShimmer for placeholder;
but    I can't replace
`- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize` 
`_priceLabel.style.spacingBefore = 3.0;`   
`_priceLabel.style.spacingAfter = 4.0;`  
to 
`_priceLabelPlaceHolderFBShimmer.style.spacingBefore = 3.0;`
because   _priceLabelPlaceHolderFBShimmer is UIView  not have  .style property.

and other UIView control  had the same problem。

**Comment by EviluS** [comment]
@leece You can wrap the `UIView` with `ASDisplayNode` like this
```
ASDisplayNode *node = [ASDisplayNode alloc] initWithViewBlock:^{
	SomeView *view  = [[SomeView alloc] init];
	return view;
}];
```

[ASDisplayNode Docs](http://texturegroup.org/docs/display-node.html)

**Comment by appleguy** [comment]
@leece - @EviluS is certainly correct. You can make a wrapper node as shown, and then the key thing is to provide a wrapperNode.style.preferredSize or other parameters (.minWidth, .height, etc) to instruct the system how to size that item when it is part of an async / background-thread layout.

You can reopen this or ask on Slack if you still have issues :).

**Comment by appleguy** [comment]
@leece more description here - https://youtu.be/ZPL4Nse76oY?t=30m32s
