### ISSUE TITLE
Crash: _ASDisplayLayer setNeedsLayout

### ISSUE THREAD

**Issue by DennisMostajo** [TextureGroup/Texture#392]
hi everyone:

I'm using XCode 8.3.3, I'm developing in Swift and I updated Texture with cocoapods to version 2.3.3, when I run on a real device I get this crash:
```
2017-06-27 18:42:55.351139-0400 MyProject[6946:1568249] *** Assertion failure in -[_ASDisplayLayer setNeedsLayout], /Users/dmostajo/Desktop/DENNIS/MyProject/Pods/Texture/Source/Details/_ASDisplayLayer.mm:122
2017-06-27 18:42:55.390330-0400 MyProject[6946:1568249] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This method must be called on the main thread'
*** First throw call stack:
(0x186f96fe0 0x1859f8538 0x186f96eb4 0x187a2e720 0x102da5ce8 0x18a2ab054 0x18a2ab4fc 0x18a2ac864 0x18a2ac9e0 0x102da5784 0x18d113c84 0x18d121e88 0x18d121784 0x18d0e5be4 0x18d1794e4 0x18dacb300 0x1000cf2d4 0x1000cf6bc 0x104664658 0x1045cab98 0x10466ac48 0x10466b130 0x1045cbe88 0x1045d44cc 0x1045d47e0 0x1045d5500 0x1045dd578 0x1046df648 0x100175018 0x10004c488 0x105729a50 0x105729a10 0x105737990 0x105739630 0x10573939c 0x186057100 0x186056cac)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
![captura de pantalla 2017-06-27 a la s 6 42 38 p m](https://user-images.githubusercontent.com/13056866/27613244-857e811e-5b68-11e7-8f43-4ee2a1f052e9.png)

I'm doing the test, but at no time I use a node to call setNeedsLayout, any help please?

thanks!

**Comment by Adlai-Holler** [comment]
Hi @DennisMostajo Based on the screenshot there, it looks like you're calling `UIRefreshControl endRefreshing` on a background thread (Thread 9). Unfortunately you can only call UIKit, CoreAnimation, and some Texture methods from the main thread (Thread 1). See https://developer.apple.com/documentation/code_diagnostics/main_thread_checker for more info.

You can use

```swift
DispatchQueue.main.async {
  refreshControl.endRefreshing()
}
```

to shift the work onto the main thread where it's safe to run. Hope that helps and I hope the framework serves you well!
