### ISSUE TITLE
Crashes when removing sections from ASCollectionNode

### ISSUE THREAD

**Issue by Pacek** [TextureGroup/Texture#397]
Hello, there are two types of crashes when removing sections from ASCollectionNode:

- "no UICollectionViewLayoutAttributes instance for -layoutAttributesForSupplementaryElementOfKind: UICollectionElementKindSectionHeader at path ..."
- "Supplementary node should exist ..."

Here is example project demonstrating both crashes: [ASDKTest.zip](https://github.com/TextureGroup/Texture/files/1107917/ASDKTest.zip)

**Comment by appleguy** [comment]
@Pacek thank you for providing the test project! It would be helpful to include the stack trace here, but I'll try running the project.
