### ISSUE TITLE
Auto Layout and InterfaceBuilder not permitted in established and disciplined iOS development teams, such as at Facebook, Instagram, and Pinterest.   is it really?

### ISSUE THREAD

**Issue by amjunliang** [TextureGroup/Texture#400]
Texture does not support UIKit Auto Layout or InterfaceBuilder

UIKit Auto Layout and InterfaceBuilder are not supported by Texture. It is worth noting that both of these technologies are not permitted in established and disciplined iOS development teams, such as at Facebook, Instagram, and Pinterest.

However, Texture’s Layout API provides a variety of ASLayoutSpec objects that allow implementing automatic layout which is more efficient (multithreaded, off the main thread), easier to debug (can step into the code and see where all values come from, as it is open source), and reusable (you can build composable layouts that can be shared with different parts of the UI). 

in doc

**Comment by appleguy** [comment]
@amjunliang https://youtu.be/ZPL4Nse76oY?t=31m5s -- basically, you'll have some challenges mixing these patterns with Texture.

It is definitely true that the companies mentioned do not use either Auto Layout *or* Interface Builder. In addition, YouTube does not allow use of either of these tools.

Both of them have serious problems with larger scale projects - anything involving more than ~10 developers or having a priority on high performance user experience shouldn't use them.

**Comment by amjunliang** [comment]
Thank you, I see it
