### ISSUE TITLE
More Memory

### ISSUE THREAD

**Issue by zly880** [TextureGroup/Texture#417]
i use it in my project. when i slide ASTableNode so quickly. I find my memory raise so quickly . Then i stop. After 30 seconds, i find memory is still so much. SO, when i slide this, all cell are not release？

**Comment by hashemp206** [comment]
please upload a sample project. You have a retain cycle. It's not related to `Texture`

**Comment by zly880** [comment]
I loader about 1000 rows，when my merory in xcode is 100M, is normal？

**Comment by hashemp206** [comment]
does memory  increase as you scroll? if it is stable is normal. else you need to check your code

**Comment by zly880** [comment]
I use sample for ASCollectionView. I see then memory increase in Xcode when I scroll.

**Comment by hashemp206** [comment]
No, I don't see such memory leak issue in the default ASCollectionView example

**Comment by zly880** [comment]
close zombie objects， then you can see memory.

**Comment by nguyenhuy** [comment]
Hi, nodes are supposed to have a long lifecycle. They survive until deleted/reloaded. The node objects themselves should not consume much memory, so it's fine to have thousands of them alive at any given time. Nodes' data, however, is cleared as soon as the nodes fall outside of the preload range. That means you should see the memory consumption to increase when the collection/table loads all the nodes, but then stabilize at a certain level and doesn't keep growing at you scroll.

If you're seeing a high memory consumption that keeps increasing over time, chances are your nodes are retaining their data and don't release it. In that case, you can override `-clearContents` in your custom node class and clear its memory intensive data.

I'm closing this issue now but feel free to reopen it if you have follow-up questions. Also, we have a [Slack community](http://texturegroup.org/slack.html) that is typically more responsive.

(Possible duplication with https://github.com/TextureGroup/Texture/issues/461)
