### ISSUE TITLE
Issue new AsyncDisplayKit.podspec with deprecated_in_favor_of set

### ISSUE THREAD

**Issue by Adlai-Holler** [TextureGroup/Texture#444]
Cocoapods lets you use `spec.deprecated_in_favor_of = 'Texture'` to point users to a new pod. We should issue another AsyncDisplayKit pod with that option set. cc @garrettmoon @maicki @nguyenhuy @appleguy

**Comment by nguyenhuy** [comment]
Who is the author of the old pod?

**Comment by maicki** [comment]
I think no one of us has any permissions anymore. I think we have to reach out to people that still have.

**Comment by Adlai-Holler** [comment]
This flag is already in AsyncDisplayKit 2.2.1.podspec
