### ISSUE TITLE
[ASCollectionView] Consider if animated layout invalidation should be done without batch updates.

### ISSUE THREAD

**Issue by appleguy** [TextureGroup/Texture#448]
This approach is probably more efficient, and might also be safer for data access timing.

```
    case ASCollectionViewInvalidationStyleWithAnimation:
      if (0 == _superBatchUpdateCount) {
        [UIView animateWithDuration:0.3 animations:^{
          [self.collectionViewLayout invalidateLayout];
        }];
      }
      break;
```

The original / current code is:
```
    case ASCollectionViewInvalidationStyleWithAnimation:
      if (0 == _superBatchUpdateCount) {
        [self _superPerformBatchUpdates:^{ } completion:nil];
      }
      break;
```

**Comment by Adlai-Holler** [comment]
Is this working in your testing? If so I absolutely support it 💯. I could have sworn that UICV didn't used to support that behavior but that was probably 4 years ago.

**Comment by appleguy** [comment]
Hmm, I think the issue here is that the animation is a bit different. With batch updates it seems to crossfade without stretching, but with this it seems to stretch the cell height while animating. I'm not sure which is supposed to happen, but for now let's leave this unchanged.

**Comment by Leonif** [comment]
Hi, I m not sure that I m in right branch, however may be you help me. I have collection view and I click on cell node, then I remove all cell nodes exclude one and versa verse. But interface during this operation jumps from one side to another
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/22885814/31760014-f184cfa6-b4bb-11e7-906c-0e781b589603.gif)

Could you give some tips?

thank you
