### ISSUE TITLE
Scrolling ASTableView cannot decelerate when touching the screen

### ISSUE THREAD

**Issue by Bayonetta** [TextureGroup/Texture#453]
Thanks for your amazing library, after using Texture, it has a big advance about our app's user experience.

But after updating to the newest version, we have found it's hard to manipulate our tableview. We must touch the screen for twice or more chances to decelerate the scrolling tableview.

Why will it happen? And you should know the older 1.0's version doesn't have this question.

**Comment by EviluS** [comment]
@Bayonetta Can you please provide more explanation to your issue. No problems occurred to me while scrolling through on of our projects' `ASTableNodes`.

**Comment by noppefoxwolf** [comment]
Perhaps I met the same problem.
Sometimes it is impossible to scroll in the reverse direction immediately after starting scrolling in a very short period of time.

**Comment by Bayonetta** [comment]
Hello, @EviluS 

I have write a demo for our app, you will run it to check this problem.

It's hard to control it, if you scroll the scrollview very quickly, it will be responsed for only 1 or 2 times.


And I found when I comments the line 173 and the following 3 lines in [WOWeiboStatusNode2.m] class file, the tableview will become normal.

![image](https://user-images.githubusercontent.com/3266065/33819538-f7abf546-de85-11e7-99b7-1ea7ff7e0537.png)

**Comment by EviluS** [comment]
@Bayonetta I'll check it later when I have time.

**Comment by Kofktu** [comment]
@Bayonetta
have you resolved this issue?, I have the same issue now.
'WOWeiboStatusNode2.m' file can not be found in Texture 2.7 version

**Comment by Bayonetta** [comment]
Hi @Kofktu 

'WOWeiboStatusNode2.m' file is my demo's file, not the including files in Texture Framework.

I've resolved this issue yet, but only deleted the 'translateNode" showed in the upper pic. It's our customized node, and I don't know why it can affact the interaction of tablenode. It has been confused me up till now.

Maybe you can also delete some your customized nodes or change your layouts's position to try.

**Comment by nguyenhuy** [comment]
Please feel free to reopen if you still have this issue. Thank you.

**Comment by strangeliu** [comment]
@Bayonetta Have you solved this problem? any updates?
