### ISSUE TITLE
Naming conflict with YYText

### ISSUE THREAD

**Issue by zyvv** [TextureGroup/Texture#458]
`sharedDebugSetFunction(const void *value, void *context)` this fuction, in `ASTextDebugOption`

**Comment by MarvinShawn** [comment]
just change the func name

**Comment by nguyenhuy** [comment]
cc @Adlai-Holler

**Comment by notePads** [comment]
platform :ios, '8.0'
use_frameworks! #here

target 'name' do
    pod 'Texture'
    pod 'YYKit'
end

**Comment by nguyenhuy** [comment]
I think it's fine to change the name of this function in Texture. Would any of you submit a quick PR for this? Thanks!

**Comment by maicki** [comment]
Just created the PR linked in here to fix this issue. I also saw there are issues open on the YYText repo for it.
