### ISSUE TITLE
The cell in ASTableNode never dealloc, when number of cells increase, the memory increases all the time

### ISSUE THREAD

**Issue by vikas-singla** [TextureGroup/Texture#461]
Referring to ASDKGram sample app, the cells are never removed from memory. The memory footprint keeps increasing. Checked in release 2.3.4

**Comment by Adlai-Holler** [comment]
The cell nodes are meant to stay alive until the rows are deleted or the table node is deallocated. The contents of their CALayers, which take up the vast majority of their memory, are discarded when the cells are out of the "display range" to conserve memory.

Are you seeing a major ramp of memory usage in ASDKgram?

**Comment by vikas-singla** [comment]
Yes, I'm seeing memory increase continuously when scrolling. I've scrolled more than 100 pages and I'm not seeing ASNetworkImageNode free up memory.

**Comment by Adlai-Holler** [comment]
How steep is the memory ramp? Again, nodes are intended to survive until they are deleted so the nodes themselves wont be reclaimed. At 100 pages of scrolling, how was the memory consumption and what was your test environment like?

**Comment by zly880** [comment]
I use instrument，I push a newView then I pop . I find the cell was released，but the memory is alaways retain. I find that no retain cycle. I use so much ASNetworkImageNode. Maybe the cache no release ? @Adlai-Holler

**Comment by nicolettemanas** [comment]
Hi, I tried running `ASDKgram` and the memory is already at around 80MB when I have only scrolled for 500 cells. Do nodes consume this much memory? 

Tested it with iPhone6s, 10.1.1. XCode9-beta6
![screen shot 2017-09-08 at 4 12 49 pm](https://user-images.githubusercontent.com/3390967/30203383-84ba6b00-94b4-11e7-93f0-1b2eb1ebc738.png)

**Comment by tqtifnypmb** [comment]
I met the same issue. The number of cells created is not equal to the number of cells destroyed. Some cells are left dangle

**Comment by nguyenhuy** [comment]
@zly880 It's normal for memory consumption to ramp up and then stabilize. Since nodes are not reused, it's generally true that collection and table nodes use more memory than UICollectionView/UITableView. However, that shouldn't cause out-of-memory crashes since node instances themselves, excluding their contents, don't consume much memory. cc #417.
