### ISSUE TITLE
ASNetworkImageNode flashing problem

### ISSUE THREAD

**Issue by qqppooqq** [TextureGroup/Texture#477]
### Problem
My problem occurs when the TabBar is switched, and when you switch to an ASNetworkImageNode as the background controller, the ASNetworkImageNode will appear blinking when I set the background color to be more noticeable and easier to snap the eye.

### View hierarchy:
ASTabBarController subClass -> CCTintNavigationController subClass -> ASViewController subClass -> node -> ASNetworkImageNode

### Code

```
- (ASNetworkImageNode *)backgroundBlurNode {
    if (!_backgroundBlurNode) {
        ASNetworkImageNode *i = [ASNetworkImageNode new];
        i.backgroundColor = [UIColor redColor];
        i.defaultImage = [UIImage as_imageNamed:@"user_icon_placeholder"];
        [i setImageModificationBlock:^ UIImage *(UIImage *originImage) {
            return [originImage imageByBlurLight];
        }];
        i.layerBacked = YES;
        [self addSubnode:i];
        _backgroundBlurNode = i;
    }
    return _backgroundBlurNode;
}
```

### Investigation
1. The -layoutSpecThatFits side of the parent node of ASNetworkImageNode: The method does not call repeatedly
2. ASNetworkImageNode internal setXxx: methods are breakpoint intercept, but did not repeat the implementation

> So, What should I do???

**Comment by qqppooqq** [comment]
Problem code
[AboutNetworkImageNode.zip](https://github.com/TextureGroup/Texture/files/1179115/AboutNetworkImageNode.zip)

**Comment by EviluS** [comment]
@qqppooqq Actually this is caused by the change between the `defaultImage` and the image loaded from the `URL` and is not a "real problem". But there is a solution :). One thing you can do is use the `placeholderFadeDuration`

```
_backgroundNode.placeholderEnabled = YES;
_backgroundNode.placeholderColor = [UIColor whiteColor];
_backgroundNode.placeholderFadeDuration = 0.3;
```

**Comment by qqppooqq** [comment]
@EviluS Thank you
For me, this is really a problem. I tried the program you mentioned
But it's actually when the placeholderFadeDuration is small enough to flicker still exists while i really do not need a gradient effect
Also try to subclass ASNetworkImageNode, rewrite `- placeholderImage` still can not be resolved, will be in the bitmap and request between the flashing
Do you have to use UIImageView?

**Comment by EviluS** [comment]
@qqppooqq One other thing you can try is to adopt `ASNetworkImageNodeDelegate` and override `- (void)imageNode:(ASNetworkImageNode *)imageNode didLoadImage:(UIImage *)image` method. And after that you can try and delay the loading of the image. 

Another thing I can think of is to add one more `ASNetworkImageNode` (on top of your current imageNode) which will only load the image from the `URL` and will not show any placeholders and defaultImages.

**Comment by seekcx** [comment]
@EviluS Hi, Why not solve this problem completely?
