### ISSUE TITLE
Question/Bug: 'didLoad' is not called on <ASCellNode>‘s subclass

### ISSUE THREAD

**Issue by oferRounds** [TextureGroup/Texture#478]
Hi, I have a node which is an `ASCellNode`‘s subclass, which is used by my `ASCollectionNode`. 

Now, on my `ASCollectionNode`'s data source, when I use `collectionNode:nodeForItemAtIndexPath:` then `didLoad` on the `ASCellNode`‘s subclass gets called. But when I switch to `collectionNode:nodeBlockForItemAtIndexPath:` it does not get called. 

Any idea what might caused this behaviour?

**Comment by oferRounds** [comment]
Sorry, re-run it, not I see that it’s not get called also when using `collectionNode:nodeForItemAtIndexPath:`.

**Comment by oferRounds** [comment]
After more debugging I found that when I implemented `ASCollectionNode` delegate method `-collectionNode:constrainedSizeForItemAtIndexPath:`, the cell’s `didLoad` does get called.
(when it was not implemented the cells where still layouted correctly.)

I still get a strange(?) behavior where the cell’s `layoutSpecThatFits` is called before `didLoad`.

**Comment by EviluS** [comment]
@oferRounds Hey here is a good read about subclassing `ASDisplayNode` - [Subclassing Docs](http://texturegroup.org/docs/subclassing.html)

Basically `didLoad` will be called on the main thread once the node is loaded and inside it you can perform all operations which are not thread safe. Lets say `didLoad` will be called once the `node` is physically there, its `view` is created.

For debugging purposes and self teaching :) you can try to call `.view` or `.layer` inside an `init` method.

Quick example - lets say we have a `node` in which we have an `ASTableNode`. The `ASTableNode` has an `ASTableView` inside. So once `didLoad` get called for our `node` you can safely set all `.view` related properties of the `ASTableNode` like `.separatorStyle`.

As for the `layoutSpecThatFits` there is nothing strange it get called before `didLoad`.

**Comment by oferRounds** [comment]
@EviluS Hey! I Thanks for this comment!
I have actually read this section. 

I understand what you’re saying `layoutSpecThatFits` which gets called before `didLoad` — got you — but my main issue was the fact that **`didLoad` was not called at all**, although the cell still appeared.

As I mentioned on my previous comment, implementing `ASCollectionNode`’s delegate method `collectionNode:constrainedSizeForItemAtIndexPath:` fixed this, but I’m not sure why, and if that is a but or not.

**Comment by EviluS** [comment]
@oferRounds Hm this is really strange, what version of ASDK you use and can you share your affected code.

**Comment by oferRounds** [comment]
@EviluS I use `2.3.4`. I’ll try to export the relevant code out to a gist. We’ll add it here a bit later.

**Comment by oferRounds** [comment]
@EviluS so the 3 main files are:

- [`ActivitiesViewController`](https://gist.github.com/oferRounds/8a2bbabb5792981a99e56cb957cc57c4), which is in charge of presenting the a `CollectionNode`, which actually functions as a `TableNode` (favored it because of the support of headers). 

- [`ActivitiesViewControllerDataSource.m`](https://gist.github.com/oferRounds/250c69c0091e108c06db0e44d1594791), which functions as the data source of the collection node

- [`ActivitiesTableCellNode.m`](https://gist.github.com/oferRounds/8d409f34c1454199cf5a3d42a5127318
), which is the Collection’s cell. It’s itself presents another collection node (horizontal flow) of scrollable items

Please note that in the implementation here, `didLoad` does get called, as it includes the implementation of `collectionNode:constrainedSizeForItemAtIndexPath:`. If removed, `didLoad` will not be called.

Hope this helps... Thanks!!!

**Comment by EviluS** [comment]
@oferRounds Your logic looks similar to the `HorizontalWithinVerticalScrolling` example which I modified to use `ASCollectionNode` instead of `ASTableNode`. But `didLoad` still got called event with no `.itemSize` set for the `UICollectionViewFlowLayout` , no `- (ASSizeRange)collectionNode:(ASCollectionNode *)collectionNode constrainedSizeForItemAtIndexPath:(NSIndexPath *)indexPath` implementation and also test with `CGSizeZero`.

In your `didLoad` override there is a call `[self addCollectionNode];`. Does your horizontal collection gets created because you said that your cell still appears?

**Comment by oferRounds** [comment]
Hey @EviluS, thanks for looking on this!

As with the original example `HorizontalWithinVerticalScrolling`, the creation of my collectionNode was originally done on the `init` method. It all started when I wanted to move it to `didLoad` — in order to use the CollectionNode’s aSync cell creation, and as the initialaztion of `UICollectionViewFlowLayout` must done on the main thread  — when I noticed that the `didLoad` is not called.

But as for your question and as I mentioned, my horizontal collection still appeared on screen.

**Comment by oferRounds** [comment]
I also checked what you checked, and `didLoad` does get called on `HorizontalWithinVerticalScrolling`. So for sure something is done differently on my project, and could be my “fault”, I’m just not sure what it is...

**Comment by EviluS** [comment]
Probably a stupid question but did you try cleaning the project maybe it is a debugger issue or something?

**Comment by oferRounds** [comment]
Hhhm, nice idea... I haven‘t. Will try!

**Comment by oferRounds** [comment]
So, not sure, it’s not get reproduced... Very mysterious... I’ll close it for now, and will update in case I see it again. @EviluS — thanks for looking into this!

**Comment by jeffersonsetiawan** [comment]
I've experience this issue before in my code, and turns out it didn't called the `didLoad` because in layoutSpecThatFits, it return the node without size (or in my case `ASLayoutSpec()`), and I saw your code, can you try remove this
```
if (_collectionNode == nil) {
        return [ASLayoutSpec new];
    }
```
or return a dummyNode with explicit size
