### ISSUE TITLE
Proposal: rename `-[ASCellNode nodeViewModel]` to `nodeModel`

### ISSUE THREAD

**Issue by mlilek-nyt** [TextureGroup/Texture#501]
#499 renamed `ASCellNode`'s `viewModel` property to `nodeViewModel` to avoid collisions with view model implementations on top of the framework.

It was brought up on slack that "view" terminology should be avoided to not cause confusion with the node's `view` property.

I'm proposing renaming this again to `nodeModel`. You have a `ViewModel` on a `View`, it seems reasonable for folks to understand on a `Node` you have a `NodeModel`.

Thoughts?

**Comment by nguyenhuy** [comment]
Renamed to `nodeModel` in #504. Thanks for opening up the discussion!
