### ISSUE TITLE
Card like layout for tablenode cell

### ISSUE THREAD

**Issue by iOSUser110** [TextureGroup/Texture#51]
I want to tableview node as card style view , 
I tried it by putting back view to each cell and on that back view put all the data by using overlay function. But it is not working as expected.
Using storyboard it is very easy but I want to stuck to texture framework.
I spend almost 1 day on this. Still not getting solution
Can anybody help me. I need this in urgent basis so ..

If you can provide any sample code  snippet

**Comment by EviluS** [comment]
Can you provide a screenshot or a sketch of the layout you want to achieve?

**Comment by iOSUser110** [comment]
Yes, I want the same as below screenshot 

![cardview](https://cloud.githubusercontent.com/assets/2657399/25279788/41be899c-26c5-11e7-83b8-0896b6ef731e.png)

**Comment by Adlai-Holler** [comment]
@iOSUser110 Hi, the core team can't field questions like that here on the repo. Please ask the folks on the #general channel of [Texture Slack](http://texturegroup.org/slack.html) or post on StackOverflow to get help. Cheers!
