### ISSUE TITLE
[ASPagerNode] Calling currentPageIndex on background thread

### ISSUE THREAD

**Issue by maicki** [TextureGroup/Texture#519]
As we use the `contentOffset` of a `UIScrollView` in `currentPageIndex` it should only be used from the main thread based:

<img width="989" alt="screen shot 2017-08-18 at 9 30 34 am" src="https://user-images.githubusercontent.com/25288/29468194-22416432-83f8-11e7-9d93-19da46588d17.png">

**Comment by nguyenhuy** [comment]
Hey @maicki, what is the call site of this problem? ASCollectionNode has a contentOffset bridged property now and we should switch to it. However, if the node is loaded, we still reach out to the view and triggers the Main-Thread Checker if it's on a background thread. Later on when we make ASCollectionNode framework private, we can make thread-safe versions of some of these properties and rely on them instead.

**Comment by maicki** [comment]
Closing as we should rely on the call site of it
