### ISSUE TITLE
[Question] How to disable LOG on version 2.4?

### ISSUE THREAD

**Issue by jadsonlourenco** [TextureGroup/Texture#524]
Hi guys, after upgrade to **2.4** version my console is sowing some informations about ASDisplayNodes render, how to disable it (in swift)?

**Comment by dangnguyenhuu** [comment]
same issue, after update to 2.4 Console shows extra logging

**Comment by nguyenhuy** [comment]
@jadsonlourenco, @dangnguyenhuu: Sorry about that! #526 should make it right!

**Comment by Adlai-Holler** [comment]
What is the density of the logging? The default debug log level is intended to be light enough not to annoy most developers, and it should only include these high-level events:

- Warning
- View controller will appear
- ASTabBarController tab switch, ASNavigationController push/pop
- View controller trait collection change
- Animated layout transition
- Collection node batch fetch
- Collection node update

*How to disable it* To disable all logging, the define the macro `ASEnableLogs=0` for Texture (or, for one-off disabling, you can change the line at the top of `ASLog.h`).

*I hear you* I understand why some developers don't want any logs from our framework at all, and why they don't feel they should have to define a macro to explicitly suppress it. That's totally reasonable.

*Why it is there* I believe that the majority of users aren't annoyed by it. I also believe that an appropriate amount of default debug logging makes the framework much more transparent and usable, especially for users who are starting off and may not be experienced enough to know where to look to enable logging.

*How to improve the situation* I'll create a runtime method to suppress all logs at all levels. That way it's easier to suppress the messages.

**Comment by sunlight2728** [comment]
ASDisableLogging();
