### ISSUE TITLE
I am trying to load the network picture when the error reported

### ISSUE THREAD

**Issue by CHENDONGY** [TextureGroup/Texture#550]
##### My picture is upgraded using https, using Texture when the picture does not load out. How do I need to be configured to load the image correctly?

_https used a self-signed certificate_

_error_
```
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)
```

**Comment by hannahmbanana** [comment]
This is a duplicate of https://github.com/pinterest/PINRemoteImage/issues/405 and should be closed.
