### ISSUE TITLE
Attributed versions of accessibility elements

### ISSUE THREAD

**Issue by fruitcoder** [TextureGroup/Texture#551]
I wanted to know whether you plan on adding the attributed versions of `accessibilityLabel`, `accessibilityHint` and `accessibilityValue`. While there are other additions to A11y (drag and drop for example), these are the most important for me, since some of my text fragments sound weird if they aren't in the correct language. 
If I can add them as a PR, tell me where to start. So far I see changes in:
```
Source/Details/_ASDisplayViewAccessiblity.h
Source/Details/_ASDisplayViewAccessiblity.mm
Source/Private/ASDisplayNode+UIViewBridge.mm
Source/Private/_ASPendingState.mm
Source/Details/UIView+ASConvenience.h
Source/Private/ASDisplayNodeInternal.h
Source/ASDisplayNode.h
```
And maybe some test would need to be updated

**Comment by maicki** [comment]
@fruitcoder We don't have any specific plans yet, but we would be happy for any PR for adding them. Thanks!

**Comment by fruitcoder** [comment]
Okay, this would be an initial version of it #554
