### ISSUE TITLE
ASCollectionNode Doesn't Display All Possible Cell Nodes

### ISSUE THREAD

**Issue by b3ll** [TextureGroup/Texture#572]
I have a pretty simple collection node, configured to use a UICollectionViewFlowLayout configured as such: 

```swift
let flowLayout = UICollectionViewFlowLayout()
flowLayout.scrollDirection = .horizontal
flowLayout.minimumLineSpacing = 0.0
flowLayout.minimumInteritemSpacing = 0.0
```  

I then dynamically provide sizes for each of the cells to create a grid:

```swift
func collectionNode(_ collectionNode: ASCollectionNode, constrainedSizeForItemAt indexPath: IndexPath) -> ASSizeRange {
  let bounds = view.bounds
  var width = indexPath.row % 2 == 0 ? floor(bounds.size.width / 2.0) : round(bounds.size.width / 2.0)
  let height = floor(bounds.size.height / 3.0)

  if indexPath.row == 5 {
    width = floor(width / 2.0)
  } else if indexPath.row == 6 {
    width = round(width / 2.0) // floor could be used here as well, it makes no difference.
  }

  return ASSizeRangeMake(CGSize(width: width, height: height))
}
```

However, for some reason, when supplied with 7 items to display (via the data source in a single section) the 7th cell (at index 6) does not get displayed. It's not in the view hierarchy at all (even though it would fit). If I supply vertical as the scroll direction, everything works as expected.

Any ideas what's up?

This is all being done on an iPad Pro (btw).

**Comment by hannahmbanana** [comment]
@b3ll - Is it possible that the frame of the collection is not as wide as it should be? Apart from an issue with the frame of the collection or the layout code inside the ASCellNodes (e.g. reporting a 0,0 size) we haven't heard of any bugs in this area. 

If you could provide an example project showing this and a dump of the view hierarchy, I could take a closer look.

**Comment by b3ll** [comment]
Hm I think my layout code was wrong, it seems to work fine now. I think my collection view layout was returning out of bounds frames
