### ISSUE TITLE
I want to know how to load a GIF image using ASImageNode.

### ISSUE THREAD

**Issue by wCodeQ** [TextureGroup/Texture#573]
My project is Swift, and when I want to use the ASPIN class in the AS library, it will be incorrectly reported and cannot be used. How do I configure the project? If you directly use the PINAnimatedImage in the PIN library, how will the ASAnimatedImageProtocol protocol be implemented?

**Comment by qqppooqq** [comment]
http://texturegroup.org/docs/network-image-node.html
search 'GIF Support', did you try this?

**Comment by qqppooqq** [comment]
I tried ASNetworkImageNode loading remote gif was successful
But loading the local gif failed

**Comment by qqppooqq** [comment]
Haha.  I found it
`node.animatedImage = [[PINAnimatedImage alloc] initWithAnimatedImageData:[NSData dataWithContentsOfURL:[[NSBundle mainBundle] URLForResource:@"timg.gif" withExtension:nil]]];`

**Comment by wCodeQ** [comment]
My project is Swift, and when I want to use the ASPIN class in the AS library, it will be incorrectly reported and cannot be used. How do I configure the project? If you directly use the PINAnimatedImage in the PIN library, how will the ASAnimatedImageProtocol protocol be implemented?

**Comment by garrettmoon** [comment]
Going to close this since y'all figured it out :)

**Comment by SolorzanoJose** [comment]
@garrettmoon this initializer no longer exists, what is the current approach to achieve the same result? i.e. local gifs can't be loaded into any type of texture node

**Comment by rafaelc0sta** [comment]
@SolorzanoJose @garrettmoon Now there's PINCachedAnimatedImage, but it doesn't seem to conform to ASAnimatedImageProtocol. Trying to figure it out, will update comment if I do.

**Comment by alisamaiee** [comment]
Any workaround?

**Comment by alisamaiee** [comment]
> Any workaround?

Found the solution.
Now you can use `ASPINRemoteImageDownloader.shared().animatedImage(with: yourAnimatedImageData)` instead.
