### ISSUE TITLE
IOS 11 ASTableNode Freeze problems - see video

### ISSUE THREAD

**Issue by boardmain** [TextureGroup/Texture#578]
Hi i have updated to ios 11 but i have a problem with ASTableNode
when new content is added in ios11 the table freeze
you can see in the video the same app in ios 10.3 and in ios 11

others with same problem?

VIDEO:

[https://youtu.be/mCGEfI4Dgys](https://youtu.be/mCGEfI4Dgys)

**Comment by notePads** [comment]
Me too.

**Comment by steewsc** [comment]
Me too, except it scrolls to top (at first) after each batch is added and later, when there are more rows, it just jumps up towards to top.
Not sure if this could help:
https://github.com/TextureGroup/Texture/pull/485
(I'll try it later and post an update)

**Comment by notePads** [comment]
@steewsc Thank you, just solved the problem.

**Comment by tqtifnypmb** [comment]
Me too.

**Comment by EviluS** [comment]
Same problem here.

**Comment by nguyenhuy** [comment]
Could any of you confirm that #485 solves this issue? If not, what are the reproducible steps?

**Comment by EviluS** [comment]
@nguyenhuy Sorry I posted before checking #485 which eliminates the problem.

**Comment by nguyenhuy** [comment]
Great! I'm gonna close this issue but feel free to reopen if you encounter this problem in the latest release (v2.5).
