### ISSUE TITLE
[UIScrollView setDelegate] called off main thread in ASEditableTextNode's dealloc

### ISSUE THREAD

**Issue by shamanskyh** [TextureGroup/Texture#586]
I'm noticing that iOS 11's main thread checker is catching an issue in ASEditableTextNode's dealloc method where we're trying to set a UIScrollView's delegate off the main thread.
<img width="857" alt="screen shot 2017-09-26 at 2 39 41 pm" src="https://user-images.githubusercontent.com/2146675/30885566-9b261048-a2c8-11e7-9165-3277c792ecc3.png">

@maicki said it'd be best to file as an issue, but let me know if there's anything I can do to help fix. Thanks!

**Comment by maicki** [comment]
I'm already actively investigate and first PR's landed around this area yesterday.

**Comment by maicki** [comment]
I just opened two PR's to two ways we could go with this issue. Happy for any feedback.

**Comment by maicki** [comment]
Fixed in #598
