### ISSUE TITLE
Reloading of table view causes crash

### ISSUE THREAD

**Issue by xilin** [TextureGroup/Texture#594]
I'm using Texture@v2.4 on my last release.

Please see the report [here](http://crashes.to/s/256ef077d06), which says:
`processing delete for section (-1) when there are only 0 rows in the table view before the update`

I'm not sure what kind of operation can make this crash happen since it happened in call of `ASMainSerialQueue`.

 Do you have any suggestions on when the section value can be -1?

**Comment by remirobert** [comment]
Have you changed your data used by dataSource?
I have this kind of errors when I change it.

**Comment by xilin** [comment]
@remirobert Yes, I changed my data. However, I've make sure the data was changed in main thread. Is it still a problem if I change data after call of `reloadData` or `reloadSection`?

**Comment by nguyenhuy** [comment]
I'm gonna close this issue. If this is still a problem for you, please feel free to reopen and provide a test project.

**Comment by xilin** [comment]
So for not updating the issue status.
In the end I found out there are some cases that the section index to reload is mis-calculated.
I've added checking to make sure the section index to reload is valid and the crash never happened.
