### ISSUE TITLE
Setting ASCellNode selectedBackgroundView doesn't work under iOS 11

### ISSUE THREAD

**Issue by ay8s** [TextureGroup/Texture#600]
When setting a ASCellNode's selectedBackgroundView in didLoad the view displays correctly on touch down in iOS 10 but has no effect in iOS 11, where it shows a default grey background.

**Comment by 3a4oT** [comment]
Hey @ay8s!  you can try to override getter and it should do the trick.
```swift
	public override var selectedBackgroundView: UIView? {
		get {
			let bgV: UIView = UIView()
			bgV.backgroundColor = UIColor.red
			return bgV
		}
		set {}
	}
```
