### ISSUE TITLE
duplicate symbol __sharedDebugSetFunction

### ISSUE THREAD

**Issue by newyjp** [TextureGroup/Texture#615]
## duplicate symbol __sharedDebugSetFunction in:
```objective-c
Objective-C:
   
   .../Build/Products/Debug-iphonesimulator/Texture/libTexture.a(ASTextDebugOption.o)
   .../Build/Products/Debug-iphonesimulator/YYText/libYYText.a(YYTextDebugOption.o)
```

ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by PrideChung** [comment]
Hi, 

Looks like Texture copied some C functions from another repo "YYText" and didn't prefix those functions. We happen to using both of them thus result in duplicate symbol error. Would you like to accept a pull request for this particular problem?

**Comment by maicki** [comment]
That should be fixed on master: https://github.com/TextureGroup/Texture/pull/623 I don't think we released a new version with it though

**Comment by nguyenhuy** [comment]
I'm closing this issue. Please pull in the change in #623 until it's bundled in a release. Thank you!
