### ISSUE TITLE
Update implementation of support for attributed accessibility properties

### ISSUE THREAD

**Issue by nguyenhuy** [TextureGroup/Texture#636]
We're planning for the next major release (2.6) to require Xcode 9. As such, we should do a follow-up on #554 and migrate to Xcode-9-compatible code. @fruitcoder Would you be able to take on this?

**Comment by fruitcoder** [comment]
Sure! Will this happen on a special branch?

**Comment by nguyenhuy** [comment]
We'll do it on master. Thanks for volunteering!

**Comment by fruitcoder** [comment]
#642

**Comment by nguyenhuy** [comment]
Resolved in #650.
