### ISSUE TITLE
ASCollectionNode hangs the whole app when there are multiple 'performBatchUpdates' or 'reloadData' runs simultaneously

### ISSUE THREAD

**Issue by fans3210** [TextureGroup/Texture#641]
Thanks for the amazing framework. We have built an xmpp based chat app using Texture several months ago. The app ran pretty well until recently we found a hidden bug. 

We used ASCollectionView for the chatting page. The app always hang when the user is at the Chatting page and there are more than 2 or 3 messages come in at exactly the same time. Normally we won't face such issue for one-to-one chat since there is always a delay for each batch update. But when the app awakes from background and there are many messages to be handled, the nightmare would come.

What I found is that:  The app always hang when we tried to do several 'reloadData' or 'performBatchUpdates' without too much delay, which means, if a batch update or reloadData starts when another same operation hasn't finished, the app might hang. I would be very appreciated if you could give me some help. Many thanks!

**Comment by fans3210** [comment]
Hi guys any update?
I tried https://gist.github.com/fans3210/14f488457e488d09f24ec512d4feaaea but this didn't resolve the prob
 Currently I'm using a timer to resolve this.

**Comment by fans3210** [comment]
Sorry after investigation, it's becuase of one line of my code in nodeblock creation, I used dispatch.main.sync which caused the deadlock

**Comment by nguyenhuy** [comment]
Glad you figured that out. Cheers!
