### ISSUE TITLE
Assertion failure in -[ASTextKitComponents dealloc]

### ISSUE THREAD

**Issue by Z-JaDe** [TextureGroup/Texture#646]
![image](https://user-images.githubusercontent.com/12668657/32133028-267baa7e-bb95-11e7-84ba-d3488642b62f.png)
![image](https://user-images.githubusercontent.com/12668657/32133036-7462e360-bb95-11e7-9d5e-15e6f1e115c9.png)
Texture  2.5.1
When I quit the interface, sometimes the crash, sometimes normal

**Comment by Jorgiss** [comment]
Have same issue

**Comment by nguyenhuy** [comment]
D

**Comment by nguyenhuy** [comment]
Duplicated with #607.
