### ISSUE TITLE
[RFC][ASDisplayNode] Provide easy access to safe area insets

### ISSUE THREAD

**Issue by ypogribnyi** [TextureGroup/Texture#658]
The safe area is really important for support of iPhone X screen. Having easy access to it would also be handy when designing for the classic iPhones to make sure the content is not obscured by the translucent navigation bars and toolbars.

These insets are currently available via some workarounds, but as a user, I'd like `ASDisplayNode` to have the `safeAreaInsets` property and the `- (void)safeAreaInsetsDidChange` callback. On iOS 11 they can be simply bridged from the underlying view. And it would be great to have a backward compatible calculation algorithm for older iOS versions (they can be derived from view controller's top and bottom layout guides).

I think that `automaticallyRelayoutOnSafeAreaChanges` property would be very handy too.

It would also be nice to have the `layoutMargins` and related properties on `ASDisplayNode`, but I'm not sure how many people really need them.

**Comment by fruitcoder** [comment]
Accessing the underlying views `safeAreaInsets` and being informed when the insets changed seems very reasonable for `ASDisplayNode` subclasses (especially returning `ASLayoutSpec`s depending on those values). It might be hard to sync those properties if you have a layer tree and the views are only created for accessing the `safeAreaInsets`. 
It might also be possible to put them in the `ASTraitCollection` and react to `asyncTraitCollectionDidChange()` although that would be quite different from `UIKit`.

**Comment by ay8s** [comment]
Think this can be closed 👍
