### ISSUE TITLE
[ASNetworkImageNode] Crash due to calls to ASImageDownloaderProtocol with nil URL

### ISSUE THREAD

**Issue by flovouin** [TextureGroup/Texture#683]
Hi guys,

A few months ago, I was experiencing some (Swift) bridging crashes due to the `ASNetworkImageNode` calling `ASImageDownloaderProtocol` methods with a `nil` URL. At the time, I had put up [a PR that solved the problem](https://github.com/facebookarchive/AsyncDisplayKit/pull/3190).

It seems that recent improvements to the `ASNetworkImageNode` have changed the way it calls the `ASImageDownloaderProtocol`, and I'm getting a new bridging crash on [this line](https://github.com/TextureGroup/Texture/blob/b2539d353179c3505a3f5382fb3305463d896c50/Source/ASNetworkImageNode.mm#L601). I haven't tried reproducing the bug in a sample project yet, but `[urls lastObject]` can clearly be `nil` if `urls` is empty, whereas `downloadImageWithURL` expects a `nonnull` URL.

Because I haven't kept up with the latest improvements in the `ASNetworkImageNode`, I don't feel confident submitting a PR myself, maybe @garrettmoon could help here?

Tell me if you need anything else.

Cheers,
Flo

**Comment by garrettmoon** [comment]
@flovouin I think https://github.com/TextureGroup/Texture/pull/699 should fix this.
