### ISSUE TITLE
layout Infinite loop

### ISSUE THREAD

**Issue by Z-JaDe** [TextureGroup/Texture#686]
When I listen to KeyboardWillChangeFrame,
I call：
self.style.height = 44 + keyboardHeight
setNeedsLayout()
layoutIfNeeded()
The memory keeps getting bigger and keeps calling layoutSpecThatFits

![image](https://user-images.githubusercontent.com/12668657/33226825-eb7c2d0c-d1d0-11e7-976e-cd0df95c515a.png)

![image](https://user-images.githubusercontent.com/12668657/33226842-1869b046-d1d1-11e7-9f79-5ef96061af48.png)

**Comment by nguyenhuy** [comment]
Hi, it seems to be an issue in your code, specifically `configObserver()` and/or `layoutSpecThatFits(:)` of `ChatToolBarNode`.

Please feel free to re-open this ticket with more information if need to. Thank you.
