### ISSUE TITLE
We got some crashes: "ASDN::Mutex::~Mutex()"

### ISSUE THREAD

**Issue by wangyutao0424** [TextureGroup/Texture#688]
I found some crashes on my platform of crash report, it only appear on iOS 11.
2.5 version we used.

![image](https://user-images.githubusercontent.com/4385589/33236846-6a9a2826-d29b-11e7-95ca-2884d6e7c70b.png)

**Comment by anuragt84** [comment]
We see this crash as well. For us, it is probably happening when the app is being force quit.

**Comment by nguyenhuy** [comment]
https://github.com/TextureGroup/Texture/pull/577 fixed a similar crash. Please update to 2.5.1 and let us know if you still see it.
