### ISSUE TITLE
ASTextNode inside ASCellNode - touch go through if not clicking on a link

### ISSUE THREAD

**Issue by xyxabcdiy** [TextureGroup/Texture#712]
I'm trying to detect link in ASTextNode that is a subnodes of ASCellNode. 

The only thing is, I need the UITextNode's links to be clickable, so I set the delegate, unfortunately this will prevent any touch going through to the ASTextNode.

The only thing I need, is detecting that if a user touch the ASTextNode, check if it was a link, if it is then opening the link, otherwise redirect the touch on the ASCellNode.

any idea how can this be done ?

much like the twitter App (we can either click on the row, or on the link...)

**Comment by ArmandsB** [comment]
Use this property on ASTextNode.

`/**
 @abstract if YES will not intercept touches for non-link areas of the text. Default is NO.
 */
@property (nonatomic, assign) BOOL passthroughNonlinkTouches;`

**Comment by xyxabcdiy** [comment]
@ArmandsB  Thank for your help, it did work for me!
