### ISSUE TITLE
Allow logs to be re-enabled at runtime

### ISSUE THREAD

**Issue by johntmcintosh** [TextureGroup/Texture#715]
In most of my apps, I like to expose a menu in debug builds which allows me to toggle logs of certain types on/off at runtime. With the current disable function only, we're able to turn logs off, but we cannot re-enable them without re-launching the build.

I just created PR #714 with a proposed new `ASEnableLogging()` function that adds support for enabling logs that have previously been disabled by calling `ASDisableLogging()`. 

Please let me know what you think about this approach, or if you have any suggestions for a better way to enable this behavior.

Thanks!

**Comment by john-mcintosh-dosh** [comment]
Resolved in PR #714. Please feel free to close out this ticket now.

**Comment by johntmcintosh** [comment]
Resolved in PR #714. Please feel free to close out this ticket.
