### ISSUE TITLE
We got some crash on iOS 8

### ISSUE THREAD

**Issue by wangyutao0424** [TextureGroup/Texture#716]
![image](https://user-images.githubusercontent.com/4385589/33986685-4ca9f320-e0f9-11e7-8357-2293d5c72e68.png)

```
- (ASCellNodeBlock)collectionNode:(ASCollectionNode *)collectionNode nodeBlockForItemAtIndexPath:(NSIndexPath *)indexPath {
    return ^{
        GCHpAssetsCell *elementNode = [[GCHpAssetsCell alloc] init];
        return elementNode;
    };
}

@implementation GCHpAssetsCell
- (instancetype)init {
    if (self = [super init]) {
        _title0 = ({
            ASTextNode *node = [[ASTextNode alloc] init];
            node.maximumNumberOfLines = 1;
            node.style.height =  ASDimensionMake(21);
            [self addSubnode:node];

            node;
        });
        
        _title1 =({
            ASTextNode *node = [[ASTextNode alloc] init];
            node.maximumNumberOfLines = 1;
            node.style.height =  ASDimensionMake(19);
            [self addSubnode:node];
            node;
        });
        
        _title2 =({
            ASTextNode *node = [[ASTextNode alloc] init];
            node.maximumNumberOfLines = 1;
            node.style.height =  ASDimensionMake(19);
            [self addSubnode:node];

            node;
        });
        _leftArrow = ({
            ASDisplayNode *node = [[ASDisplayNode alloc] init];
            node.backgroundColor = [UIColor clearColor];
            node.style.preferredSize = CGSizeMake(8, 8);
            [self addSubnode:node];
            node;
        });
        _arrow = ({
            ASImageNode *node = [[ASImageNode alloc] init];
            node.image = [UIImage imageNamed:@"gchp_arrow"];
            node.style.preferredSize = CGSizeMake(8, 8);
            [self addSubnode:node];
            node;
        });
        self.backgroundColor = [[UIColor whiteColor]colorWithAlphaComponent:0.0] ;
        
    }
    return self;
}

```

**Comment by garrettmoon** [comment]
@wangyutao0424 I don't think this is an issue with Texture. In our testing we found that calling imageNamed: off the main thread isn't safe, however, calling `imageNamed:inBundle:compatibleWithTraitCollection:` is.

Why not try using `as_imageNamed:` or `as_imageNamed:compatibleWithTraitCollection:` and seeing if that fixes the issue.

**Comment by PatrickChow** [comment]
@garrettmoon Hi,I have same issue on iOS8. So saaaaad, [https://developer.apple.com/documentation/uikit/uiimage/1624154-imagenamed](imageNamed:inBundle:compatibleWithTraitCollection:) , In iOS 9 and later, this method is thread safe.

**Comment by garrettmoon** [comment]
@PatrickChow Have you tried using the methods I suggested?

**Comment by PatrickChow** [comment]
@garrettmoon Yes,[as_imageNamed](https://github.com/TextureGroup/Texture/blob/master/Source/UIImage%2BASConvenience.h#L43) will be crash on iOS 8.1 sometimes. I using [collectionNode:nodeForItemAtIndexPath](https://github.com/TextureGroup/Texture/blob/master/Source/ASCollectionNode.h#L591) instead of [collectionNode:nodeBlockForItemAtIndexPath](https://github.com/TextureGroup/Texture/blob/master/Source/ASCollectionNode.h#L579) to make sure initial node at main thread.
