### ISSUE TITLE
Dirty corner rounding when precomposited

### ISSUE THREAD

**Issue by muukii** [TextureGroup/Texture#717]
I've tried `cornerRoundingType`.
It seems like the precomposited of type makes corner that is dirty.

<img width="836" alt="image 2017-12-15 at 17 22 03" src="https://user-images.githubusercontent.com/1888355/34038416-a9a63e5e-e1cf-11e7-975f-672427907eec.png">

**Comment by hashemp206** [comment]
add this key-value pair to your Info.plist: `UIViewEdgeAntialiasing` set to YES

**Comment by muukii** [comment]
@hashemp206 
Oops. Thank you!
I thought that that option is true by default.
So which means, Will turning true increase cost of render?
Let me know if you know that how will it affect performance?
cc @maicki

**Comment by garrettmoon** [comment]
@muukii I'm guessing it will affect performance, but I don't think there's much you can do about it. However, the performance hit should still be off the main thread so you've got that going for you which is nice.
