### ISSUE TITLE
Negative Layout Position Values

### ISSUE THREAD

**Issue by victorstewart** [TextureGroup/Texture#725]
In order to display full screen video / photos of 1.77 aspect ratio on the iPhone X, I need to set negative X origin values for the layoutPosition, as with the X's aspect ratio of 2.165 it is more width constrained.

Using the absolute spec, doing something like this...

`_metalCamera.style.layoutPosition = CGPointMake( -41, 0);`
` _metalCamera.style.preferredSize = CGSizeMake(457, 812);`

The frame is correct in `didLoad` at { {-41, 0}, {457, 812} }, but by the time we reach `layout`, its frame is incorrect, set to { {0, 0}, {375, 812} }, the screen dimensions. 

I guess I've have to change the internal code for myself to allow negative values? Any pointers to exactly where that is?

**Comment by maicki** [comment]
@victorstewart You may should just move to manual layout and in the `layout` method you adjust the frame of `_metalCamera` directly.

**Comment by victorstewart** [comment]
@maicki success thank you!!!
