### ISSUE TITLE
Suggest Feature: Keywords ( tags ) support instated of ASCollectionNode

### ISSUE THREAD

**Issue by sbhmajd** [TextureGroup/Texture#726]
First, Thank you all very much to make this project open source, I LOVE IT :)

**Problem:**

I was developing ASCollectionNode to support keywords with custom flow layout, Already checked samples code that uses MosaicCollectionViewLayout.swift.

I tried to change the layout to not be static, and used default collection layout, but no luck,
Then i wanted all of the above to support LTR and RTL, here i got stuck and no time.

So, i decide to build custom KeywordNode for this issue, and the result is good enough for me.

**Portrait:**

![simulator screen shot - iphone 8 - 2017-12-25 at 03 55 54](https://user-images.githubusercontent.com/23249321/34331221-6c62663e-e92d-11e7-9646-3cfef4d2c4ee.png)

**Landscape:**

![simulator screen shot - iphone 8 - 2017-12-25 at 03 55 57](https://user-images.githubusercontent.com/23249321/34331225-736b4162-e92d-11e7-84b0-c8c7adbbbdac.png)

So, i want to **share** this for **first time** on my contribution road 👍 

Lets begin:

**Sample Project:**
[Keywords.zip](https://github.com/TextureGroup/Texture/files/1585230/Keywords.zip)

**Usage:**

`

    /// start class

    class DemoKeywordNodeCell: ASCellNode, KeywordNodeDelegate {
    
    var keywordNode: KeywordNode!
    
    init(keywords: [String]) {
        super.init()
        
        let font: UIFont = UIFont.systemFont(ofSize: 14)
        keywordNode = KeywordNode.init(keywords, keywordFont: font, spacingKeyword: 8)
        keywordNode.keywordDelegate = self
        keywordNode.alignItems = .start
        
        self.automaticallyManagesSubnodes = true
        
    }
    
    override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
        
        
        let cellStack = ASStackLayoutSpec.vertical()
        
        let keywordCollectionNodeASInsetLayoutSpec: ASInsetLayoutSpec = ASInsetLayoutSpec(insets: UIEdgeInsets(top: 8, left: 8, bottom: 8, right: 8), child: keywordNode)
        
        cellStack.children = [keywordCollectionNodeASInsetLayoutSpec]
        
        return cellStack
        
    }
    
    func didPressOnKeyword(index: Int, keyword: String) {
        
        print("keyword => \(keyword), at index => \(index)\n")
        
    }
    
    }

    /// end class

`

**Texture version:** Texture (2.5.1)

cc @appleguy 

And happy new year everyone.

**Comment by GeekTree0101** [comment]
If you don't mind, it is enough to distribute on cocoa-pod :)

**Comment by sbhmajd** [comment]
@GeekTree0101, I will do that soon and thanks for reply.
