### ISSUE TITLE
Flashing Bug w/ UIView-wrapped ASDisplayNode

### ISSUE THREAD

**Issue by victorstewart** [TextureGroup/Texture#758]
If you check out the screen record below, aim here is pretty simple. Haven't fully perfected this, but I need to swap the top with the bottom along curved paths.... since it isn't possibly current to move ASDisplayNodes along curved paths (if you try to move the center of the underlying view... it flashes at the end of the animation), I implemented with UIKit and just wrapped the view in an ASDisplayNode.

But.... it ended up flashing anyway lol.

I need to come to some solution on this

https://www.dropbox.com/s/i15qi0aq3kp8iqu/IMG_2203.mov

**Comment by nguyenhuy** [comment]
That looks weird. If it's a wrapped node, the framework doesn't intercept much with its behavior.

Since this is a very old issue, I hope that you figured out the issue 🤞. Feel free to re-open this ticket or open a new one with a way to reproduce this behavior. Thanks!
