### ISSUE TITLE
`collectionNode: nodeBlockForSupplementaryElementOfKind kind: at indexPath` not called

### ISSUE THREAD

**Issue by brod-ie** [TextureGroup/Texture#762]
```
// Not called 😭

func collectionNode(_ collectionNode: ASCollectionNode, nodeBlockForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> ASCellNodeBlock {
    return {
        return ASLoadingCell()
    }
}

// Called 😍

func collectionNode(_ collectionNode: ASCollectionNode, supplementaryElementKindsInSection section: Int) -> [String] {
    return [UICollectionElementKindSectionFooter, UICollectionElementKindSectionHeader]
}
```

The delegate for the ASCellNode isn't being fired for my supplementary nodes. I'm returning the above in `supplementaryElementKindsInSection` which I can successfully break therefore is being triggered. What am I missing? I would include the source of `ASLoadingCell()` but it's not getting that far!

**Comment by ay8s** [comment]
Does registering the supplementary nodes enable those?

```
[self.collectionNode registerSupplementaryNodeOfKind:UICollectionElementKindSectionHeader];
[self.collectionNode registerSupplementaryNodeOfKind:UICollectionElementKindSectionFooter];
```

**Comment by brod-ie** [comment]
Thanks @ay8s but unfortunately still not called! What I added in Swift:
```
self.collectionView.registerSupplementaryNode(ofKind: UICollectionElementKindSectionHeader)
self.collectionView.registerSupplementaryNode(ofKind: UICollectionElementKindSectionFooter)
```

**Comment by ay8s** [comment]
Just checked out implementation. We use the following instead of the node block method. Not sure if that will have any effect. 
```
- (ASCellNode *)collectionNode:(ASCollectionNode *)collectionNode nodeForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
```

**Comment by brod-ie** [comment]
Still not firing! To confirm, in my `viewDidLoad`:

```
self.collectionView.registerSupplementaryNode(ofKind: UICollectionElementKindSectionHeader)
self.collectionView.registerSupplementaryNode(ofKind: UICollectionElementKindSectionFooter)
```

And as in my `ASCollectionDataSource`

```
func collectionNode(_ collectionNode: ASCollectionNode, nodeForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> ASCellNode {
    return ASLoadingCell()
}

func collectionNode(_ collectionNode: ASCollectionNode, supplementaryElementKindsInSection section: Int) -> [String] {
    return [UICollectionElementKindSectionFooter, UICollectionElementKindSectionHeader]
}
```

At this rate, I'll have to add the loading indicator to the topmost cell

**Comment by maicki** [comment]
@brod-ie Do you use `ASCollectionNode` or `ASCollectionView`? From your code snippet it seems you use `ASCollectionView` and you expect an `ASCollectionNode` callback. Furthermore if you set a breakpoint were we call the delegate method is it hit or not?

**Comment by brod-ie** [comment]
`ASLoadingCell` is a subclass of `ASCellNode`, `supplementaryElementKindsInSection ` fired but `nodeForSupplementaryElementOfKind ` did not

**Comment by maicki** [comment]
@brod-ie It's not the `ASCellNode` I mean. I mean do you use `ASCollectionView` or `ASCollectionNode`? Can you just post your controller code that bootstraps the `ASCollectionNode` / `ASCollectionView` please.

**Comment by rainypixels** [comment]
@ay8s @maicki I'm hitting the issue @brod-ie is hitting as well. 

I've set the delegate and datasource appropriately (I'm using the `ASCollectionNode`, and the rest of my implementation, including multiple-sections and batch fetching, have been working like a charm for a few months now). I also set breakpoints in both these datasource methods:

```
public func collectionNode(_ collectionNode: ASCollectionNode, nodeForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> ASCellNode { }

public func collectionNode(_ collectionNode: ASCollectionNode, nodeBlockForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> ASCellNodeBlock { }
```

Neither of the breakpoints are hit but the breakpoint set in `supplementaryElementKindsInSection` is hit multiple times.

**Comment by maicki** [comment]
@rainypixels @brod-ie Here is an example project. You also have to either set the `headerReferenceSize` of the `UICollectionViewLayout` you use or implement `collectionNode:sizeRangeForHeaderInSection`:

[CollectionNodeSupplementaryExample.zip](https://github.com/TextureGroup/Texture/files/1683539/CollectionNodeSupplementaryExample.zip)

**Comment by rainypixels** [comment]
@maicki Thanks much for the example project, and the tip about header sizing! Worked like a charm once I realized I was missing that. And thanks to layout specs, I get self-sizing for free by returning `ASSizeRangeUnconstrained` in `collectionNode:sizeRangeForHeaderInSection:`. 🎉

**Comment by maicki** [comment]
Great to hear. I will close this issue as it seems to be resolved.

**Comment by JoeFerrucci** [comment]
fwiw, i can only get a header to work if i set the header reference size on the layout. i have the collectionNode:sizeRangeForHeaderInSection implemented but it never gets called; whether or not i've set header reference size on layout. what a pain.
