### ISSUE TITLE
layoutSpecThatFits not called only in Release build configuration

### ISSUE THREAD

**Issue by tungvoduc** [TextureGroup/Texture#766]
I am using this library https://github.com/Yalantis/Koloda in my app for card swiping.

I need to provide an UIView in the following datasource method:

`
func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {      
        return nextCardNode(index).view
}

func nextCardNode(_ index: Int) -> ASDisplayNode {
       return SwipingLoadingNode()
}
`

The library, after getting UIView returned from **koloda(_ koloda: KolodaView, viewForCardAt index: Int) **, will apply constraints to this UIView instance. Every thing works fine in debug environment, the ASDisplayNode instance gets correct frame, **layout** and **layoutSpecThatFits** methods are called. In Release environment, however, they are not getting called, resulting that all subnodes are not displayed but background color is showing correctly. 

What do you think could be the problem here?

**Comment by tungvoduc** [comment]
@Specscd One library that I use asks for UIView so I return node.view and somehow it did not work.
If you have same problem then you can try create an UIView class that wraps the node. In layoutSubviews of UIView class, just set the node frame to its superview's bounds.

**Comment by Specscd** [comment]
![snip20180408_23](https://user-images.githubusercontent.com/17806563/38463310-70032df6-3b2a-11e8-8023-bfda68087186.png)
it still doesn't work,do you have any idea?

**Comment by Specscd** [comment]
thank you very much, it works.
