### ISSUE TITLE
ASEditableTextNode ->  isSecureTextEntry , not working

### ISSUE THREAD

**Issue by lutetium71** [TextureGroup/Texture#781]
ASEditableTextNode ->  isSecureTextEntry , not working

version:  2.5.1

**Comment by ay8s** [comment]
@lutetium71 I don't believe this is supported right now. I've been using UITextField in a few of my projects for this. Also spotted theres a ASTextFieldNode which also does this. https://github.com/pocketlabs/ASTextFieldNode
