### ISSUE TITLE
ASCollectionNode & ASTableNode dealloc failing Main Thread Checker

### ISSUE THREAD

**Issue by johntmcintosh** [TextureGroup/Texture#804]
#793 introduced a new implementation of `dealloc` to `ASCollectionNode` and `ASTableNode` which asserts that the view's superview must be nil. 

```
- (void)dealloc
{
  if ([self isNodeLoaded]) {
    ASDisplayNodeAssert(self.view.superview == nil, @"Node's view should be removed from hierarchy.");
  }
}
```

However, I'm now seeing in my application that the main thread checker is failing when I deallocate an `ASCollectionNode` because `dealloc` is being called on a background thread:

```
-[UIView superview] must be used from main thread only
```

Looking at the stacktrace I get when in `dealloc`, it looks like `ASDisplayNode`'s `dealloc` is explicitly handling the fact that it may be called off the main thread, so I suspect that's something that needs to be accounted for in `ASCollectionNode` and `ASTableNode` as well. 

I'm not sure whether the right fix is not having the assertion, or doing something else to move the deallocation to the main thread.

**Comment by nguyenhuy** [comment]
Hi there, thanks for reporting. #803 should fix this issue. Please let us know otherwise!

**Comment by johntmcintosh** [comment]
Thanks @nguyenhuy ! I've confirmed this is resolved for me in the latest on master. Closing out.
