### ISSUE TITLE
My project can't download from cocoapods

### ISSUE THREAD

**Issue by UnicomMrLee** [TextureGroup/Texture#815]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack (we'll be updating the name to Texture soon)

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// Texture version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

**Comment by UnicomMrLee** [comment]
Its so long time ,then ,it cant download

**Comment by bawn** [comment]
@UnicomMrLee  Check your network when necessary using VPN

**Comment by nguyenhuy** [comment]
I don't think this is a framework issue. Please feel free to open new tickets if you have other issues. Thank you.
