### ISSUE TITLE
[ASPagerNode] Layout bug introduced by 2618c5 #788

### ISSUE THREAD

**Issue by flovouin** [TextureGroup/Texture#845]
Hi guys,

While upgrading Texture in my App, I encountered a layout bug about a month ago. I promised a sample project but then forgot about it. At last, here it is: https://github.com/flovouin/Texture-PagerNodeLayoutBug

It occurs when using the `ASPagerNode` full screen and... well that's it. There's not much more to it: the cells do not take the full pager node frame, and leave an inset at the top.

The bug has been around since `2618c5` and still happens on `master`. The same behaviour (which might be intentional in this case?) can also be observed in previous versions by setting `allowsAutomaticInsetsAdjustment` to `true` in the `ASPagerNode`.

As always, I can provide more details on request. :-)

Cheers,

Flo

**Comment by nguyenhuy** [comment]
Thanks for helping to test `master` and reporting issues. The new run loop queue introduced in `2618c5` has been known to be a bit unstable at the moment. We had to disable it in the Pinterest app. Now that we have a new framework-level config/experiment functionality, we'll probably make an opt-in option for using the new queue.

**Comment by appleguy** [comment]
@flovouin for the short term, try syncing past https://github.com/TextureGroup/Texture/pull/862 and make sure all is well!

Thanks a lot for reporting, and especially the repro case. @wsdwsd0829 and I will look into it.

**Comment by flovouin** [comment]
Thanks @nguyenhuy and @appleguy for the replies!
Looks like #862 solves the problem for both the sample project and my app.
I'll reopen this if I notice something strange again.

Cheers,

Flo
