### ISSUE TITLE
The CI Can Fail with a Bizarre Cocoapods Working Tree Issue

### ISSUE THREAD

**Issue by Adlai-Holler** [TextureGroup/Texture#85]
https://github.com/TextureGroup/Texture/pull/82#issuecomment-298092446

It's fine to close this and say "not worth the effort" – we've only seen it once. But we should at least give it a look-see. @garrettmoon

**Comment by garrettmoon** [comment]
@Adlai-Holler this was temporary, due to testing a new VMWare instance.
