### ISSUE TITLE
Custom flow layout did not work in ASCollectionNode ,But work in UICollectionView

### ISSUE THREAD

**Issue by yaxunliu** [TextureGroup/Texture#859]
ASCollectionNode : 
![issue](https://user-images.githubusercontent.com/22487604/38003850-0a1ab75a-326c-11e8-8204-7296588d87b9.png)
UICollectionView:
![normal](https://user-images.githubusercontent.com/22487604/38003858-1147f09c-326c-11e8-8c24-135a270d1135.png)

I used the same flowLayout but got an unusual result in ASCollectionNode

[Demo](https://github.com/yaxunliu/Chat)

ASCollectionNode:

```swift
let layout = EmojiFlowLayout()
let collecNode = ASCollectionNode(collectionViewLayout: layout)
collecNode.view.isPagingEnabled = true
collecNode.dataSource = self
collecNode.delegate = self


```

**Comment by buithuyen** [comment]
I have faced same thing, do you guys have any suggestion?

**Comment by nguyenhuy** [comment]
Hi, custom collection view layouts don't work out of the box. Please check out our [examples](https://github.com/TextureGroup/Texture/tree/master/examples), such as "[CustomCollectionView](https://github.com/TextureGroup/Texture/tree/master/examples/CustomCollectionView)". Thank you.

**Comment by nikmun** [comment]
It is happening with me too. The Demo of "CustomCollectionView" has initialiser "initWithLayoutDelegate" for ASCollectionLayoutDelegate but in current version of texture there is no such initialiser. So we have only one initialiser name "initWithCollectionViewLayout" in which we can only give CollectionViewFlowLayout object which is not working internally while accessing collection view inside it. What should I do now?
