### ISSUE TITLE
Swift4.1 initialization error

### ISSUE THREAD

**Issue by shevakuilin** [TextureGroup/Texture#865]
Hi,
Today I updated xcode to version 9.3 and then run my project. In the swift4.1 environment, the initialization method of ASViewController directly reports an error:

'self' used in property access 'timeline' before 'super.init' call

my code:

```
lazy var timeline = ASTableNode().then {
        $0.delegate = self
        $0.dataSource = self
        $0.backgroundColor = kColor(239, 242, 245)
        $0.view.separatorStyle = .none
        $0.autoresizingMask = [.flexibleWidth, .flexibleHeight]
    }

init() {
        super.init(node: timeline) // error: 'self' used in property access 'timeline' before 'super.init' call
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

Before swift4.1, everything worked, I didn't know exactly what happened, I hope I can get help.

**Comment by shevakuilin** [comment]
This may be the stricter grammar requirement of swift 4.1. When I replace the lazy loading timeline, everything becomes normal.

```
private var timeline = ASTableNode()

init() {
        super.init(node: timeline) 
        timeline.delegate = self
        timeline.dataSource = self
        timeline.backgroundColor = kColor(239, 242, 245)
        timeline.view.separatorStyle = .none
        timeline.autoresizingMask = [.flexibleWidth, .flexibleHeight]
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

[whats-new-in-swift-4-1](https://www.raywenderlich.com/187826/whats-new-in-swift-4-1)
[texturegroup.org](http://texturegroup.org/docs/containers-asviewcontroller.html)

**Comment by rainypixels** [comment]
@shevakuilin — Were you able to link Texture and dependencies successfully for use with Xcode 9.3? I'm facing SIGABRT errors when I build (`dyld: Symbol not found: _PINDiskCachePrefix`). Presumably you're using Cocoapods? Carthage support for Texture has always had issues...
