### ISSUE TITLE
editingTransactionQueueBusy = YES, but _editingTransactionGroupCount = 0

### ISSUE THREAD

**Issue by hashemp206** [TextureGroup/Texture#914]
I'm using latest version of Texture cloned from GitHub.
but occasionally I face this strange issue:

`'NSInternalInconsistencyException', reason: 'editingTransactionQueueBusy = YES, but _editingTransactionGroupCount = 0 !'`

any Idea whats going on?

<img width="1056" alt="screen shot 2018-05-08 at 2 53 42 pm" src="https://user-images.githubusercontent.com/3206748/39752160-d367b3c8-52cf-11e8-846d-f33ef349906c.png">

<img width="300" alt="screen shot 2018-05-08 at 2 53 43 pm" src="https://user-images.githubusercontent.com/3206748/39752329-5625921c-52d0-11e8-8e26-9cb86578c8d1.jpg">

**Comment by appleguy** [comment]
@hashemp206 I have an idea for how this is happening. Could you "bt all" if you can trigger this again? Specifically I need to see what the other threads are doing, to understand if it is possible that one of them has just decremented the Count variable but a block is still running.

If you could also log out the values for Busy and Count at the time of the assert, that might be enough to create a theoretical fix.

**Comment by hashemp206** [comment]
@appleguy I tried hard now to reproduce it but doesn't happen right now! I will try more

**Comment by hashemp206** [comment]
@appleguy today it happened, accidentally one more time after application launch:
count is 0 and busy is Yes

<img width="300" alt="screen shot 2018-05-08 at 2 53 43 pm" src="https://user-images.githubusercontent.com/3206748/39992676-da33c2f6-5788-11e8-869c-27ab5b22adfa.jpg">
<img width="300" alt="screen shot 2018-05-08 at 2 53 43 pm" src="https://user-images.githubusercontent.com/3206748/39992681-df2468f6-5788-11e8-8637-49f14f1e2f2c.jpg">

**Comment by appleguy** [comment]
@hashemp206 thanks again for reporting this. We found out that, ironically, this assertion was invalid even though the code was valid. That is to say, the assertion required transactional integrity between two bits of state (the atomic counter, and the queue), which is actually not required if only the counter is being referenced. So, all should be well if you update.
