### ISSUE TITLE
didUpdateToObject is meaningless

### ISSUE THREAD

**Issue by YasinZhou** [TextureGroup/Texture#941]
If the model changes, the `SectionController` will be regenerated, so the `didUpdateToObject` is meaningless. Why not just write it in `init`

**Comment by Adlai-Holler** [comment]
Hi @YasinZhou `didUpdateToObject` is https://github.com/Instagram/IGListKit functionality. Is your issue specifically with Texture's integration?

**Comment by YasinZhou** [comment]
Sorry, I made a mistake.
