### ISSUE TITLE
Show shared UIMenuController from a ASCellNode is not working anymore

### ISSUE THREAD

**Issue by nixzhu** [TextureGroup/Texture#957]
Hi, guys. I have a ASCellNode subclass when user tap on it with gesture to show a UIMenuController.

The code as follow:

``` swift 
view.becomeFirstResponder()
let menuController = UIMenuController.shared
menuController.menuItems = menuItems
menuController.setTargetRect(contentNode.frame, in: view)
menuController.setMenuVisible(true, animated: true)
```

It works on Texture 2.6 but not work on Texture 2.7. The `becomeFirstResponder()` return false now.

I have

``` swift
override func canBecomeFirstResponder() -> Bool {
    return true
}
```

which is called.

It there anything I need to do in Texture 2.7?

**Comment by BrandonZacharie** [comment]
I'm having the same issue but with `ASDisplayNode`

**Comment by maicki** [comment]
@nixzhu @BrandonZacharie Hey - do you also overwrite `becomeFirstResponder()` and become the first responder while responding with `true`?

**Comment by BrandonZacharie** [comment]
No. What should be done in that override?

**Comment by nixzhu** [comment]
@maicki Hi, I have try to override the `becomeFirstResponder()`, which is called, the `let result = becomeFirstResponder()` is true, but UIMenuController.shared is still not visible after `setMenuVisible(:animated:)`

``` swift
override func becomeFirstResponder() -> Bool {
    return true
}
```

**Comment by BrandonZacharie** [comment]
I had the same result.

**Comment by maicki** [comment]
Would some of you please so kind and provide a small example project so  I can debug it? Would appreciate that! Thanks!

**Comment by nixzhu** [comment]
@maicki I'll try to create a demo project tomorrow.

**Comment by nixzhu** [comment]
@maicki Hi, the demo at https://github.com/nixzhu/TextureDemo can reproduce this issue. Search `showMenu` in the project (Long press on cell to show the test menu). Texture version is 2.6 in the `Podfile`, which it works. You can change it to 2.7 to debug it.

**Comment by lucabecchetti** [comment]
same issue.

**Comment by maicki** [comment]
@nixzhu @BrandonZacharie @lucabecchetti Sorry for the late respond. I looked into that and in 2.7 we did changes to handling the responder chain between `ASDisplayNode` and the backing view. I have a branch up that should address this issue in Texture and it should work properly going forward after we merge this into master. Unfortunately within 2.7 there is a workaround necessary:

1. Create a new subclass of `_ASDisplayView`:
```
// _ASDisplayView subclass that can become first responder
class _ASDisplayViewCanBecomeFirstResponder : _ASDisplayView {
    override var canBecomeFirstResponder: Bool {
        return true
    }
}
```
2. Implement the following in your `ASDisplayNode`:
// Set the view class to a custom display view class to become first responder
@objc class func viewClass() -> AnyClass {
  return _ASDisplayViewCanBecomeFirstResponder.self
}
override func canBecomeFirstResponder() -> Bool {
  return true
}
```
Please let  me know if this helps. Thanks!

**Comment by nixzhu** [comment]
@maicki Thank you, I will give it a try.

**Comment by nixzhu** [comment]
@maicki This workaround works!

**Comment by BrandonZacharie** [comment]
@maicki, when will your patch be released?
