### ISSUE TITLE
LOTAnimation(lottie) does not work animation in ASCellNode

### ISSUE THREAD

**Issue by Kofktu** [TextureGroup/Texture#966]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack (we'll be updating the name to Texture soon)

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// Texture version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

When using LOTAnimationView in ASCellNode, 
add and layout works well,  but animation does not work.
Also, addAnimation on CALayer is not the same.

<img width="377" alt="2018-06-13 10 19 29" src="https://user-images.githubusercontent.com/1860205/41365603-c75b3804-6f74-11e8-8c12-12cf362183be.png">

- 
```swift
class AnimationCellNode: ASCellNode {
    init() {
       automaticallyManagesSubnodes = true
    }

    func layoutSpecFit(_ ...) -> ASLayoutSpec {
        return ASInsetlayout(....)
    }

}

class AnimationNode: ASDisplayNode {
    init() {
       super.init()
       setViewBlock ( LOTAnimationView(..) )
       style.preferredSize = CGSize
    }

   func didLoad() {
       lotView.startAnimation()
   }
}
```

**Comment by GeekTree0101** [comment]
Try to bring lotView from superView(such as ViewController root view or TabView) 
ex). superview.bringSubview(toFront: lotView)

**Comment by GeekTree0101** [comment]
or move startAnimation call onto animateLayoutTransition
http://texturegroup.org/docs/layout-transition-api.html

**Comment by Kofktu** [comment]
@GeekTree0101 
I changed startAnimation() called by animateLayout 
but it did not work, 
so I added it to the tableView and finished processing it. T_T

**Comment by peakerWu** [comment]
@Kofktu hi, I have the same problem for useing . can you show me your code?

**Comment by peakerWu** [comment]
@Kofktu  It means you didn't use texture in the end. Is it?

**Comment by Kofktu** [comment]
@peakerWu 
Hi,
I added to the tableView,
i did start/stopAnimation() in the didScroll method.

But!
i found a way to test it.

called start/stopAnimation() in
```swift
override func didEnterVisibleState() {
    super.didEnterVisibleState()
    startAnimation()
}
 
override func didExitVisibleState() {
    super.didExitVisibleState()
    stopAnimation()
}
```
i confirmed that it works normally

**Comment by peakerWu** [comment]
thx. have done it.
