### ISSUE TITLE
[ASDisplayNode] setNeedsLayout doesn't work only Texture 2.7

### ISSUE THREAD

**Issue by GeekTree0101** [TextureGroup/Texture#977]
[similar issue](https://github.com/TextureGroup/Texture/issues/964)
In my case, I forced setNeedLayout after textNode attributedText value with a few sec delay

```swift
     Observable.just(NSAttributedString(string: "test")
            .delay(2.0, scheduler: MainScheduler.asyncInstance) // a few sec delay
            .subscribe(onNext: { [weak self] value in 
                    self?.textNode.attributedText = value // update attributedText (data)
                    self?.setNeedsLayout()  // call setNeedsLayout
             }
            .disposed(by: disposeBag)
```

Texture 2.6 is correctly work like this picture
<img width="290" alt="v2 6" src="https://user-images.githubusercontent.com/19504988/41608900-8e2d6962-7424-11e8-819b-3c9515814f0a.png">

But, I got unwanted UI in Texture 2.7 like this picture
<img width="294" alt="v2 7" src="https://user-images.githubusercontent.com/19504988/41609025-d0a090f8-7424-11e8-8489-62ad971d9428.png">

I check frame value from debugger
![2018-06-19 6 38 55](https://user-images.githubusercontent.com/19504988/41609066-e9e57cfe-7424-11e8-942a-bde063f83381.png)
I found that UITableViewCellContentView frame isn't equal with ASCellNode frame

So, just update ASCellNode frame with UITableViewCellContentView frame on didEnterVisibleState like this code
```swift
    override func didEnterVisibleState() {
        super.didEnterVisibleState()
        self.frame = self.view.superview?.frame ?? self.frame
    }
```
In this case, it's correctly work like this pic
<img width="303" alt="2018-06-20 12 49 40" src="https://user-images.githubusercontent.com/19504988/41609310-73a6cf42-7425-11e8-9d1d-8bc0f9adc1d3.png">

**Comment by hashemp206** [comment]
I have faced such issue when I was changing collection node layout when rotating device. what I did was I write a custom collection flow layout using `ASCollectionLayoutDelegate`  to calculate node frame

**Comment by GeekTree0101** [comment]
When Rx subscribe logic moves  from initialization to didLoad method. I no longer faced this problem. 
When using RxSwift / RxCocoa, it is safe to subscribe from the didLoad method.

**Comment by GeekTree0101** [comment]
<img width="1047" alt="2018-07-27 9 15 04" src="https://user-images.githubusercontent.com/19504988/43334679-cd84dbca-9208-11e8-8442-4cc3a63b7419.png">
It is still a problem. I don't know that why constraintedSize min and max are equal & doesn't change after setNeedsLayout.

**Comment by GeekTree0101** [comment]
i solve this issue like this
```swift
        ASPerformBlockOnMainThread {
            self.invalidateCalculatedLayout()
            self.setNeedsLayout()
            self.layoutIfNeeded()
        }
```

**Comment by GeekTree0101** [comment]
close!

**Comment by GeekTree0101** [comment]
no way still has problem TT
