### ISSUE TITLE
Memory leaks with ASNetworkImageNode in ASCellNode

### ISSUE THREAD

**Issue by dhatuna** [TextureGroup/Texture#978]
Hi, there are some unexpected memory leaks when I load a web image via ASNetworkImageNode in  ASCollectionNode. I set the URL on -didEnterDisplayState function. Here's the code of the cell:

    private let imageNode = ASNetworkImageNode()
    
    private let backupData: PostData!
    var data: PostData {
        return backupData
    }
    
    init(with postData: PostData, showHaveIt: Bool = false) {
        backupData = postData
        
        super.init()
        
        self.selectionStyle = .none
        
        imageNode.backgroundColor = UIColor.wishpokeF7f7f7
        imageNode.style.preferredSize = PostMatrixCellNode.itemSize
        imageNode.contentMode = .scaleAspectFill
        imageNode.clipsToBounds = true
        
        if let imageUrl = self.data.imageUrls?.first?.absUrlString {
            imageNode.url = URL(string: imageUrl)
        }
        
        self.addSubnode(imageNode)
    }
    
    override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
            return ASAbsoluteLayoutSpec(children: [imageNode])
    }
    
    override func didEnterDisplayState() {
        super.didEnterDisplayState()
        
        guard let imageUrl = self.data.imageUrls?.first?.absUrlString else {return}
        
        let queue = DispatchQueue(label: "loadCellImage", qos: .background, attributes: .concurrent, autoreleaseFrequency: .workItem, target: nil)
        queue.async {
            self.imageNode.setURL(URL(string: imageUrl), resetToDefault: false)
        }
    }
    
    override func didExitDisplayState() {
        super.didExitDisplayState()
        
        self.imageNode.setURL(nil, resetToDefault: false)
    }

And whenever I scroll down the collectionNode, memory leaks occur on GCD 
like this:

![os_dispatch_group](https://user-images.githubusercontent.com/6669243/41641255-b38e248c-749f-11e8-9761-e1330313f5ea.png)

Any suggestions are welcomed!
Many thanks!

**Comment by GeekTree0101** [comment]
Try to insert weak reference on async queue
for example

```
override func didEnterDisplayState() {
    super.didEnterDisplayState()
    
    guard let imageUrl = self.data.imageUrls?.first?.absUrlString else {return}
    
    let queue = DispatchQueue(label: "loadCellImage", qos: .background, attributes: .concurrent, autoreleaseFrequency: .workItem, target: nil)
    queue.async { [weak self] () -> () in // <---- here
        self?.imageNode.setURL(URL(string: imageUrl), resetToDefault: false)
    }
}
```

**Comment by dhatuna** [comment]
Hi! @GeekTree0101 .
Thanks for your great help.

Your suggestion reduces some issues and works pretty!!
For others, there were some reference cycles on my codes.

Thank you very much again!
