### ISSUE TITLE
Declaration 'init()' cannot override more than one superclass declaration

### ISSUE THREAD

**Issue by hashemp206** [TextureGroup/Texture#983]
I get  the above error when compiling the project using Xcode 10 beta 2, when overriding `ASViewController` `init` method. 

to test run texture swift sample project

<img width="775" alt="screen shot 2018-06-23 at 3 02 02 pm" src="https://user-images.githubusercontent.com/3206748/41808680-714d9af4-76f6-11e8-9e55-3138519c6a5a.png">

any idea?

**Comment by Flatout73** [comment]
Same

**Comment by maicki** [comment]
This was an issue on the Swift side and huge thanks to @DougGregor and @jrose-apple for fixing it for the next release.

Until than I think the workaround mentioned in my last comment will work, so I will close this issue.
