### ISSUE TITLE
The calculation of flex-basis is different from iPhoneX and other

### ISSUE THREAD

**Issue by shima11** [TextureGroup/Texture#986]
We discovered that the size of Node varies depending on the device.
[Sample Project (Github)](https://github.com/shima11/texture-practice)

We confirmed the node width on iPhone 8 and iPhoneX by debug view hierarchy.
The screen width is 375.
The child node width in iPhone 8 is 187.5.
The child node width in iPhoneX is 187.667.

iPhone8
<img width="1512" alt="flexbasis_iphone8" src="https://user-images.githubusercontent.com/7531826/41818110-f090d46a-77e2-11e8-91bf-805f4e5e26e8.png">

iPhoneX
<img width="1512" alt="flexbasis_iphonex" src="https://user-images.githubusercontent.com/7531826/41818112-f3b5ec2a-77e2-11e8-9834-af472d8a89f3.png">

> Xcode 9.3
> Simulator: iPhone8 and iPhoneX

Is this a bug?

**Comment by GeekTree0101** [comment]
Try to setup justifyContent as .spaceBetween

**Comment by GeekTree0101** [comment]
@Adlai-Holler Oh i see, i just saw @shima11 code(Sample Project (Github))
```
    override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {

        return ASStackLayoutSpec(
            direction: .horizontal,
            spacing: 0,
            justifyContent: .start,
            alignItems: .start,
            flexWrap: .wrap,
            alignContent: .start,
            lineSpacing: 0,
            children: boxes
        )
    }
```
In this case, flexWrap should be **.noWrap**, is it right?

**Comment by shima11** [comment]
@Adlai-Holler I got it !! Thank you for your explanation.
@GeekTree0101 Thanks, Ok I see.
