### ISSUE TITLE
how to remove animation in ASCellNode.setNeedDisplay when change height

### ISSUE THREAD

**Issue by Kofktu** [TextureGroup/Texture#994]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack (we'll be updating the name to Texture soon)

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// Texture version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

ASCellNode height change inside ASTableNode
problem is that height of the cell animates according to its layout
i can't find the way to control animation duration of height change.

1) call `setNeedLayout()`on cell node, it's animated
    i changed `defaultLayoutTransitionDuration`of cell do not change animation duration
2) If i call `transitionLayoutWithAnimation` on cell node nothing happens. Height change is not animated.
3) I called `setNeedLayout` and called `layoutIfNeeded` right away.
    but, same...
4) CATransaction
```swift
CATransaction.begin
CATransaction.setDisableActions(false)
cell.setNeedLayout()
CATransaction.commit
```
5) UIView.animation
```swift
UIView.setAnimationEnabled(false)
cell.setNeedLayout()
UIView.setAnimationEnabled(true)
```

T_T.. i can't remove animation
I tested one trick and tried to remove the animation as I wanted.

```swift
UIView.setAnimationsEnabled(false)
tableNodeController.node.performBatch(animated: false, updates: {
        node.setNeedsLayout()
}) { (_) in
        dispatch_after(delay: node.defaultLayoutTransitionDuration, closure: {
            UIView.setAnimationsEnabled(true)
        })
}
```

Once you have done the above code, 
I want to have one more, more reliable way to work.

**Comment by kangfugui** [comment]
@Kofktu hi, the issue is resolve?
