### ISSUE TITLE
tableNode insertRows dropped frames

### ISSUE THREAD

**Issue by CivelXu** [TextureGroup/Texture#995]
```
                    var indexPaths = [IndexPath]()
                    let newDataNum = new.count
                    let allDataNum = allDatas.count
                    let begin = allDataNum - newDataNum
                    
                    for now in begin...(allDataNum - 1) {
                        let path = IndexPath(row: now, section: 0)
                        indexPaths.append(path)
                    }
                    self.tableNode.insertRows(at: indexPaths, with: .none)
```

I  insert new data into tableNode; AstableNode will dropped frames when inset 
I' don't know why; I review my code for a long time and don't find the reason;
Is any suggest for me
I really need  help !!

**Comment by GeekTree0101** [comment]
Try to use performBatch method
```
 self.tableNode.performBatch(animated: true, updates: { [weak self] () in
    self?.tableNode.insertRows(at: indexPaths, with: .none)
}, completion: { _ in .... })
```

**Comment by CivelXu** [comment]
I try to use this  performBatch method;
 dropped frames still exist;

**Comment by CivelXu** [comment]
I fix this

**Comment by lohenyumnam** [comment]
> I fix this

How did you fixed it ??

**Comment by lohenyumnam** [comment]
Well I fetch the data from server and  when the fetch is complete I call it using delegate.
and inside that delegate method the add the new data

This is the Method

```
    func moreCategoryProfileFetchDidComplete(for type: CategoryFeedType, feed: CategoryProfileFeed?) {

        if let newTopics = feed?.category.topics {
            topics.append(contentsOf: newTopics)
            let indexRange = (topics.count - newTopics.count ..< topics.count )
            let indexPaths = indexRange.map { IndexPath(row: $0, section: 1) }
            
            DispatchQueue.main.async {
                self.collectionNode.insertItems(at: indexPaths)
                self.batchcontext?.completeBatchFetching(true)
            }
        }
    }
```

**Comment by CivelXu** [comment]
I agree with you

**Comment by lohenyumnam** [comment]
So any advice for me ?? how can I fixed the frame drop every time this performBatchUpdates is called

**Comment by CivelXu** [comment]
1. insert indexpaths，not reload all tableview
2. during performBatchUpdates begin and end，Do not have the operation that hinders the main thread
3. check the right flex layout and make view layer back as far as possible

I am just getting started, I hope I can be useful to you.




| |
xuxiwen785
邮箱：xuxiwen785@163.com
|

Signature is customized by Netease Mail Master

On 01/18/2019 01:52, Lohen wrote:

So any advice for me ?? how can I fixed the frame drop every time this performBatchUpdates is called
